Repository graphql/graphql-js, pull requests merged in 2018-08, with the labels that each got.

#1441 Allows to add schema definition missing in the original schema
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/extendSchema.js
Labels: CLA Signed

#1443 Convert 'GraphQL*Config' to exact types (part 2)
  src/type/directives.js
  src/type/schema.js
Labels: CLA Signed, semver major

#1445 Drop Node 9 support
  .travis.yml
  package.json
Labels: CLA Signed, semver major

#1444 Update deps
  .flowconfig
  package.json
  src/subscription/__tests__/subscribe-test.js
  yarn.lock
Labels: CLA Signed

#1446 Split out 'ASTValidationContext'
  src/utilities/isValidLiteralValue.js
  src/validation/ValidationContext.js
  src/validation/index.js
  src/validation/rules/ExecutableDefinitions.js
  src/validation/rules/FieldsOnCorrectType.js
  src/validation/rules/FragmentsOnCompositeTypes.js
  src/validation/rules/KnownArgumentNames.js
  src/validation/rules/KnownDirectives.js
  src/validation/rules/KnownFragmentNames.js
  src/validation/rules/KnownTypeNames.js
  src/validation/rules/LoneAnonymousOperation.js
  src/validation/rules/NoFragmentCycles.js
  src/validation/rules/NoUndefinedVariables.js
  src/validation/rules/NoUnusedFragments.js
  src/validation/rules/NoUnusedVariables.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
  src/validation/rules/PossibleFragmentSpreads.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/rules/ScalarLeafs.js
  src/validation/rules/SingleFieldSubscriptions.js
  src/validation/rules/UniqueArgumentNames.js
  src/validation/rules/UniqueDirectivesPerLocation.js
  src/validation/rules/UniqueFragmentNames.js
  src/validation/rules/UniqueInputFieldNames.js
  src/validation/rules/UniqueOperationNames.js
  src/validation/rules/UniqueVariableNames.js
  src/validation/rules/ValuesOfCorrectType.js
  src/validation/rules/VariablesAreInputTypes.js
  src/validation/rules/VariablesInAllowedPosition.js
  src/validation/specifiedRules.js
  src/validation/validate.js
Labels: CLA Signed

#1447 Fix typo in runtime type exception
  src/execution/__tests__/abstract-test.js
  src/execution/execute.js
Labels: CLA Signed

#1449 Fix "watch" command. Remove 'babel-node'
  package.json
  resources/watch.js
  yarn.lock
Labels: CLA Signed

#1438 [RFC]SDL validation
  src/type/__tests__/validation-test.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
  src/validation/ValidationContext.js
  src/validation/__tests__/KnownDirectives-test.js
  src/validation/__tests__/UniqueDirectivesPerLocation-test.js
  src/validation/__tests__/harness.js
  src/validation/rules/KnownDirectives.js
  src/validation/rules/LoneSchemaDefinition.js
  src/validation/specifiedRules.js
  src/validation/validate.js
Labels: CLA Signed, semver major

#1450 Remove unused dev dependencies
  .babelrc.js
  .eslintrc.yml
  package.json
  yarn.lock
Labels: CLA Signed

#1452 Fix imports in 'watch' script
  resources/watch.js
Labels: CLA Signed

#1453 Update deps
  .flowconfig
  package.json
  yarn.lock
Labels: CLA Signed

#1451 Generate error per duplicate schema def + Extend tests
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/validation/__tests__/KnownDirectives-test.js
  src/validation/__tests__/LoneSchemaDefinition-test.js
  src/validation/rules/LoneSchemaDefinition.js
Labels: CLA Signed

#1437 [RFC] Allow directives on variable definitions
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/language/ast.js
  src/language/directiveLocation.js
  src/language/parser.js
  src/language/printer.js
  src/language/visitor.js
  src/type/__tests__/introspection-test.js
  src/type/introspection.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/validation/__tests__/KnownDirectives-test.js
  src/validation/__tests__/harness.js
  src/validation/rules/KnownDirectives.js
Labels: CLA Signed, spec RFC

#1454 VariableDefinition Directives: hide behind experimental flag
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/language/parser.js
  src/validation/__tests__/KnownDirectives-test.js
Labels: CLA Signed

#1456 Reuse 'many' for parsing document
  src/language/parser.js
Labels: CLA Signed

#1458 Fixup: add Experimental note to variable-directive tests
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/validation/__tests__/KnownDirectives-test.js
  src/validation/__tests__/harness.js
Labels: CLA Signed

#1457 Use invariants instead of throwing Errors
  src/utilities/buildASTSchema.js
Labels: CLA Signed

#1459 Add Node Predicates
  src/index.js
  src/language/index.js
  src/language/predicates.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
  src/validation/rules/ExecutableDefinitions.js
Labels: CLA Signed

#1460 import only GraphQLError instead of entire folder
  src/error/__tests__/locatedError-test.js
  src/execution/execute.js
  src/execution/values.js
  src/utilities/coerceValue.js
  src/validation/rules/ExecutableDefinitions.js
  src/validation/rules/FieldsOnCorrectType.js
  src/validation/rules/FragmentsOnCompositeTypes.js
  src/validation/rules/KnownArgumentNames.js
  src/validation/rules/KnownDirectives.js
  src/validation/rules/KnownFragmentNames.js
  src/validation/rules/KnownTypeNames.js
  src/validation/rules/LoneAnonymousOperation.js
  src/validation/rules/LoneSchemaDefinition.js
  src/validation/rules/NoFragmentCycles.js
  src/validation/rules/NoUndefinedVariables.js
  src/validation/rules/NoUnusedFragments.js
  src/validation/rules/NoUnusedVariables.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
  src/validation/rules/PossibleFragmentSpreads.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/rules/ScalarLeafs.js
  src/validation/rules/SingleFieldSubscriptions.js
  src/validation/rules/UniqueArgumentNames.js
  src/validation/rules/UniqueDirectivesPerLocation.js
  src/validation/rules/UniqueFragmentNames.js
  src/validation/rules/UniqueInputFieldNames.js
  src/validation/rules/UniqueOperationNames.js
  src/validation/rules/UniqueVariableNames.js
  src/validation/rules/ValuesOfCorrectType.js
  src/validation/rules/VariablesAreInputTypes.js
  src/validation/rules/VariablesInAllowedPosition.js
Labels: CLA Signed

#1462 Fix typo in AST predicates
  src/language/kinds.js
  src/language/predicates.js
Labels: CLA Signed

#1465 Add 'isRequredArgument' & 'isRequredInputField' predicates
  src/index.js
  src/type/definition.js
  src/type/index.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/rules/ValuesOfCorrectType.js
Labels: CLA Signed

#1477 Update deps
  package.json
  yarn.lock
Labels: CLA Signed

#1473 Remove unneeded "options" from package.json
  package.json
Labels: CLA Signed

#1470 Benchmark: replace shell scripts with JS code
  resources/benchmark.js
Labels: CLA Signed

#1482 Add missing deprecation comments
  src/utilities/extendSchema.js
  src/utilities/schemaPrinter.js
Labels: CLA Signed

#1483 Convert more object types to be exact
  src/__tests__/starWarsData.js
  src/execution/execute.js
  src/language/ast.js
  src/language/source.js
Labels: CLA Signed

#1485 Remove "--optional runtime" that was dropped in Babel v6
  package.json
  resources/benchmark.js
Labels: CLA Signed

#1486 Add unit tests for isRequired predicates
  src/type/__tests__/predicate-test.js
Labels: CLA Signed

#1490 Fix link and description of supported Markdown
  src/type/directives.js
  src/utilities/__tests__/schemaPrinter-test.js
Labels: CLA Signed

#1491 Fix formatting
  src/type/introspection.js
  src/utilities/__tests__/findBreakingChanges-test.js
  src/validation/__tests__/FieldsOnCorrectType-test.js
  src/validation/__tests__/KnownDirectives-test.js
  src/validation/rules/FieldsOnCorrectType.js
Labels: CLA Signed

#1493 Allow to add optional args to fields implemented from interfaces
  src/type/__tests__/validation-test.js
  src/type/validate.js
Labels: CLA Signed

#1494 Exclude __fixtures__ from dist
  package.json
Labels: CLA Signed

#1496 Correct error message about resolve specified on input fields
  src/type/__tests__/definition-test.js
  src/type/definition.js
Labels: CLA Signed
