Repository graphql/graphql-js, pull requests merged in 2018-06, with the labels that each got.

#1333 Errors: fix how error messages represent arrays
  src/execution/__tests__/abstract-test.js
  src/execution/execute.js
  src/execution/values.js
  src/jsutils/inspect.js
  src/language/parser.js
  src/subscription/subscribe.js
  src/type/definition.js
  src/type/scalars.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/astFromValue.js
  src/utilities/coerceValue.js
  src/validation/rules/FragmentsOnCompositeTypes.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
  src/validation/rules/PossibleFragmentSpreads.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/rules/ScalarLeafs.js
  src/validation/rules/ValuesOfCorrectType.js
  src/validation/rules/VariablesInAllowedPosition.js
Labels: CLA Signed

#1348 Babel 7 preparation: Switch babel config to JS
  .babelrc
  .babelrc.js
  package.json
  resources/common-js-modules.js
  yarn.lock
Labels: CLA Signed

#1362 Updated Flow, Prettier and other dependencies
  .flowconfig
  package.json
  yarn.lock
Labels: CLA Signed

#1336 Scalars: reject array serialization/coercion
  src/execution/__tests__/variables-test.js
  src/type/__tests__/serialization-test.js
  src/type/scalars.js
  src/utilities/__tests__/coerceValue-test.js
Labels: CLA Signed

#1350 Upgrade babel and associated plugins to v7
  .babelrc
  .babelrc.js
  package.json
  yarn.lock
Labels: CLA Signed, semver major

#1357 instanceOf: Check that one of the names in non-empty string
  src/jsutils/instanceOf.js
Labels: CLA Signed

#1297 Add support for Symbol.toStringTag
  src/jsutils/applyToStringTag.js
  src/language/source.js
  src/type/__tests__/toStringTag-test.js
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
Labels: CLA Signed

#1259 Use empty arrays instead of undefined properties
  src/type/schema.js
  src/type/validate.js
  src/utilities/extendSchema.js
Labels: CLA Signed

#1365 Reject Infinity supplied as Int or Float value
  src/jsutils/isInteger.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/serialization-test.js
  src/type/scalars.js
  src/utilities/__tests__/coerceValue-test.js
Labels: CLA Signed

#1267 [Bug Reproduce] Can't use undefined and NaN as enum values
  src/execution/__tests__/variables-test.js
  src/utilities/__tests__/valueFromAST-test.js
Labels: CLA Signed

#1369 Handle NaN as input value
  src/type/definition.js
  src/utilities/__tests__/coerceValue-test.js
  src/utilities/coerceValue.js
Labels: CLA Signed, semver major

#1370 Add simple test for `instanceOf`.
  src/jsutils/__tests__/instanceOf-test.js
Labels: CLA Signed

#1372 fix imports
  src/__tests__/starWarsIntrospection-test.js
  src/__tests__/starWarsQuery-test.js
  src/__tests__/starWarsSchema.js
  src/__tests__/starWarsValidation-test.js
Labels: CLA Signed

#1373 Merge extendType functionality changes from #1322
  src/type/definition.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
Labels: CLA Signed

#1374 Bump RC version to publish on npm
  package.json
Labels: CLA Signed

#1376 Allow interfaces to have no implementors
  src/type/__tests__/validation-test.js
  src/type/validate.js
Labels: CLA Signed, spec RFC

#1378 Json serialize types
  src/jsutils/defineToJSON.js
  src/jsutils/defineToStringTag.js
  src/language/source.js
  src/type/__tests__/definition-test.js
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
Labels: CLA Signed

#1381 Refactor NoFragmentCycles rule
  src/validation/rules/NoFragmentCycles.js
Labels: CLA Signed

#1386 Add deprecation notices with explicit removal versions
  src/index.js
  src/language/parser.js
  src/utilities/index.js
  src/utilities/introspectionQuery.js
  src/utilities/isValidJSValue.js
  src/utilities/isValidLiteralValue.js
Labels: CLA Signed

#1385 BREAKING: Remove deprecated introspection fields
  src/type/__tests__/introspection-test.js
  src/type/introspection.js
  src/utilities/__tests__/schemaPrinter-test.js
Labels: CLA Signed

#1382 BREAKING/BUGFIX Strict coercion of scalar types
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/variables-test.js
  src/jsutils/isFinite.js
  src/type/__tests__/serialization-test.js
  src/type/scalars.js
  src/utilities/__tests__/astFromValue-test.js
  src/utilities/__tests__/coerceValue-test.js
Labels: CLA Signed, semver major

#1390 Fix `extensionASTNodes` assigment
  src/type/definition.js
  src/utilities/__tests__/extendSchema-test.js
Labels: CLA Signed

#1392 Extend scalar
  src/type/definition.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/extendSchema.js
Labels: CLA Signed

#1391 Convert 'GraphQL*Config' to exact types
  src/type/definition.js
  src/type/introspection.js
  src/utilities/buildClientSchema.js
Labels: CLA Signed

#1397 Fix test name
  src/utilities/__tests__/coerceValue-test.js
Labels: CLA Signed

#1398 Fix extend schema test
  src/utilities/__tests__/extendSchema-test.js
Labels: CLA Signed

#1396 Mark more stuff as deprecated
  src/index.js
  src/type/schema.js
  src/utilities/buildASTSchema.js
  src/utilities/index.js
Labels: CLA Signed

#1402 Update Flow to 0.75 + other deps
  .flowconfig
  package.json
  src/jsutils/dedent.js
  yarn.lock
Labels: CLA Signed

#1400 Document the contextValue argument
  src/graphql.js
Labels: CLA Signed

#1409 Fix trailing space from #1400
  src/graphql.js
Labels: CLA Signed
