Repository graphql/graphql-js, pull requests merged in 2019-07, with the labels that each got.

#2008 Flow: Remove deprecated 'Function' type
  src/jsutils/defineToJSON.js
Labels: PR: polish 💅

#2011 Correctly add modified 'version.js' to release commit
  package.json
Labels: PR: internal 🏠

#1467 Make error handling consistent in createSourceEventStream
  src/subscription/__tests__/subscribe-test.js
  src/subscription/subscribe.js
Labels: CLA Signed, PR: bug fix 🐞

#2014 Fix build after #1467
  src/subscription/__tests__/subscribe-test.js
  src/subscription/subscribe.js
Labels: PR: polish 💅

#2013 Mark as private to prevent accidential publishing of root 'package.json'
  package.json
  resources/build.js
Labels: PR: internal 🏠

#2015 Flow: Remove some of the 'existential type' usages
  src/execution/execute.js
  src/execution/values.js
  src/jsutils/defineToStringTag.js
  src/language/lexer.js
  src/type/definition.js
  src/utilities/TypeInfo.js
  src/utilities/findBreakingChanges.js
  src/validation/ValidationContext.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
Labels: PR: polish 💅

#2016 Travis: Run gitdeploy only on pushes to master
  .travis.yml
Labels: PR: internal 🏠

#2019 Benchmark: Inline code from benchmark.js
  package.json
  resources/benchmark.js
  resources/colors.js
  yarn.lock
Labels: PR: internal 🏠

#2021 Benchmark: simplify code
  resources/benchmark.js
Labels: PR: internal 🏠

#2022 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2023 parser: simplify 'many' utility function
  src/language/parser.js
Labels: PR: polish 💅

#2024 parser: Remove unnecessary export on internal function
  src/language/parser.js
Labels: PR: polish 💅

#2025 Move 'getTokenDesc' into parser
  src/language/lexer.js
  src/language/parser.js
Labels: PR: polish 💅

#2026 Flow: Remove unussed '$FlowIssue'
  .flowconfig
Labels: PR: internal 🏠

#2027 Flow: Remove unnecessary type annotations
  src/language/parser.js
Labels: PR: polish 💅

#2028 Parser: group internal methods into a class to share lexer & options
  src/language/parser.js
Labels: PR: polish 💅

#2030 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2031 Remove use of existential type in validation tests
  src/type/__tests__/validation-test.js
Labels: PR: polish 💅

#2032 ESLint: Enable flowtype/no-existential-type rule
  .eslintrc.yml
  src/type/definition.js
Labels: PR: internal 🏠

#2033 Run prettier on all files in repo
  .babelrc.js
  .eslintrc.yml
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .nycflowrc.yml
  .nycrc.yml
  .travis.yml
  README.md
  docs/APIReference-GraphQL.md
  docs/APIReference-Language.md
  docs/APIReference-TypeSystem.md
  docs/APIReference-Utilities.md
  docs/Guides-ConstructingTypes.md
  docs/Tutorial-Authentication.md
  docs/Tutorial-BasicTypes.md
  docs/Tutorial-ExpressGraphQL.md
  docs/Tutorial-GettingStarted.md
  docs/Tutorial-GraphQLClients.md
  docs/Tutorial-Mutations.md
  docs/Tutorial-ObjectTypes.md
  docs/Tutorial-PassingArguments.md
  package.json
  src/README.md
  src/__fixtures__/github-schema.json
  src/error/README.md
  src/execution/README.md
  src/jsutils/README.md
  src/language/README.md
  src/polyfills/README.md
  src/subscription/README.md
  src/type/README.md
  src/utilities/README.md
  src/validation/README.md
  yarn.lock
Labels: PR: polish 💅

#2034 Cleanup leftovers of CI publishing
  .npmignore
  package.json
  resources/prepublish.sh
Labels: PR: internal 🏠

#2035 gen-changelog: remove hardcoded GitHub org and repo
  resources/gen-changelog.js
Labels: PR: internal 🏠

#2039 benchmark: improve reproducibility
  .eslintrc.yml
  package.json
  resources/benchmark-fork.js
  resources/benchmark.js
  src/language/__tests__/parser-benchmark.js
  src/utilities/__tests__/buildASTSchema-benchmark.js
  src/utilities/__tests__/buildClientSchema-benchmark.js
  src/utilities/__tests__/introspectionFromSchema-benchmark.js
  src/validation/__tests__/validateGQL-benchmark.js
  src/validation/__tests__/validateSDL-benchmark.js
Labels: PR: internal 🏠

#2040 Update Babel
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2042 Add tests for parseValue & parseLiteral of std scalars
  src/type/__tests__/scalars-test.js
Labels: PR: polish 💅

#2043 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2045 test: Fully cover 'coerceValue' function with tests
  src/utilities/__tests__/coerceValue-test.js
Labels: PR: polish 💅

#2046 Enable 'flowlint deprecated-type'
  .eslintrc.yml
  .flowconfig
  src/type/definition.js
Labels: PR: polish 💅

#2047 coerceValues: correctly handle NaN and similar values
  src/utilities/__tests__/coerceValue-test.js
  src/utilities/coerceValue.js
Labels: PR: bug fix 🐞

#2049 Remove useless check since args are always array (can be empty)
  src/execution/values.js
  src/type/schema.js
Labels: PR: polish 💅

#2050 Simplify coercion algorithm in getVariableValues/getArgumentValues
  src/execution/values.js
Labels: PR: polish 💅

#2051 Make getArgumentValues/getVariableValues algorithm linear
  src/execution/values.js
Labels: PR: polish 💅

#2052 coerceValue: Simplify path printing
  src/execution/__tests__/variables-test.js
  src/utilities/__tests__/coerceValue-test.js
  src/utilities/coerceValue.js
Labels: PR: polish 💅

#2053 jsutils: Add generic Path implementation
  src/execution/execute.js
  src/execution/index.js
  src/jsutils/Path.js
  src/subscription/subscribe.js
  src/type/definition.js
  src/type/index.js
  src/utilities/coerceValue.js
Labels: PR: polish 💅

#2054 buildExecutionContext: simplify errors handling
  src/execution/execute.js
Labels: PR: polish 💅

#2057 Update Flow to 0.104
  .flowconfig
  package.json
  src/polyfills/flatMap.js
  yarn.lock
Labels: PR: dependency 📦

#2058 flow: Enable 'uninitialized-instance-property' lint
  .flowconfig
  src/language/parser.js
  src/type/definition.js
  src/type/schema.js
Labels: PR: polish 💅

#2060 Using direct imports in test files
  src/__tests__/starWarsSchema.js
  src/error/__tests__/GraphQLError-test.js
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/directives-test.js
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/lists-test.js
  src/execution/__tests__/mutations-test.js
  src/execution/__tests__/nonnull-test.js
  src/execution/__tests__/resolve-test.js
  src/execution/__tests__/schema-test.js
  src/execution/__tests__/sync-test.js
  src/execution/__tests__/union-interface-test.js
  src/execution/__tests__/variables-test.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/printLocation-test.js
  src/language/__tests__/visitor-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/directive-test.js
  src/type/__tests__/enumType-test.js
  src/type/__tests__/introspection-test.js
  src/type/__tests__/predicate-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/serialization-test.js
  src/type/__tests__/validation-test.js
  src/utilities/__tests__/astFromValue-test.js
  src/utilities/__tests__/buildASTSchema-benchmark.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/concatAST-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/__tests__/findDeprecatedUsages-test.js
  src/utilities/__tests__/getOperationAST-test.js
  src/utilities/__tests__/getOperationRootType-test.js
  src/utilities/__tests__/introspectionFromSchema-benchmark.js
  src/utilities/__tests__/introspectionFromSchema-test.js
  src/utilities/__tests__/isValidLiteralValue-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/__tests__/separateOperations-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/utilities/__tests__/typeComparators-test.js
  src/utilities/__tests__/valueFromAST-test.js
  src/utilities/__tests__/valueFromASTUntyped-test.js
  src/validation/__tests__/KnownArgumentNames-test.js
  src/validation/__tests__/KnownDirectives-test.js
  src/validation/__tests__/KnownTypeNames-test.js
  src/validation/__tests__/LoneSchemaDefinition-test.js
  src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
  src/validation/__tests__/PossibleTypeExtensions-test.js
  src/validation/__tests__/ProvidedRequiredArguments-test.js
  src/validation/__tests__/UniqueDirectiveNames-test.js
  src/validation/__tests__/UniqueEnumValueNames-test.js
  src/validation/__tests__/UniqueFieldDefinitionNames-test.js
  src/validation/__tests__/UniqueOperationTypes-test.js
  src/validation/__tests__/UniqueTypeNames-test.js
  src/validation/__tests__/harness.js
  src/validation/__tests__/validateGQL-benchmark.js
  src/validation/__tests__/validateSDL-benchmark.js
  src/validation/__tests__/validation-test.js
Labels: PR: polish 💅

#2061 change 'CoercedVariableValues' to disjoint union
  src/execution/execute.js
  src/execution/values.js
Labels: PR: polish 💅

#2063 Remove useless invariant since 'serialize' is always exist
  src/execution/execute.js
Labels: PR: polish 💅

#2064 invariant: improve code that babel outputs
  resources/inline-invariant.js
  src/jsutils/invariant.js
Labels: PR: polish 💅

#2065 Remove 'invariant' calls from 'stripIgnoredCharacters' tests
  src/utilities/__tests__/stripIgnoredCharacters-test.js
Labels: PR: polish 💅

#2066 Use 'invariant' only for real invariants, add 'devAssert' for the rest
  .flowconfig
  resources/inline-invariant.js
  src/error/formatError.js
  src/execution/execute.js
  src/jsutils/devAssert.js
  src/language/parser.js
  src/language/source.js
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
  src/utilities/assertValidName.js
  src/utilities/buildASTSchema.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  src/validation/validate.js
Labels: PR: polish 💅

#2067 Convert all non-reachable exceptions into invariants
  resources/inline-invariant.js
  src/execution/execute.js
  src/type/introspection.js
  src/utilities/astFromValue.js
  src/utilities/buildASTSchema.js
  src/utilities/coerceValue.js
  src/utilities/extendSchema.js
  src/utilities/findBreakingChanges.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/schemaPrinter.js
  src/utilities/typeFromAST.js
  src/utilities/valueFromAST.js
  src/utilities/valueFromASTUntyped.js
Labels: PR: polish 💅

#2068 parser: Extract 'optionalMany' utility function
  src/language/parser.js
Labels: PR: polish 💅
