Repository graphql/graphql-js, pull requests merged in 2019-12, with the labels that each got.

#2274 Resolve import cycle by moving 'visitWithTypeInfo' into 'TypeInfo.js'
  src/index.d.ts
  src/index.js
  src/language/__tests__/visitor-test.js
  src/language/ast.d.ts
  src/language/ast.js
  src/language/index.d.ts
  src/language/index.js
  src/language/visitor.d.ts
  src/language/visitor.js
  src/utilities/TypeInfo.d.ts
  src/utilities/TypeInfo.js
  src/utilities/__tests__/TypeInfo-test.js
  src/utilities/findDeprecatedUsages.js
  src/utilities/index.d.ts
  src/utilities/index.js
  src/validation/ValidationContext.js
  src/validation/validate.js
Labels: PR: breaking change 💥

#2279 Update TravisCi to run full CI suite on Node 12
  .travis.yml
Labels: PR: internal 🏠

#2283 Update deps
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2286 Remove duplicate colon in coercion error message
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/coerceInputValue.js
Labels: PR: bug fix 🐞

#2285 Remove forgotten internal error message functions (#2159)
  src/type/__tests__/introspection-test.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/rules/ScalarLeafs.js
  src/validation/rules/UniqueArgumentNames.js
  src/validation/rules/UniqueDirectiveNames.js
Labels: PR: polish 💅

#2284 Replace all instances of Flow existential type
  .flowconfig
  src/type/definition.js
Labels: PR: breaking change 💥

#2287 tests: Fix style of graphql queries inside string literals
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/mutations-test.js
  src/execution/__tests__/variables-test.js
Labels: PR: polish 💅

#2288 tests: Switch to using named arguments to graphql/execute
  src/__tests__/starWarsQuery-test.js
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/lists-test.js
  src/execution/__tests__/mutations-test.js
  src/execution/__tests__/nonnull-test.js
  src/execution/__tests__/resolve-test.js
  src/execution/__tests__/schema-test.js
  src/execution/__tests__/union-interface-test.js
  src/subscription/subscribe.js
  src/type/__tests__/introspection-test.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/introspectionFromSchema-benchmark.js
  src/utilities/introspectionFromSchema.js
Labels: PR: polish 💅

#2289 Update Flow to 0.114.0
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2290 Drop Support for Node 8
  .travis.yml
  package.json
Labels: PR: breaking change 💥

#2291 Add node v13 to CI
  .travis.yml
Labels: PR: internal 🏠

#2293 benchmark: extract 'bold' func for applying ANSI bold code
  resources/benchmark.js
Labels: PR: internal 🏠

#2294 benchmark: make clean build every time
  resources/benchmark.js
Labels: PR: internal 🏠

#2295 Correct bunch of spelling mistakes
  resources/benchmark.js
  resources/build.js
  resources/check-cover.js
  resources/check-cycles.js
  resources/gen-changelog.js
  src/__tests__/starWarsData.js
  src/__tests__/starWarsQuery-test.js
  src/__tests__/starWarsSchema.js
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/schema-test.js
  src/execution/__tests__/variables-test.js
  src/execution/execute.d.ts
  src/jsutils/__tests__/dedent-test.js
  src/jsutils/__tests__/inspect-test.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/printLocation-test.js
  src/language/blockString.d.ts
  src/language/lexer.d.ts
  src/language/lexer.js
  src/language/printLocation.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/mapAsyncIterator.d.ts
  src/type/__tests__/definition-test.js
  src/type/__tests__/introspection-test.js
  src/type/__tests__/validation-test.js
  src/utilities/TypeInfo.d.ts
  src/utilities/TypeInfo.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/concatAST-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/utilities/buildClientSchema.js
  src/validation/__tests__/KnownArgumentNames-test.js
  src/validation/__tests__/KnownTypeNames-test.js
  src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
  src/validation/__tests__/ScalarLeafs-test.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
Labels: PR: polish 💅

#2296 More fixes to make spellchecker happy
  README.md
  src/language/printLocation.js
  src/type/schema.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/extendSchema.js
  src/validation/__tests__/KnownArgumentNames-test.js
  src/validation/__tests__/ProvidedRequiredArguments-test.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
  src/validation/__tests__/harness.js
  src/validation/__tests__/validation-test.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
Labels: PR: polish 💅

#2297 Add spellchecker
  README.md
  cspell.json
  package.json
  yarn.lock
Labels: PR: internal 🏠

#2300 tests: Switch to using named arguments for `subscribe` calls
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#2302 tests: simplify 'astNode' and 'extensionASTNodes' tests
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅

#2305 Small optimization in the schema type map reducer
  src/type/schema.js
Labels: PR: polish 💅

#2306 Remove unmatched opening parenthesis in description
  src/type/directives.js
  src/utilities/__tests__/schemaPrinter-test.js
Labels: PR: bug fix 🐞

#2307 Add dots at the end of error messages
  src/execution/__tests__/executor-test.js
  src/execution/execute.js
  src/jsutils/invariant.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/parser.js
  src/language/source.js
  src/language/visitor.js
  src/subscription/__tests__/subscribe-test.js
  src/subscription/subscribe.js
  src/type/__tests__/definition-test.js
  src/type/definition.js
  src/utilities/__tests__/assertValidName-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/utilities/assertValidName.js
  src/utilities/astFromValue.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
  src/utilities/stripIgnoredCharacters.js
  src/validation/validate.js
Labels: PR: bug fix 🐞

#2308 extendedSchema-test: make tests self contained
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅

#2309 extendSchema: remove dead check on number of directives
  src/utilities/extendSchema.js
Labels: PR: polish 💅

#2310 buildSchema/extendSchema: improve test coverage
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/extendSchema.js
Labels: PR: polish 💅

#2248 buildSchema/extendSchema: add support for extensions
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
Labels: PR: feature 🚀

#2311 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2312 Mark 'config' as readonly argument to contructors
  src/type/definition.d.ts
  src/type/definition.js
  src/type/directives.d.ts
  src/type/directives.js
  src/type/schema.d.ts
  src/type/schema.js
Labels: PR: polish 💅

#2314 gen-changelog: Fix error handling and improve error messages
  resources/gen-changelog.js
Labels: PR: internal 🏠

#2315 Add 'yarn check --integrity' to 'preversion' script
  package.json
Labels: PR: internal 🏠
