Repository graphql/graphql-js, pull requests merged in 2019-05, with the labels that each got.

#1840 ESLint: enable 'arrow-body-style' rule
  .eslintrc.yml
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#1841 Make single 'build.js' to handle NPM package build
  .babelrc.js
  package.json
  resources/build.js
  resources/copy-package-json.js
  resources/fs-utils.js
  yarn.lock
Labels: PR: internal 🏠

#1842 Terminate shell scripts if any subcomand terminated
  resources/checkgit.sh
  resources/gitpublish.sh
  resources/prepublish.sh
Labels: PR: internal 🏠

#1843 Fix "npm run build" on Node 10
  resources/fs-utils.js
Labels: PR: internal 🏠

#1844 Correctly trap errors in shell scripts
  resources/checkgit.sh
  resources/gitpublish.sh
  resources/prepublish.sh
Labels: PR: internal 🏠

#1845 Adapt benchmark to the new build script
  .gitignore
  resources/benchmark.js
Labels: PR: internal 🏠

#1837 isSpecifiedDirective should not assume Directive type
  src/type/__tests__/predicate-test.js
  src/type/directives.js
  src/type/scalars.js
Labels: PR: bug fix 🐞

#1848 Remove Flow workaround for const arguments
  src/type/directives.js
  src/type/introspection.js
  src/type/scalars.js
Labels: PR: polish 💅

#1849 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1850 Add comment to make test better understandable
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅

#1851 nyc: Switch config from JSON to YAML and move args from package.json
  .nycrc
  .nycrc.yml
  package.json
Labels: PR: internal 🏠

#1855 Add 'yarn check --integrity' to CI tests
  package.json
Labels: PR: internal 🏠

#1856 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1861 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1862 Update 'eslint-plugin-flowtype'
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1863 Fix some typos in stripIgnoredCharacters docs+tests
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/utilities/stripIgnoredCharacters.js
Labels: PR: polish 💅

#1864 Drop parser option since Prettier supports Flow by default
  .prettierrc
Labels: PR: internal 🏠

#1865 Enable Flow on "subscribe-test.js"
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#1866 Enable Flow in "visitor-test.js"
  src/language/__tests__/visitor-test.js
Labels: PR: polish 💅

#1867 ESLint: Simplify exclude for "no-restricted-syntax" rule
  .eslintrc.yml
Labels: PR: internal 🏠

#1868 Add missing "@noflow"
  resources/watch.js
Labels: PR: polish 💅

#1869 ESLint: remove useless "parserOptions" options
  .eslintrc.yml
Labels: PR: internal 🏠

#1870 Add missing "use strict"
  resources/watch.js
Labels: PR: internal 🏠

#1871 Lint JS files inside "resources" folder
  .eslintrc.yml
  package.json
Labels: PR: internal 🏠

#1872 Replace all "var" with "const" & "let" in "resources/*.js" files
  .eslintrc.yml
  resources/inline-invariant.js
  resources/watch.js
Labels: PR: internal 🏠

#1873 Fix lint issues in 'resources/*.js' files
  .eslintrc.yml
  resources/benchmark.js
  resources/build.js
  resources/fs-utils.js
  resources/inline-invariant.js
  resources/watch.js
Labels: PR: internal 🏠

#1874 Enable "no-inner-declarations" rule on "resources/*.js" files
  .eslintrc.yml
  resources/benchmark.js
Labels: PR: internal 🏠

#1876 inline-invariant: use template instead of AST
  resources/inline-invariant.js
Labels: PR: internal 🏠

#1875 Enable prettier for "resources/*.js" files
  .eslintrc.yml
  package.json
  resources/benchmark.js
  resources/fs-utils.js
  resources/watch.js
Labels: PR: internal 🏠

#1877 Rename 'fs-utils.js' to 'utils.js'
  resources/benchmark.js
  resources/build.js
  resources/utils.js
Labels: PR: internal 🏠

#1879 Use "isPromise" instead of testing for 'then' property
  src/graphql.js
  src/utilities/introspectionFromSchema.js
Labels: PR: polish 💅

#1880 Enable "sketchy-null-mixed" Flow check
  .flowconfig
  src/error/GraphQLError.js
  src/jsutils/inspect.js
  src/jsutils/invariant.js
  src/language/__tests__/toJSONDeep.js
  src/language/__tests__/visitor-test.js
Labels: PR: polish 💅

#1881 Partly fix results of "sketchy-null-mixed" Flow check
  src/execution/values.js
  src/language/blockString.js
  src/validation/rules/VariablesInAllowedPosition.js
Labels: PR: polish 💅

#1882 Enable 'prefer-promise-reject-errors' ESLint rule
  .eslintrc.yml
  src/execution/__tests__/executor-test.js
Labels: PR: polish 💅

#1883 Enable "no-sequences" ESLint rule
  .eslintrc.yml
  src/jsutils/keyMap.js
  src/jsutils/keyValMap.js
  src/type/schema.js
Labels: PR: polish 💅

#1884 memoize3: Explicitly pass arguments
  src/jsutils/memoize3.js
Labels: PR: polish 💅

#1885 Explicitly create Promise using "Promise.resolve"
  src/execution/__tests__/sync-test.js
Labels: PR: polish 💅

#1886 Remove TODO on "no-warning-comments" ESLint rule
  .eslintrc.yml
Labels: PR: internal 🏠

#1887 Enable "no-case-declarations" ESLint rule
  .eslintrc.yml
  src/execution/execute.js
  src/language/lexer.js
  src/utilities/TypeInfo.js
  src/utilities/getOperationRootType.js
  src/utilities/valueFromASTUntyped.js
  src/validation/rules/KnownDirectives.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
Labels: PR: polish 💅

#1888 Enable 'no-prototype-builtins' ESLint rule
  .eslintrc.yml
  src/execution/__tests__/variables-test.js
  src/language/parser.js
  src/type/definition.js
Labels: PR: polish 💅

#1891 findBreakingChanges-test: remove unneeded 'Query' types
  src/utilities/__tests__/findBreakingChanges-test.js
Labels: PR: polish 💅

#1892 build: Add new lines to "*.js" and "*.mjs" files
  resources/build.js
Labels: PR: internal 🏠

#1893 findBreakingChanges: test only functions that are part of public API
  src/utilities/__tests__/findBreakingChanges-test.js
Labels: PR: polish 💅

#1895 findBreakingChanges: Remove 'export' from internal functions
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1896 findBreakingChanges: Correctly document not reachable statement
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1897 findBreakingChanges-test: Remove unnecessary fields
  src/utilities/__tests__/findBreakingChanges-test.js
Labels: PR: polish 💅

#1898 findBreakingChanges: simplify checking of wrapped types
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1809 buildClientSchema: include standard type only if it is used
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/buildClientSchema.js
Labels: PR: bug fix 🐞

#1899 findBreakingChanges: Add new tests to improve coverage
  src/utilities/__tests__/findBreakingChanges-test.js
Labels: PR: polish 💅

#1900 Update babel to v7.4.5
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1901 findBreakingChanges: extract 'findByName' utility function
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1902 findBreakingChanges: Simplify type to string conversion
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1903 findBreakingChanges: add missing dots to descriptions
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1904 findBreakingChanges-test: Unify changes snapshots
  src/utilities/__tests__/findBreakingChanges-test.js
Labels: PR: polish 💅

#1905 findBreakingChanges: simplify schema iteration
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1906 Use 'Object.freeze' consistently on all exported Array/Object constants
  src/language/visitor.js
  src/type/directives.js
  src/type/introspection.js
  src/type/scalars.js
  src/utilities/findBreakingChanges.js
  src/validation/specifiedRules.js
Labels: PR: feature 🚀

#1907 findBreakingChanges: unify how changes are collected
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1908 findBreakingChanges: extract "diff" utility function
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1909 findBreakingChanges: reduce duplication by merging some functions
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1910 Replace some "for" cycles with "for of"
  src/jsutils/suggestionList.js
  src/utilities/astFromValue.js
  src/utilities/getOperationAST.js
  src/utilities/schemaPrinter.js
  src/utilities/valueFromAST.js
  src/validation/ValidationContext.js
  src/validation/rules/NoFragmentCycles.js
Labels: PR: polish 💅

#1911 findBreakingChanges: merge funcs and remove duplicated iteration logic
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1912 findBreakingChanges: sort functions in logical order
  src/utilities/findBreakingChanges.js
Labels: PR: polish 💅

#1914 ESLint: Forbid unnecessary backticks
  .eslintrc.yml
  src/type/__tests__/serialization-test.js
  src/type/__tests__/validation-test.js
  src/type/validate.js
  src/utilities/__tests__/coerceValue-test.js
Labels: PR: polish 💅

#1915 Travis: don't duplicate testing on Node's latest LTS
  .travis.yml
Labels: PR: internal 🏠

#1878 Add "version" string and parsed "versionInfo"
  package.json
  resources/build.js
  resources/gen-version.js
  resources/utils.js
  src/__tests__/version-test.js
  src/index.js
  src/version.js
Labels: PR: feature 🚀

#1916 findBreakingChanges: use string representation to compare default values
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/findBreakingChanges.js
Labels: PR: bug fix 🐞

#1917 Manually update 'version.js'
  package.json
  resources/build.js
  src/version.js
Labels: PR: internal 🏠

#1918 tests: replace 'printNode' with more high-level 'printASTNode'
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅

#1919 Update GitHub schema
  src/__fixtures__/github-schema.graphql
  src/__fixtures__/github-schema.json
Labels: PR: internal 🏠

#1920 Remove trailing spaces from 'Int' and 'Float' descriptions
  src/type/scalars.js
Labels: PR: bug fix 🐞

#1921 Manually concat all static strings
  src/execution/__tests__/abstract-test.js
  src/execution/execute.js
  src/language/__tests__/lexer-test.js
  src/language/lexer.js
  src/type/__tests__/introspection-test.js
  src/type/definition.js
  src/type/directives.js
  src/type/introspection.js
  src/type/scalars.js
  src/utilities/buildClientSchema.js
Labels: PR: polish 💅

#1923 Copy 'site/graphql-js' folder from 'graphql.github.io' repo
  docs/APIReference-Errors.md
  docs/APIReference-Execution.md
  docs/APIReference-ExpressGraphQL.md
  docs/APIReference-GraphQL.md
  docs/APIReference-Language.md
  docs/APIReference-TypeSystem.md
  docs/APIReference-Utilities.md
  docs/APIReference-Validation.md
  docs/Guides-ConstructingTypes.md
  docs/Tutorial-Authentication.md
  docs/Tutorial-BasicTypes.md
  docs/Tutorial-ExpressGraphQL.md
  docs/Tutorial-GettingStarted.md
  docs/Tutorial-GraphQLClients.md
  docs/Tutorial-Mutations.md
  docs/Tutorial-ObjectTypes.md
  docs/Tutorial-PassingArguments.md
Labels: PR: docs 📝

#1924 Add 'docs' to .npmignore
  .npmignore
Labels: PR: internal 🏠

#1926 Update deps
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1927 validation-tests: remove useless parseValue & parseLiteral
  src/validation/__tests__/harness.js
Labels: PR: polish 💅

#1928 package.json: Rename "check-cover" to "check:cover"
  package.json
Labels: PR: internal 🏠

#1929 benchmark: create 'exec' wrap for execSync function
  resources/benchmark.js
  resources/utils.js
Labels: PR: internal 🏠

#1931 npmignore: remove all dot files since they already covered by '.*'
  .npmignore
Labels: PR: internal 🏠

#1933 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1934 Add typings to introspection resolvers
  src/type/introspection.js
Labels: PR: polish 💅
