Repository graphql/graphql-js, pull requests merged in 2019-01, with the labels that each got.

#1638 Update deps
  package.json
  yarn.lock
Labels: CLA Signed

#1641 Correctly handle custom inspect fn that returns object value
  src/jsutils/__tests__/inspect-test.js
  src/jsutils/inspect.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
Labels: CLA Signed

#1645 Update ESLint
  .eslintrc.yml
  package.json
  yarn.lock
Labels: CLA Signed

#1646 Remove unnecessary use of hasOwnProperty
  src/language/__tests__/toJSONDeep.js
  src/language/visitor.js
  src/utilities/coerceValue.js
Labels: CLA Signed

#1647 Add analog of 'Object.entries' to simplify and speedup iteration
  src/jsutils/objectEntries.js
  src/type/definition.js
  src/type/directives.js
  src/type/validate.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
Labels: CLA Signed

#1648 Use custom polyfill for 'Array.find'
  src/utilities/findBreakingChanges.js
Labels: CLA Signed

#1649 Convert a few cycles to use objectValues
  src/type/schema.js
  src/validation/rules/ValuesOfCorrectType.js
Labels: CLA Signed

#1650 Simplify args definition
  src/type/definition.js
  src/type/directives.js
Labels: CLA Signed

#1651 Added 'jsutils/mapValue'
  src/jsutils/mapValue.js
  src/type/definition.js
  src/utilities/extendSchema.js
Labels: CLA Signed

#1652 Switch schema validation tests to Flow
  src/type/__tests__/validation-test.js
Labels: CLA Signed

#1653 Update deps
  package.json
  yarn.lock
Labels: CLA Signed

#1654 Enable Flow on definition tests
  src/type/__tests__/definition-test.js
Labels: CLA Signed

#1655 Use 'Array.prototype.find' if available
  src/jsutils/find.js
Labels: CLA Signed

#1656 Move polyfills into separate dir and exclude them from coverage
  .nycrc
  src/execution/values.js
  src/jsutils/mapValue.js
  src/polyfills/README.md
  src/polyfills/find.js
  src/polyfills/isFinite.js
  src/polyfills/isInteger.js
  src/polyfills/objectEntries.js
  src/polyfills/objectValues.js
  src/type/definition.js
  src/type/directives.js
  src/type/introspection.js
  src/type/scalars.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/TypeInfo.js
  src/utilities/astFromValue.js
  src/utilities/buildASTSchema.js
  src/utilities/coerceValue.js
  src/utilities/extendSchema.js
  src/utilities/findBreakingChanges.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/schemaPrinter.js
  src/utilities/valueFromAST.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
  src/validation/rules/ValuesOfCorrectType.js
Labels: CLA Signed

#1658 Remove excessive invariants
  src/error/__tests__/printError-test.js
  src/utilities/__tests__/getOperationRootType-test.js
Labels: CLA Signed

#1660 Update Flow to 0.90.0
  .flowconfig
  package.json
  src/jsutils/inspect.js
  src/language/__tests__/toJSONDeep.js
  src/type/definition.js
  src/type/scalars.js
  yarn.lock
Labels: CLA Signed

#1661 Move isInputType & isOutputType test to rest of predicates test
  src/type/__tests__/definition-test.js
  src/type/__tests__/predicate-test.js
Labels: CLA Signed

#1662 Add tests for GraphQLDirective
  src/type/__tests__/directive-test.js
  src/type/directives.js
Labels: CLA Signed

#1663 Merge schema validation tests with other schema tests
  src/type/__tests__/definition-test.js
  src/type/__tests__/schema-test.js
Labels: CLA Signed

#1664 Move $DisableFlowOnNegativeTest to more precise locations
  src/type/__tests__/definition-test.js
  src/type/__tests__/directive-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
Labels: CLA Signed

#1665 Enable Flow on buildClientSchema tests
  src/utilities/__tests__/buildClientSchema-test.js
Labels: CLA Signed

#1610 add type name to information
  src/utilities/buildClientSchema.js
Labels: CLA Signed

#1669 Remove usage of Flow placeholder argument + cleanup
  src/utilities/buildASTSchema.js
Labels: CLA Signed

#1667 Update travis api_key for npm deploys
  .travis.yml
Labels: CLA Signed

#1547 Parser: Better names for parser util functions
  src/language/parser.js
Labels: CLA Signed

#1671 Update Flow to 0.91.0
  .flowconfig
  package.json
  yarn.lock
Labels: CLA Signed, PR: Dependency 📦

#1672 Remove useless if inside 'getAllSubNodes' function
  src/type/validate.js
Labels: PR: polish 💅

#1600 Inspect non-error types to produce helpful error messages for failing resolvers
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/executor-test.js
  src/execution/execute.js
Labels: CLA Signed, PR: bug fix 🐞

#1677 Remove excessive cache inside buildClientSchema
  src/utilities/buildClientSchema.js
Labels: CLA Signed, PR: polish 💅

#1678 buildClientSchema: move inner functions to follow return
  src/utilities/buildClientSchema.js
Labels: CLA Signed, PR: polish 💅

#1681 Remove excessive cache inside lexicographicSortSchema
  src/utilities/lexicographicSortSchema.js
Labels: PR: polish 💅

#1684 extract flatMap function out of extendSchema implementation
  src/utilities/extendSchema.js
Labels: PR: polish 💅

#1685 Update deps
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1688 Fix codecov in yarn.lock
  yarn.lock
Labels: CLA Signed

#1686 Add polyfill for 'flatMap'
  src/polyfills/flatMap.js
  src/type/validate.js
  src/utilities/concatAST.js
  src/utilities/extendSchema.js
  src/utilities/schemaPrinter.js
Labels: CLA Signed, PR: polish 💅

#1689 Improve code coverage reporting
  .gitignore
  README.md
  codecov.yml
  package.json
Labels: CLA Signed

#1673 Disable coverage on deprecated 'isValidJSValue' function
  src/utilities/isValidJSValue.js
Labels: CLA Signed, PR: polish 💅

#1692 Run full CI only on node LTS
  .travis.yml
Labels: CLA Signed, PR: Internal 🏠

#1693 Move coverage upload to .travis.yml
  .travis.yml
  package.json
  yarn.lock
Labels: CLA Signed, PR: Internal 🏠

#1695 Remove excessive cache inside buildSchema and extendSchema
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
Labels: PR: polish 💅

#1696 Improve coverage for lexicographicSortSchema
  src/utilities/__tests__/lexicographicSortSchema-test.js
  src/utilities/lexicographicSortSchema.js
Labels: CLA Signed

#1697 Remove Flow workaround in buildASTSchema
  src/utilities/buildASTSchema.js
Labels: PR: polish 💅

#1698 Fix missing schema's astNode when schema was defined inside extension
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/extendSchema.js
Labels: CLA Signed, PR: bug fix 🐞

#1699 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1700 Update Flow and other deps
  .flowconfig
  package.json
  src/jsutils/__tests__/dedent-test.js
  yarn.lock
Labels: CLA Signed, PR: dependency 📦
