Repository graphql/graphql-js, pull requests merged in 2019-06, with the labels that each got.

#1935 Update Flow to v0.100.0
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1936 Remove dead code since args are always present on fields and directives
  src/type/introspection.js
Labels: PR: polish 💅

#1937 Accept normal object as 'variableValues' arg of 'graphql' function
  src/graphql.js
Labels: PR: bug fix 🐞

#1938 Allow null value on 'data' property of 'ExecutionResult' type
  src/execution/execute.js
Labels: PR: bug fix 🐞

#1939 Accept normal object as 'variableValues' arg of subscribe functions
  src/subscription/subscribe.js
Labels: PR: bug fix 🐞

#1940 Allow 'async/await' in 'resources' scripts
  .eslintrc.yml
Labels: PR: internal 🏠

#1941 Speed up "check:cover" by using async exec
  resources/check-cover.js
  resources/utils.js
Labels: PR: internal 🏠

#1942 Export "SubscriptionArgs" type
  src/index.js
  src/subscription/index.js
  src/subscription/subscribe.js
Labels: PR: feature 🚀

#1943 Simplify args handling in 'graphql', 'subscribe' and 'execute' funcs
  src/execution/execute.js
  src/graphql.js
  src/subscription/subscribe.js
Labels: PR: polish 💅

#1944 Extract "didYouMean" util function
  src/execution/__tests__/variables-test.js
  src/jsutils/__tests__/didYouMean-test.js
  src/jsutils/__tests__/quotedOrList-test.js
  src/jsutils/didYouMean.js
  src/jsutils/orList.js
  src/jsutils/quotedOrList.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/enumType-test.js
  src/utilities/__tests__/coerceValue-test.js
  src/utilities/coerceValue.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
  src/validation/rules/FieldsOnCorrectType.js
  src/validation/rules/KnownArgumentNames.js
  src/validation/rules/KnownTypeNames.js
  src/validation/rules/PossibleTypeExtensions.js
  src/validation/rules/ScalarLeafs.js
  src/validation/rules/ValuesOfCorrectType.js
Labels: PR: polish 💅

#1945 Extract 'identityFunc' function to be used instead of 'x => x'
  src/jsutils/__tests__/identityFunc-test.js
  src/jsutils/identityFunc.js
  src/type/__tests__/definition-test.js
  src/type/definition.js
  src/utilities/buildASTSchema.js
  src/utilities/buildClientSchema.js
Labels: PR: polish 💅

#1946 GraphQLScalarType: make 'serialize' optional with 'identityFunc' as default
  src/type/__tests__/definition-test.js
  src/type/__tests__/predicate-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
  src/type/definition.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/buildASTSchema.js
  src/utilities/buildClientSchema.js
  src/validation/__tests__/harness.js
Labels: PR: feature 🚀

#1359 validateSchema: validate Input Objects self-references
  src/type/__tests__/validation-test.js
  src/type/validate.js
Labels: CLA Signed, PR: feature 🚀, spec RFC

#1947 Remove 'watch' script
  package.json
  resources/watch.js
  yarn.lock
Labels: PR: internal 🏠

#1949 [printError] Make location formatting IDE friendly
  src/error/__tests__/printError-test.js
  src/error/printError.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
Labels: PR: feature 🚀

#1950 validateSchema: use 'astNode' from fields/args instead of type's subnodes
  src/type/validate.js
Labels: PR: polish 💅

#1952 tests: replace `invariant` with `assertEnumType`
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: polish 💅

#1953 Remove "coverage/flow" before every "check:cover" run.
  resources/check-cover.js
Labels: PR: internal 🏠

#1955 Make 'parseLiteral' optional and use wrapped 'parseValue' by default
  src/type/__tests__/definition-test.js
  src/type/definition.js
  src/validation/__tests__/harness.js
Labels: PR: feature 🚀

#1956 Update prettier to v1.18.0
  package.json
  src/execution/execute.js
  src/jsutils/instanceOf.js
  src/utilities/findBreakingChanges.js
  yarn.lock
Labels: PR: dependency 📦

#1957 Remove unnecessary concatenations from template strings
  src/execution/execute.js
  src/execution/values.js
  src/language/lexer.js
  src/type/definition.js
  src/type/validate.js
  src/utilities/assertValidName.js
  src/utilities/buildClientSchema.js
  src/utilities/findBreakingChanges.js
  src/validation/rules/FragmentsOnCompositeTypes.js
  src/validation/rules/PossibleFragmentSpreads.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/rules/ScalarLeafs.js
  src/validation/rules/SingleFieldSubscriptions.js
  src/validation/rules/UniqueDirectiveNames.js
  src/validation/rules/UniqueDirectivesPerLocation.js
  src/validation/rules/UniqueEnumValueNames.js
  src/validation/rules/UniqueFieldDefinitionNames.js
  src/validation/rules/UniqueOperationTypes.js
  src/validation/rules/UniqueTypeNames.js
  src/validation/rules/ValuesOfCorrectType.js
  src/validation/rules/VariablesInAllowedPosition.js
Labels: PR: polish 💅

#1959 Fix URLs to the GraphQL Specification and its repository
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  README.md
Labels: PR: docs 📝

#1961 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1962 parser: remove unused token that was returned from keyword match
  src/language/parser.js
Labels: PR: polish 💅

#1963 buildASTSchema-test: inline SDL in 'buildSchema' calls
  src/utilities/__tests__/buildASTSchema-test.js
Labels: PR: polish 💅

#1964 Simplify SDLs used in 'buidSchema'/`extendSchema' tests
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅

#1965 Added partial support for repeatable directives
  src/__fixtures__/schema-kitchen-sink.graphql
  src/language/__tests__/schema-parser-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/ast.js
  src/language/parser.js
  src/language/printer.js
  src/type/__tests__/directive-test.js
  src/type/directives.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/buildASTSchema.js
  src/utilities/schemaPrinter.js
  src/validation/__tests__/UniqueDirectivesPerLocation-test.js
  src/validation/rules/UniqueDirectivesPerLocation.js
Labels: PR: feature 🚀, spec RFC

#1966 Add script to generate changelog
  resources/gen-changelog.js
Labels: PR: internal 🏠

#1968 Add some stats to the 'yarn build' command
  resources/build.js
Labels: PR: internal 🏠

#1969 Improve generated changelog
  package.json
  resources/gen-changelog.js
Labels: PR: internal 🏠

#1971 Update deps
  .eslintrc.yml
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1972 inspect: Handle 'null' explicitly
  src/jsutils/inspect.js
Labels: PR: polish 💅

#1973 Extract 'isObjectLike' utility function
  src/error/GraphQLError.js
  src/execution/execute.js
  src/jsutils/__tests__/isObjectLike-test.js
  src/jsutils/isObjectLike.js
  src/language/__tests__/toJSONDeep.js
  src/type/definition.js
  src/type/directives.js
  src/type/scalars.js
  src/type/schema.js
  src/utilities/astFromValue.js
  src/utilities/coerceValue.js
Labels: PR: polish 💅

#1974 buildClientSchema: add dev check for invalid introspection argument
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/buildClientSchema.js
Labels: PR: polish 💅

#1975 inspect-test: Improve coverage
  src/jsutils/__tests__/inspect-test.js
Labels: PR: polish 💅

#1976 inspect-test: remove $FlowFixMe
  src/jsutils/__tests__/inspect-test.js
Labels: PR: polish 💅

#1977 buildClientSchema: improve coverage
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: polish 💅

#1978 Flow: switch to new '...' syntax for inexact objects
  .flowconfig
  src/__tests__/starWarsData.js
  src/error/GraphQLError.js
  src/error/formatError.js
  src/execution/execute.js
  src/execution/values.js
  src/graphql.js
  src/jsutils/ObjMap.js
  src/language/ast.js
  src/language/lexer.js
  src/language/parser.js
  src/subscription/subscribe.js
  src/type/definition.js
  src/type/validate.js
  src/utilities/buildASTSchema.js
  src/utilities/findBreakingChanges.js
  src/utilities/introspectionQuery.js
  src/utilities/lexicographicSortSchema.js
Labels: PR: polish 💅

#1980 Correct imports to use direct paths instead of relying on 'index.js'
  src/language/lexer.js
  src/language/parser.js
  src/validation/ValidationContext.js
  src/validation/validate.js
Labels: PR: polish 💅

#1981 Move TokenKind into separate file to solve cycle import
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/language/ast.js
  src/language/index.js
  src/language/lexer.js
  src/language/parser.js
  src/language/tokenKind.js
  src/utilities/buildASTSchema.js
  src/utilities/stripIgnoredCharacters.js
Labels: PR: polish 💅

#1982 printError: improve coverage
  src/error/__tests__/printError-test.js
Labels: PR: polish 💅

#1983 printError shouldn't return trailing new line
  src/error/__tests__/printError-test.js
  src/error/printError.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
Labels: PR: bug fix 🐞

#1990 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1991 Change formating of '.travis.yml' to better match output of Travis CLI
  .travis.yml
Labels: PR: internal 🏠

#1992 Change formatting of '.travis.yml'. Continuation of 2b9d571
  .travis.yml
Labels: PR: internal 🏠

#1993 Update Flow to v0.102
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1994 Improve Flow typing for 'memoize3'
  src/jsutils/memoize3.js
Labels: PR: polish 💅

#1995 Improve typings for 'toJSONDeep' function
  src/language/__tests__/toJSONDeep.js
Labels: PR: polish 💅

#1996 Update NPM token inside '.travis.yml'
  .travis.yml
Labels: PR: internal 🏠

#1998 Add "postversion" step to commit changed files
  package.json
Labels: PR: internal 🏠

#1999 changelog: Remove duplicate PRs
  resources/gen-changelog.js
Labels: PR: internal 🏠

#2000 dedent: Simplify and remove unused features
  src/jsutils/__tests__/dedent-test.js
  src/jsutils/dedent.js
Labels: PR: polish 💅

#2001 Switch some of arguments from `Array` to `$ReadOnlyArray`
  src/execution/values.js
  src/jsutils/dedent.js
  src/language/blockString.js
  src/language/printLocation.js
  src/language/visitor.js
  src/type/definition.js
  src/utilities/lexicographicSortSchema.js
  src/validation/rules/FieldsOnCorrectType.js
  src/validation/rules/KnownArgumentNames.js
  src/validation/rules/KnownTypeNames.js
  src/validation/rules/NoFragmentCycles.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
  src/validation/rules/PossibleTypeExtensions.js
Labels: PR: bug fix 🐞

#2002 Mark user-provided 'variableValues' as read-only
  src/execution/execute.js
  src/execution/values.js
  src/graphql.js
  src/subscription/subscribe.js
Labels: PR: bug fix 🐞

#2003 Travis: Disable automatic publishing on NPM
  .travis.yml
Labels: PR: internal 🏠

#2004 Travis: remove Node.js v11 from test matrix
  .travis.yml
Labels: PR: internal 🏠

#2006 buildClientSchema: add test for missing standard scalar
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: polish 💅
