Repository graphql/graphql-js, pull requests merged in 2019-02, with the labels that each got.

#1702 Add missing Flow typing for 'print' function
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/printer.js
  src/type/introspection.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/schemaPrinter.js
Labels: CLA Signed, PR: bug fix 🐞

#1704 Update ESLint
  .eslintrc.yml
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1705 Use isLeafType instead of isEnumType & isScalarType combo
  src/utilities/astFromValue.js
Labels: CLA Signed, PR: polish 💅

#1706 Cleanup unnecessary Query types from printSchema tests
  src/utilities/__tests__/schemaPrinter-test.js
Labels: CLA Signed

#1707 printSchema: Fix printing of empty types
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/schemaPrinter.js
Labels: CLA Signed, PR: bug fix 🐞

#1708 buildASTSchema: test building of empty types
  src/utilities/__tests__/buildASTSchema-test.js
Labels: CLA Signed, PR: polish 💅

#1709 Parser: use "any" util fn to parse object literal
  src/language/parser.js
Labels: CLA Signed, PR: polish 💅

#1710 Simplify "Type Map: includes input types only used in directives" test
  src/type/__tests__/schema-test.js
Labels: CLA Signed, PR: polish 💅

#1712 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1714 Update deps
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1554 Improve error message for missing required argument in field or directive
  src/validation/rules/ProvidedRequiredArguments.js
Labels: CLA Signed, PR: bug fix 🐞

#1717 NonNull tests: Use SDL to create test schema
  src/execution/__tests__/nonnull-test.js
Labels: CLA Signed, PR: polish 💅

#1718 Make all "not reachable" look and work the same
  src/execution/execute.js
  src/type/introspection.js
  src/utilities/astFromValue.js
  src/utilities/buildASTSchema.js
  src/utilities/coerceValue.js
  src/utilities/extendSchema.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/schemaPrinter.js
  src/utilities/typeFromAST.js
  src/utilities/valueFromAST.js
  src/utilities/valueFromASTUntyped.js
Labels: CLA Signed, PR: polish 💅

#1719 Move schema related test to "schema-test.js" + cleanup
  src/type/__tests__/definition-test.js
  src/type/__tests__/schema-test.js
Labels: CLA Signed, PR: polish 💅

#1720 Fix error message typo for extend types
  src/validation/rules/PossibleTypeExtensions.js
Labels: CLA Signed

#1721 definition tests: simplify NonNull and List tests
  src/type/__tests__/definition-test.js
Labels: CLA Signed, PR: polish 💅

#1722 Remove duplicating NonNull test
  src/type/__tests__/definition-test.js
Labels: CLA Signed, PR: polish 💅

#1723 Move 'Object.toString' tests to the appropriate files
  src/language/__tests__/source-test.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/directive-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/toStringTag-test.js
Labels: CLA Signed, PR: polish 💅

#1724 Add missing toStringTag into GraphQLList and GraphQLNonNull
  src/type/__tests__/definition-test.js
  src/type/definition.js
Labels: CLA Signed, PR: bug fix 🐞

#1725 Group type definitions tests by type kind
  src/type/__tests__/definition-test.js
Labels: CLA Signed, PR: polish 💅

#1728 Unwrap type definition tests
  src/type/__tests__/definition-test.js
Labels: CLA Signed, PR: polish 💅

#1729 Remove useless positive isTypeOf tests, since this function is optional
  src/type/__tests__/definition-test.js
Labels: PR: polish 💅

#1730 Allow for long string literals inside tests
  src/__tests__/starWarsIntrospection-test.js
  src/__tests__/starWarsSchema.js
  src/execution/__tests__/nonnull-test.js
  src/execution/__tests__/variables-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/enumType-test.js
  src/type/__tests__/introspection-test.js
  src/type/__tests__/validation-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/validation/__tests__/FieldsOnCorrectType-test.js
  src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
  src/validation/__tests__/validation-test.js
Labels: CLA Signed, PR: polish 💅

#1731 Update 'eslint-plugin-flowtype'
  .eslintrc.yml
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1732 Update Flow to 0.93
  .flowconfig
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1733 General cleanup of definition tests
  src/type/__tests__/definition-test.js
Labels: CLA Signed, PR: polish 💅

#1734 Use AST abbreviation consistently
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/__tests__/visitor-test.js
  src/subscription/__tests__/subscribe-test.js
Labels: CLA Signed, PR: polish 💅

#1735 Simplify checking of args inside visitor tests
  src/language/__tests__/visitor-test.js
Labels: CLA Signed, PR: polish 💅

#1736 Speedup visitor test on kitchenSinkQuery
  src/language/__tests__/visitor-test.js
Labels: CLA Signed, PR: polish 💅

#1737 Remove custom mocha timeout
  package.json
Labels: CLA Signed, PR: Internal 🏠

#1738 Update nyc
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1739 Move list of supported targets into separate file
  .babelrc.js
  .browserslistrc
Labels: CLA Signed, PR: Internal 🏠

#1740 Update deps
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1741 Update ESLint to v5.14
  .eslintrc.yml
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1742 Update to Mocha v6
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1743 Move Mocha config into .mocharc.yml
  .mocharc.yml
  package.json
  resources/watch.js
Labels: PR: Internal 🏠

#1744 Remove 'yarn t' in favor of 'yarn mocha' or 'npm run mocha'
  package.json
Labels: CLA Signed, PR: Internal 🏠

#1745 Do not run duplicating parser step on watch
  resources/watch.js
Labels: CLA Signed, PR: Internal 🏠

#1746 Use ESLint cache to speedup watch
  .gitignore
  resources/watch.js
Labels: CLA Signed, PR: Internal 🏠

#1747 Use ESLint cache for local development
  package.json
Labels: CLA Signed, PR: Internal 🏠

#1748 Inline 'beautify-benchmark' + heavy refactoring
  package.json
  resources/benchmark.js
  yarn.lock
Labels: CLA Signed, PR: Internal 🏠

#1750 Simplify benchmark by using more low-level API from 'benchmark.js'
  resources/benchmark.js
Labels: CLA Signed, PR: Internal 🏠

#1752 Update deps
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1754 Update deps
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1756 Speedup parser (~50%) by using 'slice' and 'charCodeAt' directly
  src/language/lexer.js
Labels: CLA Signed
