Repository graphql/graphql-js, pull requests merged in 2019-08, with the labels that each got.

#2069 parser: Inline 'parseExecutableDefinition' to simplify code
  src/language/parser.js
Labels: PR: polish 💅

#2070 coverage: Fixed coverage bug introduced in #2067
  resources/inline-invariant.js
Labels: PR: internal 🏠

#2075 inspect: correctly handle custom objects without class name
  src/jsutils/__tests__/inspect-test.js
  src/jsutils/inspect.js
Labels: bug

#2076 coverage: remove not essential 'istanbul ignore's
  resources/inline-invariant.js
  src/jsutils/__tests__/inspect-test.js
  src/jsutils/devAssert.js
  src/jsutils/invariant.js
  src/type/__tests__/introspection-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
Labels: PR: polish 💅

#2062 Limits errors in getVariableValues()
  src/execution/__tests__/variables-test.js
  src/execution/execute.js
  src/execution/values.js
  src/index.js
  src/jsutils/Path.js
  src/jsutils/printPathArray.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/coerceInputValue.js
  src/utilities/coerceValue.js
  src/utilities/index.js
  src/utilities/isValidJSValue.js
Labels: PR: feature 🚀

#2077 validation-test: remove unneeded 'specifiedRules'
  src/validation/__tests__/validation-test.js
Labels: PR: polish 💅

#2078 getVariableValues: improve coverage of 'maxErrors'
  src/execution/__tests__/variables-test.js
Labels: PR: polish 💅

#2079 Add benchmark for validating invalid query
  src/validation/__tests__/validateInvalidGQL-benchmark.js
Labels: PR: polish 💅

#2080 Update Flow to 0.105
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2082 Convert type definitions subtypes to be exact
  src/type/definition.js
Labels: PR: bug fix 🐞

#2083 GraphQLSchema: Remove unneeded recursion during type collection
  src/type/schema.js
Labels: PR: polish 💅

#2085 starWarsIntrospection-test: cleanup + add explanation comment
  src/__tests__/starWarsIntrospection-test.js
Labels: PR: polish 💅

#2086 GraphQLSchema: simplify `getPossibleTypes` & `isPossibleType`
  src/type/schema.js
Labels: PR: polish 💅

#2087 benchmark: use version specific babel
  resources/benchmark.js
Labels: PR: internal 🏠

#2088 benchmark: collect memory usage per operation
  package.json
  resources/benchmark-fork.js
  resources/benchmark.js
Labels: PR: internal 🏠

#2089 definition: replace object spread with explicit assignments
  src/type/__tests__/definition-test.js
  src/type/definition.js
Labels: PR: polish 💅

#2090 type definitions: Use consistent order for public fields
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
Labels: PR: polish 💅

#2091 definitions: make constructed fields non-optional
  src/type/__tests__/predicate-test.js
  src/type/definition.js
  src/type/introspection.js
Labels: PR: bug fix 🐞

#2094 tests: use consistent order of fields in snapshots
  src/type/__tests__/definition-test.js
  src/type/__tests__/directive-test.js
  src/type/__tests__/enumType-test.js
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: polish 💅

#2095 extendSchema-test: replace 'GraphQL*' types with SDL
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅

#2097 Add 'extensions' to all Type System objects
  src/jsutils/ObjMap.js
  src/jsutils/__tests__/toObjMap-test.js
  src/jsutils/toObjMap.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/directive-test.js
  src/type/__tests__/enumType-test.js
  src/type/__tests__/extensions-test.js
  src/type/__tests__/predicate-test.js
  src/type/definition.js
  src/type/directives.js
  src/type/introspection.js
  src/type/schema.js
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: feature 🚀

#2099 Switch all 'for..of' loops to assume they iterating only arrays
  .babelrc.js
Labels: bug

#2100 Convert more cycles to 'for..of'
  src/execution/execute.js
  src/jsutils/suggestionList.js
  src/polyfills/find.js
  src/polyfills/flatMap.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
Labels: PR: polish 💅

#2101 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2103 Add README for 'tstypes' folder
  tstypes/README.md
Labels: PR: docs 📝

#2112 Update deps
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2116 Copy non-standard properites from field's config
  src/type/definition.js
Labels: PR: bug fix 🐞

#2121 Drop Support for Node 6
  .browserslistrc
  .travis.yml
  package.json
Labels: PR: breaking change 💥

#2122 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2123 Update ESLint
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2124 Remove deprecated 'introspectionQuery' constant
  src/index.js
  src/utilities/index.js
  src/utilities/introspectionQuery.js
  tstypes/index.d.ts
  tstypes/utilities/index.d.ts
  tstypes/utilities/introspectionQuery.d.ts
Labels: PR: breaking change 💥

#2125 Move 'introspectionQuery.js' to 'getIntrospectionQuery.js'
  src/type/__tests__/introspection-test.js
  src/utilities/__tests__/introspectionFromSchema-benchmark.js
  src/utilities/buildClientSchema.js
  src/utilities/getIntrospectionQuery.js
  src/utilities/index.js
  src/utilities/introspectionFromSchema.js
  src/validation/__tests__/validateGQL-benchmark.js
  tstypes/utilities/buildClientSchema.d.ts
  tstypes/utilities/getIntrospectionQuery.d.ts
  tstypes/utilities/index.d.ts
  tstypes/utilities/introspectionFromSchema.d.ts
Labels: PR: polish 💅

#2126 Remove deprecated 'isValidJSValue' function
  src/index.js
  src/utilities/index.js
  src/utilities/isValidJSValue.js
  tstypes/index.d.ts
  tstypes/utilities/index.d.ts
  tstypes/utilities/isValidJSValue.d.ts
Labels: PR: breaking change 💥

#2127 Remove deprecated 'isValidLiteralValue' function
  src/index.js
  src/utilities/__tests__/isValidLiteralValue-test.js
  src/utilities/index.js
  src/utilities/isValidLiteralValue.js
  tstypes/index.d.ts
  tstypes/utilities/index.d.ts
  tstypes/utilities/isValidLiteralValue.d.ts
Labels: PR: breaking change 💥

#2128 Remove deprecated 'coerceValue' function
  src/index.js
  src/utilities/coerceValue.js
  src/utilities/index.js
  tstypes/index.d.ts
  tstypes/utilities/coerceValue.d.ts
  tstypes/utilities/index.d.ts
Labels: PR: breaking change 💥

#2129 Remove deprecated 'allowedLegacyNames' property of 'GraphQLSchema'
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/buildASTSchema.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  tstypes/type/schema.d.ts
Labels: PR: breaking change 💥

#2130 ValidationContext: Remove deprecated 'getErrors' and make 'onError' r…
  src/validation/ValidationContext.js
  tstypes/validation/ValidationContext.d.ts
Labels: PR: breaking change 💥

#2132 GraphQLArgument: make 'description' undefined by default
  src/type/__tests__/definition-test.js
  src/type/__tests__/directive-test.js
  src/type/definition.js
  src/type/directives.js
Labels: PR: breaking change 💥

#2133 Flow: fix warning about unused $FlowFixMe
  src/polyfills/flatMap.js
Labels: PR: polish 💅

#2135 tstypes: Use `any` as BREAK type.
  tstypes/language/visitor.d.ts
Labels: PR: bug fix 🐞

#2134 `void` => `undefined` in Path.d.ts
  tstypes/jsutils/Path.d.ts
Labels: PR: bug fix 🐞

#2137 Flow: fix errors in 'flatMap.js' on old Flow versions
  src/polyfills/flatMap.js
Labels: PR: bug fix 🐞

#2138 Add missing `toObjMap' conversion for `extensions` inside directive args
  src/type/__tests__/extensions-test.js
  src/type/directives.js
Labels: PR: bug fix 🐞

#2143 Fix 'isFinite' polyfill resulting in infinite recursion
  src/polyfills/isFinite.js
Labels: PR: bug fix 🐞

#2117 Removes non-standard properties from field objects
  src/type/definition.js
Labels: PR: breaking change 💥
