Repository graphql/graphql-js, pull requests merged in 2019-09, with the labels that each got.

#2146 Update ESLint to 6.3 + other deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2147 Use consistent naming for config arguments
  src/type/definition.js
  src/type/directives.js
Labels: PR: polish 💅

#2148 GraphQLEnumType: Drop support for 'undefined' custom value
  src/type/__tests__/definition-test.js
  src/type/definition.js
  src/utilities/__tests__/valueFromAST-test.js
Labels: PR: breaking change 💥

#2149 Errors if empty string is provided as operationName
  src/execution/__tests__/executor-test.js
  src/execution/execute.js
Labels: PR: breaking change 💥

#2151 findDangerousChanges: sort fields inside 'defaultValue'
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/findBreakingChanges.js
Labels: PR: bug fix 🐞

#2157 Fix typos
  src/language/__tests__/parser-test.js
  src/type/__tests__/scalars-test.js
  src/validation/__tests__/KnownTypeNames-test.js
Labels: PR: polish 💅

#2158 validation: Simplify 'ValuesOfCorrectType' rule
  src/validation/rules/ValuesOfCorrectType.js
Labels: PR: polish 💅

#2160 Validation: unify error messages
  src/type/__tests__/enumType-test.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/validation/__tests__/ExecutableDefinitions-test.js
  src/validation/__tests__/KnownArgumentNames-test.js
  src/validation/__tests__/KnownDirectives-test.js
  src/validation/__tests__/NoFragmentCycles-test.js
  src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
  src/validation/__tests__/PossibleTypeExtensions-test.js
  src/validation/__tests__/UniqueDirectiveNames-test.js
  src/validation/__tests__/UniqueDirectivesPerLocation-test.js
  src/validation/__tests__/UniqueVariableNames-test.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
  src/validation/__tests__/validation-test.js
  src/validation/rules/ExecutableDefinitions.js
  src/validation/rules/KnownArgumentNames.js
  src/validation/rules/KnownDirectives.js
  src/validation/rules/NoFragmentCycles.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
  src/validation/rules/PossibleTypeExtensions.js
  src/validation/rules/UniqueDirectiveNames.js
  src/validation/rules/UniqueDirectivesPerLocation.js
  src/validation/rules/UniqueVariableNames.js
  src/validation/rules/ValuesOfCorrectType.js
Labels: PR: bug fix 🐞

#2161 Unify rest of error messages
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/lists-test.js
  src/execution/__tests__/variables-test.js
  src/execution/execute.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/enumType-test.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/__tests__/findDeprecatedUsages-test.js
  src/utilities/coerceInputValue.js
  src/utilities/findDeprecatedUsages.js
Labels: PR: bug fix 🐞

#2165 didYouMean: quote suggested values
  src/jsutils/__tests__/didYouMean-test.js
  src/jsutils/didYouMean.js
  src/utilities/coerceInputValue.js
  src/validation/rules/FieldsOnCorrectType.js
  src/validation/rules/KnownArgumentNames.js
  src/validation/rules/KnownTypeNames.js
  src/validation/rules/PossibleTypeExtensions.js
  src/validation/rules/ValuesOfCorrectType.js
Labels: PR: polish 💅

#2166 Update deps
  .eslintrc.yml
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2171 tstypes: Add missing 'abstractType' argument to `GraphQLTypeResolver`
  tstypes/type/definition.d.ts
Labels: PR: bug fix 🐞

#2173 Use explicit comparisons instead of using `Boolean` constructor
  src/error/GraphQLError.js
  src/jsutils/isPromise.js
  src/language/visitor.js
  src/type/schema.js
  src/validation/rules/KnownTypeNames.js
Labels: PR: polish 💅

#2164 RFC: Number lexer lookahead restriction
  src/language/__tests__/lexer-test.js
  src/language/lexer.js
Labels: PR: breaking change 💥, spec RFC

#2174 Switch lexer and parser tests to exact match of error messages
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/schema-parser-test.js
Labels: PR: polish 💅

#2175 parser: Convert error messages to match common standard of this lib
  src/execution/__tests__/sync-test.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/schema-parser-test.js
  src/language/lexer.js
  src/language/parser.js
  src/utilities/stripIgnoredCharacters.js
Labels: PR: bug fix 🐞

#2176 parser: Show empty strings in error messages
  src/language/__tests__/parser-test.js
  src/language/parser.js
Labels: PR: bug fix 🐞

#2177 printSchema: support empty descriptions
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/buildASTSchema.js
  src/utilities/schemaPrinter.js
Labels: PR: bug fix 🐞

#2178 Fix bunch of edge cases with empty strings
  .flowconfig
  src/jsutils/invariant.js
  src/language/source.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  src/utilities/findDeprecatedUsages.js
  src/utilities/getOperationAST.js
Labels: PR: bug fix 🐞

#2184 toConfig: allows 'extensionASTNodes' to be undefined
  src/type/definition.js
  src/type/schema.js
  src/utilities/extendSchema.js
Labels: PR: breaking change 💥

#2182 Improve documentation for astFromValue
  src/utilities/astFromValue.js
Labels: PR: docs 📝

#1827 Update built-in scalar's parseLiteral method to throw TypeError
  src/type/__tests__/enumType-test.js
  src/type/__tests__/scalars-test.js
  src/type/__tests__/serialization-test.js
  src/type/scalars.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
Labels: PR: breaking change 💥

#2187 Scalars: convert errors from 'TypeError' to 'GraphQLError'
  src/execution/__tests__/variables-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/enumType-test.js
  src/type/scalars.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/coerceInputValue.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
  src/validation/rules/ValuesOfCorrectType.js
Labels: PR: bug fix 🐞

#2191 Fixes variable values of non-null type with default value
  src/execution/__tests__/variables-test.js
  src/execution/values.js
Labels: PR: bug fix 🐞

#2192 Fixes variable values of non-null type with default value
  src/execution/__tests__/variables-test.js
  src/execution/values.js
Labels: PR: bug fix 🐞

#2193 Remove unussed 'ABORT_VALIDATION' constant
  src/validation/validate.js
Labels: PR: polish 💅

#2198 Add two more tests to KnownArgumentNames validation rule
  src/validation/__tests__/KnownArgumentNames-test.js
Labels: PR: polish 💅

#2195 tstypes: fix typings for 'isSpecifiedDirective'/'isSpecifiedScalarType'
  tstypes/type/directives.d.ts
  tstypes/type/scalars.d.ts
Labels: PR: bug fix 🐞

#2200 tests: simplify 'includes interface's thunk subtypes in the type map'
  src/type/__tests__/schema-test.js
Labels: PR: polish 💅

#2201 Synchronise 'GraphQLDirective' formatting with other definitions
  src/type/directives.js
Labels: PR: polish 💅

#2202 tstypes: Synchronise TS typings for `GraphQL*` types
  tstypes/type/definition.d.ts
  tstypes/type/directives.d.ts
  tstypes/type/schema.d.ts
Labels: PR: bug fix 🐞

#2204 findBreakingChanges: better message for removing standard scalar
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/findBreakingChanges.js
Labels: PR: bug fix 🐞
