Repository graphql/graphql-js, pull requests merged in 2019-03, with the labels that each got.

#1757 GraphQLError: don't wrap single node in array
  src/error/__tests__/GraphQLError-test.js
  src/execution/values.js
  src/type/validate.js
  src/utilities/findDeprecatedUsages.js
  src/utilities/getOperationRootType.js
  src/validation/rules/ExecutableDefinitions.js
  src/validation/rules/FieldsOnCorrectType.js
  src/validation/rules/FragmentsOnCompositeTypes.js
  src/validation/rules/KnownDirectives.js
  src/validation/rules/KnownFragmentNames.js
  src/validation/rules/LoneAnonymousOperation.js
  src/validation/rules/NoUnusedFragments.js
  src/validation/rules/NoUnusedVariables.js
  src/validation/rules/PossibleFragmentSpreads.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/rules/ScalarLeafs.js
  src/validation/rules/VariablesAreInputTypes.js
Labels: CLA Signed, PR: polish 💅

#1758 Tests: 'expect(...).to.eql' => 'expect(...).to.deep.equal'
  src/utilities/__tests__/findBreakingChanges-test.js
Labels: CLA Signed, PR: polish 💅

#1759 Update Flow to 0.94
  .flowconfig
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1763 Fix typos in UniqueOperationTypes test
  src/validation/__tests__/UniqueOperationTypes-test.js
Labels: CLA Signed

#1766 Update ESLint to 5.15
  .eslintrc.yml
  package.json
  yarn.lock
Labels: CLA Signed, PR: Internal 🏠

#1765 Fix validator test names
  src/validation/__tests__/UniqueEnumValueNames-test.js
  src/validation/__tests__/UniqueFieldDefinitionNames-test.js
Labels: CLA Signed

#1764 Minor code simplification in validation rules
  src/validation/rules/UniqueEnumValueNames.js
  src/validation/rules/UniqueFieldDefinitionNames.js
Labels: CLA Signed, PR: polish 💅

#1767 Use non-capturing group inside RegExp
  src/utilities/astFromValue.js
Labels: CLA Signed, PR: polish 💅

#1768 Update deps
  package.json
  yarn.lock
Labels: CLA Signed

#1772 fix out of range return check for charCodeAt in lexer (NaN instead of null)
  src/language/lexer.js
Labels: CLA Signed

#1776 Update deps
  package.json
  yarn.lock
Labels: CLA Signed, PR: dependency 📦

#1778 Minor spelling errors in PossibleTpyeExtensions
  src/validation/__tests__/PossibleTypeExtensions-test.js
  src/validation/rules/PossibleTypeExtensions.js
Labels: CLA Signed

#1777 Prettier: normalize line ending to git standard
  .prettierrc
Labels: CLA Signed, PR: Internal 🏠

#1781 Add directive predicates tests and fix test names
  src/type/__tests__/directive-test.js
  src/type/__tests__/predicate-test.js
Labels: CLA Signed, PR: polish 💅

#1782 Fix grammar in error message
  src/type/__tests__/schema-test.js
  src/type/schema.js
Labels: CLA Signed, PR: polish 💅

#1785 Fix test case description
  src/execution/__tests__/union-interface-test.js
Labels: CLA Signed, PR: polish 💅

#1792 Duplicate fields in deep inputs not validated properly (#1791)
  src/validation/__tests__/UniqueInputFieldNames-test.js
  src/validation/rules/UniqueInputFieldNames.js
Labels: PR: bug fix 🐞

#1793 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1794 Update Flow to v0.95
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1795 Switch 'check-cover' to use Flow's 'batch-coverage' cmd
  package.json
Labels: PR: Internal 🏠

#1796 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1797 Update to Babel 7.4.1
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1798 Rename 'MaybePromise' to 'PromiseOrValue'
  src/execution/execute.js
  src/graphql.js
  src/jsutils/PromiseOrValue.js
  src/jsutils/promiseReduce.js
  src/subscription/mapAsyncIterator.js
  src/type/definition.js
Labels: PR: polish 💅

#1800 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1801 Tiny simplification in the parser code
  src/language/parser.js
Labels: PR: polish 💅

#1806 Enable Flow on more test files
  src/subscription/__tests__/asyncIteratorReject-test.js
  src/subscription/__tests__/eventEmitterAsyncIterator-test.js
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#1807 Update to ESLint 5.16
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#1808 buildClientSchema: Revert breaking change introduced in #1677
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/buildClientSchema.js
Labels: PR: bug fix 🐞

#1810 buildSchema/extendSchema: test standard scalars
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅
