Repository graphql/graphql-js, pull requests merged in 2019-11, with the labels that each got.

#2250 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2251 Update Flow to 0.111
  .flowconfig
  package.json
  src/type/__tests__/validation-test.js
  src/utilities/extendSchema.js
  yarn.lock
Labels: PR: dependency 📦

#2252 docs: follow express' best practice
  docs/Guides-ConstructingTypes.md
  docs/Tutorial-Authentication.md
  docs/Tutorial-BasicTypes.md
  docs/Tutorial-ExpressGraphQL.md
  docs/Tutorial-ObjectTypes.md
  docs/Tutorial-PassingArguments.md
Labels: PR: docs 📝

#2186 Consistent error messages in buildClientSchema
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/buildClientSchema.js
Labels: PR: polish 💅

#2255 Fix spelling: heirarchy to hierarchy
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: polish 💅

#2256 docs: correctly tag code samples
  docs/APIReference-Language.md
  docs/Guides-ConstructingTypes.md
  docs/Tutorial-Authentication.md
  docs/Tutorial-BasicTypes.md
  docs/Tutorial-ExpressGraphQL.md
  docs/Tutorial-GettingStarted.md
  docs/Tutorial-GraphQLClients.md
  docs/Tutorial-Mutations.md
  docs/Tutorial-ObjectTypes.md
  docs/Tutorial-PassingArguments.md
Labels: PR: docs 📝

#2257 cleanup ESLint config
  .eslintrc.yml
  src/type/__tests__/enumType-test.js
Labels: PR: polish 💅

#2258 list-test: Remove 'argument' usage
  src/execution/__tests__/lists-test.js
Labels: PR: polish 💅

#2259 ESLint: mark unused arguments with underscore
  .eslintrc.yml
  src/__tests__/starWarsSchema.js
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/mutations-test.js
  src/execution/__tests__/union-interface-test.js
  src/language/__tests__/visitor-test.js
  src/type/__tests__/enumType-test.js
  src/type/introspection.js
  src/validation/rules/FieldsOnCorrectType.js
  src/validation/rules/KnownDirectives.js
Labels: PR: polish 💅

#2261 TS: `introspectionTypes` should be array of `GraphQLNamedType`
  src/type/introspection.d.ts
Labels: PR: bug fix 🐞

#2263 Update prettier
  package.json
  src/language/__tests__/schema-parser-test.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/type/__tests__/enumType-test.js
  src/type/__tests__/validation-test.js
  src/validation/__tests__/NoFragmentCycles-test.js
  src/validation/__tests__/NoUndefinedVariables-test.js
  src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
  src/validation/__tests__/PossibleTypeExtensions-test.js
  src/validation/__tests__/SingleFieldSubscriptions-test.js
  src/validation/__tests__/UniqueArgumentNames-test.js
  src/validation/__tests__/UniqueDirectiveNames-test.js
  src/validation/__tests__/UniqueDirectivesPerLocation-test.js
  src/validation/__tests__/UniqueEnumValueNames-test.js
  src/validation/__tests__/UniqueFieldDefinitionNames-test.js
  src/validation/__tests__/UniqueFragmentNames-test.js
  src/validation/__tests__/UniqueInputFieldNames-test.js
  src/validation/__tests__/UniqueOperationNames-test.js
  src/validation/__tests__/UniqueOperationTypes-test.js
  src/validation/__tests__/UniqueTypeNames-test.js
  src/validation/__tests__/UniqueVariableNames-test.js
  src/validation/__tests__/VariablesInAllowedPosition-test.js
  src/validation/index.d.ts
  src/validation/index.js
  yarn.lock
Labels: PR: dependency 📦

#2265 Update Flow to v0.112
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2266 Update ESLint
  .eslintrc.yml
  package.json
  resources/benchmark.js
  yarn.lock
Labels: PR: dependency 📦

#2267 ESLint: remove options that match default ones
  .eslintrc.yml
Labels: PR: internal 🏠

#2269 Flow: switch more types to be exact
  .eslintrc.yml
  src/language/parser.js
  src/utilities/buildASTSchema.js
Labels: PR: bug fix 🐞

#2270 Enable 'default-param-last'
  .eslintrc.yml
  src/subscription/__tests__/subscribe-test.js
  src/validation/validate.js
Labels: PR: polish 💅

#2271 Update rest of deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2272 Enable 'require-await' ESLint check
  .eslintrc.yml
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅
