Repository graphql/graphql-js, pull requests merged in 2019-10, with the labels that each got.

#2208 Simplify 'validateObjectInterfaces' function
  src/type/validate.js
Labels: PR: polish 💅

#2205 Document private functions with @internal tag
  src/execution/execute.js
  src/execution/values.js
  src/language/blockString.js
  src/language/lexer.js
  src/type/definition.js
  src/validation/rules/KnownArgumentNames.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/specifiedRules.js
  src/validation/validate.js
  tstypes/language/blockString.d.ts
  tstypes/language/directiveLocation.d.ts
  tstypes/language/kinds.d.ts
  tstypes/utilities/findBreakingChanges.d.ts
  tstypes/validation/rules/KnownArgumentNames.d.ts
  tstypes/validation/rules/ProvidedRequiredArguments.d.ts
  tstypes/validation/specifiedRules.d.ts
  tstypes/validation/validate.d.ts
Labels: PR: polish 💅

#2209 Lexer: remove passthrough options
  src/language/lexer.js
  src/language/parser.js
  tstypes/language/lexer.d.ts
Labels: PR: breaking change 💥

#2196 Change 'isSpecified*' & 'isIntrospectionType' accept only correct types
  src/type/__tests__/predicate-test.js
  src/type/directives.js
  src/type/introspection.js
  src/type/scalars.js
  tstypes/type/directives.d.ts
  tstypes/type/introspection.d.ts
  tstypes/type/scalars.d.ts
Labels: PR: breaking change 💥

#2212 Fix minor typos in gen-changelog.js
  resources/gen-changelog.js
Labels: PR: polish 💅

#2084 RFC: Allow interfaces to implement other interfaces
  src/__fixtures__/schema-kitchen-sink.graphql
  src/execution/__tests__/union-interface-test.js
  src/execution/execute.js
  src/language/__tests__/schema-parser-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/ast.js
  src/language/parser.js
  src/language/printer.js
  src/language/visitor.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/introspection-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
  src/type/definition.js
  src/type/introspection.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/__tests__/lexicographicSortSchema-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/__tests__/typeComparators-test.js
  src/utilities/buildASTSchema.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  src/utilities/findBreakingChanges.js
  src/utilities/getIntrospectionQuery.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/schemaPrinter.js
  src/utilities/typeComparators.js
  src/validation/__tests__/FragmentsOnCompositeTypes-test.js
  src/validation/__tests__/harness.js
  tstypes/language/ast.d.ts
  tstypes/language/visitor.d.ts
  tstypes/type/definition.d.ts
  tstypes/type/schema.d.ts
  tstypes/utilities/getIntrospectionQuery.d.ts
Labels: PR: breaking change 💥, spec RFC

#2218 build: Add support for 'alpha' and 'beta' tags
  resources/build.js
  resources/gen-version.js
Labels: PR: internal 🏠

#2219 version: Fix version test for alpha & beta releases
  src/__tests__/version-test.js
Labels: PR: internal 🏠

#2220 gen-changelog: add support for rebased PRs
  resources/gen-changelog.js
Labels: PR: internal 🏠

#2223 printSchema: don't break description lines
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/schemaPrinter.js
Labels: PR: breaking change 💥

#2225 serialization-test: Don't use 'delete' on test objects
  src/type/__tests__/serialization-test.js
Labels: PR: polish 💅

#2228 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2229 Convert AST nodes types to be exact objects
  src/language/ast.js
Labels: PR: feature 🚀

#2231 Convert more types to be exact objects
  src/utilities/findBreakingChanges.js
  src/utilities/getIntrospectionQuery.js
Labels: PR: bug fix 🐞

#2232 execute: Convert ExecutionResult to be an exact object
  src/execution/execute.js
Labels: PR: bug fix 🐞

#2233 parser: convert Location to be an ES6 class
  src/language/ast.d.ts
  src/language/ast.js
  src/language/parser.js
Labels: PR: breaking change 💥

#2234 lexer: convert Token to be an ES6 class
  src/language/ast.d.ts
  src/language/ast.js
  src/language/lexer.js
Labels: PR: breaking change 💥

#2235 buildSchema/extendSchema: unify AST node processing
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
Labels: PR: polish 💅

#2236 buildASTSchema/extendSchema: unify directive building
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
Labels: PR: polish 💅

#2237 Update deps
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2239 chore: Spelling
  README.md
Labels: PR: docs 📝

#2238 grammar: 'falsey' => 'falsy'
  src/__fixtures__/kitchen-sink.graphql
  src/error/GraphQLError.js
  src/language/__tests__/printer-test.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
Labels: PR: polish 💅
