Repository graphql/graphql-js, pull requests merged in 2020-05, with the labels that each got.

#2526 Update deps
  .eslintrc.yml
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2527 Enable '@typescript-eslint/method-signature-style' lint rule
  .eslintrc.yml
  src/type/definition.d.ts
Labels: PR: polish 💅

#2528 Enable '@typescript-eslint/no-invalid-void-type' lint rule
  .eslintrc.yml
  src/type/definition.d.ts
Labels: PR: polish 💅

#2529 Add node v14 to the test matrix
  .travis.yml
Labels: PR: internal 🏠

#2530 Don't deploy on forks
  .travis.yml
Labels: PR: internal 🏠

#2531 Remove single quotes from Node.js versions
  .travis.yml
Labels: PR: internal 🏠

#2276 Add `@specifiedBy` directive
  docs/APIReference-TypeSystem.md
  src/type/__tests__/definition-test.js
  src/type/__tests__/introspection-test.js
  src/type/definition.d.ts
  src/type/definition.js
  src/type/directives.d.ts
  src/type/directives.js
  src/type/introspection.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/__tests__/getIntrospectionQuery-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/buildASTSchema.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/getIntrospectionQuery.js
  src/utilities/printSchema.js
Labels: PR: feature 🚀, spec RFC

#2534 Simplify 'getOperationTypeNode' function
  src/type/validate.js
Labels: PR: polish 💅

#2535 Make 'toJSON' definition explicit
  .eslintrc.yml
  src/jsutils/__tests__/inspect-test.js
  src/jsutils/defineInspect.js
  src/language/ast.d.ts
  src/language/ast.js
  src/type/definition.js
  src/type/directives.js
Labels: PR: polish 💅

#2536 Update deps
  .eslintrc.yml
  .flowconfig
  package.json
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/subscribe-test.js
  yarn.lock
Labels: PR: dependency 📦

#2537 extendSchema-test: improve test coverage
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅

#2540 Switch to SDL for validation tests
  src/validation/__tests__/FieldsOnCorrectTypeRule-test.js
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.js
  src/validation/__tests__/harness.js
  src/validation/__tests__/validation-test.js
Labels: PR: polish 💅

#2543 printSchema-test: cleanup and simplify
  src/utilities/__tests__/printSchema-test.js
Labels: PR: polish 💅

#2544 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2545 ESLint: replace deprecated rules with `eslint-plugin-node`
  .eslintrc.yml
  package.json
  resources/build.js
  yarn.lock
Labels: PR: internal 🏠

#2547 ts: add missing `schemaDescription` option of `getIntrospectionQuery`
  src/utilities/getIntrospectionQuery.d.ts
Labels: PR: bug fix 🐞

#2548 cspell: correctly check 'resources' folder
  package.json
  resources/eslint-rules/no-dir-import.js
Labels: PR: internal 🏠

#2549 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2538 [cspell] migrate custom words to upstream dictionaries
  cspell.json
Labels: PR: internal 🏠

#2550 resources: cleanup scripts
  .eslintrc.yml
  resources/benchmark.js
  resources/build.js
  resources/check-cover.js
  resources/gen-version.js
  resources/utils.js
Labels: PR: internal 🏠

#2551 package.json: change how 'eslint-plugin-graphql-internal' installed
  package.json
  yarn.lock
Labels: PR: internal 🏠

#2552 Switch to 'package-lock.json'
  .gitignore
  .travis.yml
  README.md
  package-lock.json
  package.json
  resources/benchmark.js
  resources/check-cycles.js
  resources/eslint-rules/README.md
  resources/gen-version.js
  yarn.lock
Labels: PR: internal 🏠

#2553 Switch to GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
  README.md
  resources/gitpublish.sh
Labels: PR: internal 🏠

#2555 Update deps
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2556 flowconfig: remove iterall from ignored
  .flowconfig
Labels: PR: internal 🏠

#2557 Fix deployment to 'npm' branch
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#2563 TS: Fix incorrect enum typing in findBreakingChanges
  src/utilities/findBreakingChanges.d.ts
Labels: PR: bug fix 🐞

#2561 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2564 package.json: use only exact versions
  package.json
Labels: PR: internal 🏠

#2565 Enable linting for istanbul ignore comments
  .eslintrc.yml
  package-lock.json
  package.json
  src/__tests__/version-test.js
  src/error/GraphQLError.js
  src/execution/execute.js
  src/execution/values.js
  src/jsutils/__tests__/inspect-test.js
  src/jsutils/__tests__/isCollection-test.js
  src/jsutils/dedent.js
  src/jsutils/defineInspect.js
  src/jsutils/devAssert.js
  src/jsutils/instanceOf.js
  src/jsutils/invariant.js
  src/jsutils/nodejsCustomInspectSymbol.js
  src/language/__tests__/visitor-test.js
  src/polyfills/arrayFrom.js
  src/polyfills/symbols.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/introspection-test.js
  src/type/validate.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/utilities/extendSchema.js
  src/validation/rules/KnownArgumentNamesRule.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
  src/validation/rules/ProvidedRequiredArgumentsRule.js
  src/validation/rules/UniqueEnumValueNamesRule.js
  src/validation/rules/UniqueFieldDefinitionNamesRule.js
  src/validation/rules/UniqueOperationTypesRule.js
Labels: PR: internal 🏠

#2571 Add missing exports for the new specifiedBy directive
  src/index.d.ts
  src/index.js
  src/type/index.d.ts
  src/type/index.js
Labels: PR: bug fix 🐞

#2572 Move `dedent` into new `__testUtils__` folder
  src/__testUtils__/__tests__/dedent-test.js
  src/__testUtils__/dedent.js
  src/error/__tests__/GraphQLError-test.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/printLocation-test.js
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-parser-test.js
  src/language/__tests__/schema-printer-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/concatAST-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/introspectionFromSchema-test.js
  src/utilities/__tests__/lexicographicSortSchema-test.js
  src/utilities/__tests__/printSchema-test.js
  src/utilities/__tests__/separateOperations-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
Labels: PR: internal 🏠

#2573 ESLint: Forbid usage of test utils inside production code
  .eslintrc.yml
Labels: PR: internal 🏠

#2574 blockString-test: add fuzzing test for 'printBlockString'
  .babelrc.json
  src/__testUtils__/__tests__/genFuzzStrings-test.js
  src/__testUtils__/__tests__/inspectStr-test.js
  src/__testUtils__/genFuzzStrings.js
  src/__testUtils__/inspectStr.js
  src/language/__tests__/blockString-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
Labels: PR: polish 💅

#2575 Move fuzzing tests into separate files
  .github/workflows/ci.yml
  .nycrc.yml
  package.json
  src/language/__tests__/blockString-fuzz.js
  src/language/__tests__/blockString-test.js
  src/utilities/__tests__/stripIgnoredCharacters-fuzz.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
Labels: PR: polish 💅

#2576 ESLint: Enable 'dot-notation' rule
  .eslintrc.yml
  resources/gen-changelog.js
  src/jsutils/__tests__/inspect-test.js
Labels: PR: polish 💅

#2578 CI: Fix copy-paster errors in 'fuzz' flow
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#2579 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2580 resources: correctly report errors in top level premisses
  resources/benchmark.js
  resources/gen-changelog.js
Labels: PR: internal 🏠

#2581 ci: add benchmark job
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#2583 ts: enable more tslint checks
  src/error/GraphQLError.d.ts
  src/language/visitor.d.ts
  src/tslint.json
Labels: PR: polish 💅

#2584 ts: use `typeof` instead of private types
  src/language/directiveLocation.d.ts
  src/language/kinds.d.ts
  src/language/tokenKind.d.ts
  src/utilities/findBreakingChanges.d.ts
Labels: PR: polish 💅

#2585 ts: switch more types to interfaces
  src/execution/execute.d.ts
  src/jsutils/Path.d.ts
  src/language/ast.d.ts
  src/tslint.json
  src/type/definition.d.ts
  src/type/schema.d.ts
  src/validation/ValidationContext.d.ts
Labels: PR: polish 💅

#2586 ts: used named export for 'Maybe' type
  src/error/GraphQLError.d.ts
  src/error/locatedError.d.ts
  src/execution/execute.d.ts
  src/execution/values.d.ts
  src/graphql.d.ts
  src/language/visitor.d.ts
  src/subscription/subscribe.d.ts
  src/tsutils/Maybe.d.ts
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/type/schema.d.ts
  src/utilities/TypeInfo.d.ts
  src/utilities/astFromValue.d.ts
  src/utilities/extendSchema.d.ts
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/getOperationAST.d.ts
  src/utilities/valueFromAST.d.ts
  src/utilities/valueFromASTUntyped.d.ts
  src/validation/ValidationContext.d.ts
  src/validation/validate.d.ts
Labels: PR: polish 💅

#2587 ts: cleanup definition files
  src/execution/execute.d.ts
  src/tslint.json
  src/type/definition.d.ts
  src/validation/validate.d.ts
Labels: PR: polish 💅

#2590 Update deps
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2592 gitignore: remove unused entry
  .gitignore
Labels: PR: internal 🏠

#2593 package.json: remove yarn from engines
  package.json
Labels: PR: internal 🏠

#2594 Exported `Token` and `Location` as ES6 classes
  src/index.d.ts
  src/index.js
  src/language/index.js
Labels: PR: bug fix 🐞

#2595 Update deps
  package-lock.json
  package.json
Labels: PR: dependency 📦
