Repository graphql/graphql-js, pull requests merged in 2020-09, with the labels that each got.

#2778 Add 'resolveOnNextTick' to use in tests
  src/__testUtils__/__tests__/resolveOnNextTick-test.js
  src/__testUtils__/resolveOnNextTick.js
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/mutations-test.js
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#2780 buildASTSchema-test: expend SDL descriptions test
  src/utilities/__tests__/buildASTSchema-test.js
Labels: PR: polish 💅

#2782 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
  src/type/definition.d.ts
  src/utilities/typedQueryDocumentNode.d.ts
Labels: PR: dependency 📦

#2783 LICENSE: Remove year from copyright
  LICENSE
Labels: PR: internal 🏠

#2785 Update Flow
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2788 Make specifiedByUrl in IntrospectionScalarType's flow type optional
  src/utilities/getIntrospectionQuery.js
Labels: PR: bug fix 🐞

#2733 Allow deprecating input fields and arguments
  src/type/__tests__/definition-test.js
  src/type/__tests__/directive-test.js
  src/type/__tests__/introspection-test.js
  src/type/__tests__/predicate-test.js
  src/type/__tests__/validation-test.js
  src/type/definition.d.ts
  src/type/definition.js
  src/type/directives.js
  src/type/introspection.js
  src/type/validate.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/printSchema-test.js
  src/utilities/extendSchema.js
  src/utilities/printSchema.js
  src/validation/__tests__/NoDeprecatedCustomRule-test.js
  src/validation/rules/custom/NoDeprecatedCustomRule.js
Labels: PR: feature 🚀, spec RFC

#2790 abstract-test: unify sync and async tests
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/abstract-test.js
Labels: PR: polish 💅

#2793 resolveType: add workaround for transformed schemas
  src/__tests__/starWarsSchema.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/union-interface-test.js
  src/execution/execute.js
  src/type/definition.js
Labels: PR: bug fix 🐞

#2794 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2795 subscribe: correct Flow definitions
  src/subscription/__tests__/eventEmitterAsyncIterator-test.js
  src/subscription/__tests__/eventEmitterAsyncIterator.js
  src/subscription/__tests__/subscribe-test.js
  src/subscription/mapAsyncIterator.js
  src/subscription/subscribe.js
Labels: PR: bug fix 🐞

#2796 subscribe-test: remove dependency on Node's EventEmitter
  src/subscription/__tests__/eventEmitterAsyncIterator.js
  src/subscription/__tests__/simplePubSub-test.js
  src/subscription/__tests__/simplePubSub.js
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#2799 benchmark: switch to spawn intead of fork
  cspell.json
  package.json
  resources/benchmark-fork.js
  resources/benchmark.js
Labels: PR: internal 🏠

#2802 integrationTests: remove shell command for copying files
  integrationTests/integration-test.js
Labels: PR: internal 🏠

#2770 Adding experimental online parser
  src/language/experimentalOnlineParser/README.md
  src/language/experimentalOnlineParser/grammar.d.ts
  src/language/experimentalOnlineParser/grammar.js
  src/language/experimentalOnlineParser/index.d.ts
  src/language/experimentalOnlineParser/index.js
  src/language/experimentalOnlineParser/onlineParser.d.ts
  src/language/experimentalOnlineParser/onlineParser.js
Labels: PR: feature 🚀

#2804 Added check for specific symbols in polyfills/symbols
  src/polyfills/symbols.js
Labels: PR: bug fix 🐞

#2797 Make print() break arguments over multiple lines
  src/language/__tests__/printer-test.js
  src/language/printer.js
Labels: PR: feature 🚀

#2806 Update outdated documentation
  docs/APIReference-Utilities.md
Labels: PR: docs 📝

#2810 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦
