Repository graphql/graphql-js, pull requests merged in 2020-02, with the labels that each got.

#2419 Add support for adding description to schema
  src/__fixtures__/schema-kitchen-sink.graphql
  src/language/__tests__/schema-parser-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/ast.d.ts
  src/language/ast.js
  src/language/parser.js
  src/language/printer.js
  src/language/visitor.d.ts
  src/language/visitor.js
  src/type/__tests__/introspection-test.js
  src/type/__tests__/schema-test.js
  src/type/introspection.js
  src/type/schema.d.ts
  src/type/schema.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/getIntrospectionQuery-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  src/utilities/getIntrospectionQuery.js
  src/utilities/introspectionFromSchema.js
  src/utilities/schemaPrinter.js
Labels: PR: feature 🚀, spec RFC

#2420 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2421 Use explicit default arguments
  src/language/printer.js
  src/language/source.js
Labels: PR: polish 💅

#2423 Use nullish coalescing operator in all appropriate places
  src/__tests__/starWarsData.js
  src/error/GraphQLError.js
  src/error/formatError.js
  src/error/locatedError.js
  src/execution/execute.js
  src/execution/values.js
  src/language/lexer.js
  src/language/parser.js
  src/language/printer.js
  src/language/visitor.js
  src/subscription/subscribe.js
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/TypeInfo.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
  src/validation/rules/FieldsOnCorrectTypeRule.js
  src/validation/rules/KnownArgumentNamesRule.js
  src/validation/rules/KnownTypeNamesRule.js
  src/validation/rules/LoneSchemaDefinitionRule.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
  src/validation/rules/ProvidedRequiredArgumentsRule.js
  src/validation/rules/UniqueEnumValueNamesRule.js
  src/validation/rules/UniqueFieldDefinitionNamesRule.js
  src/validation/rules/UniqueOperationTypesRule.js
Labels: PR: polish 💅

#2424 isValidNameError: Remove node argument
  src/error/locatedError.d.ts
  src/error/locatedError.js
  src/type/validate.js
  src/utilities/assertValidName.d.ts
  src/utilities/assertValidName.js
Labels: PR: breaking change 💥

#2425 nyc: exclude export files added only for deprecation
  .nycrc.yml
Labels: PR: internal 🏠

#2426 Rename 'schemaPrinter.js' to 'printSchema.js'
  src/type/__tests__/schema-test.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/introspectionFromSchema-test.js
  src/utilities/__tests__/lexicographicSortSchema-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/index.d.ts
  src/utilities/index.js
  src/utilities/printSchema.d.ts
  src/utilities/printSchema.js
Labels: PR: polish 💅

#2429 Simplify 'concatMaybeArrays'
  src/utilities/extendSchema.js
Labels: PR: polish 💅

#2430 Change 'toConfig' to always return 'extensionASTNodes' as array
  src/type/definition.js
  src/type/schema.js
  src/utilities/extendSchema.js
Labels: PR: feature 🚀

#2431 buildASTSchema: remove useless code
  src/utilities/buildASTSchema.js
Labels: PR: polish 💅

#2432 parser: simplify parsing of null, boolean and enum values
  src/language/parser.js
Labels: PR: polish 💅

#2433 Flow: Remove 'any's or improve their locality
  src/error/__tests__/locatedError-test.js
  src/execution/__tests__/executor-test.js
  src/language/__tests__/visitor-test.js
  src/polyfills/flatMap.js
  src/utilities/extendSchema.js
  src/validation/rules/UniqueDirectivesPerLocationRule.js
Labels: PR: polish 💅

#2434 Benchmark: set 'NODE_ENV=production' before running the benchmarks
  resources/benchmark-fork.js
Labels: PR: internal 🏠

#2435 docs: Add note about 'NODE_ENV=production'
  README.md
Labels: PR: docs 📝

#2436 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2437 astFromValue: reject non-finite numbers
  src/utilities/__tests__/astFromValue-test.js
  src/utilities/astFromValue.js
Labels: PR: bug fix 🐞

#2443 visitor-test: use proper test name
  src/language/__tests__/visitor-test.js
Labels: PR: polish 💅

#2438 NaN values should be checked inside scalar's `serialize` method
  src/execution/execute.js
  src/jsutils/isInvalid.js
  src/jsutils/isNullish.js
  src/utilities/__tests__/astFromValue-test.js
  src/utilities/__tests__/valueFromASTUntyped-test.js
  src/utilities/astFromValue.js
  src/utilities/valueFromAST.js
  src/utilities/valueFromASTUntyped.js
  src/validation/rules/ValuesOfCorrectTypeRule.js
Labels: PR: breaking change 💥

#2446 UniqueDirectivesPerLocation: check for directive uniqueness in extensions
  src/validation/__tests__/UniqueDirectivesPerLocationRule-test.js
  src/validation/rules/UniqueDirectivesPerLocationRule.js
Labels: PR: bug fix 🐞

#2447 Update deps
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2448 validation: Fix names of internal SDL rules
  src/validation/__tests__/KnownArgumentNamesRule-test.js
  src/validation/__tests__/ProvidedRequiredArgumentsRule-test.js
  src/validation/rules/KnownArgumentNamesRule.d.ts
  src/validation/rules/KnownArgumentNamesRule.js
  src/validation/rules/ProvidedRequiredArgumentsRule.d.ts
  src/validation/rules/ProvidedRequiredArgumentsRule.js
  src/validation/specifiedRules.js
Labels: PR: polish 💅

#2452 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2456 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2457 TS: add missing export on 'BuildSchemaOptions' type
  .eslintrc.yml
  src/utilities/buildASTSchema.d.ts
Labels: PR: bug fix 🐞

#2458 ESLint: move custom rule into CLI argument
  .eslintrc.yml
  package.json
Labels: PR: internal 🏠

#2460 getNullableType: fix TS signature
  src/type/definition.d.ts
  src/type/definition.js
Labels: PR: bug fix 🐞
