Repository graphql/graphql-js, pull requests merged in 2020-10, with the labels that each got.

#2813 benchmark: extract benchmarks into separate folder and run them on NPM package
  .eslintignore
  .eslintrc.yml
  .gitignore
  .prettierignore
  benchmark/benchmark.js
  benchmark/buildASTSchema-benchmark.js
  benchmark/buildClientSchema-benchmark.js
  benchmark/fixtures.js
  benchmark/github-schema.graphql
  benchmark/github-schema.json
  benchmark/introspectionFromSchema-benchmark.js
  benchmark/parser-benchmark.js
  benchmark/validateGQL-benchmark.js
  benchmark/validateInvalidGQL-benchmark.js
  benchmark/validateSDL-benchmark.js
  cspell.json
  package.json
  resources/colors.js
  src/__fixtures__/index.js
  src/language/__tests__/parser-benchmark.js
  src/utilities/__tests__/buildASTSchema-benchmark.js
  src/utilities/__tests__/buildClientSchema-benchmark.js
  src/utilities/__tests__/introspectionFromSchema-benchmark.js
  src/validation/__tests__/validateGQL-benchmark.js
  src/validation/__tests__/validateInvalidGQL-benchmark.js
  src/validation/__tests__/validateSDL-benchmark.js
Labels: PR: internal 🏠

#2815 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2816 Convert fixtures to be JS files
  .eslintrc.yml
  .prettierignore
  src/__fixtures__/index.js
  src/__testUtils__/kitchenSinkQuery.js
  src/__testUtils__/kitchenSinkSDL.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-parser-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/__tests__/visitor-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
Labels: PR: polish 💅

#2818 Cleanup '__fixtures__' leftovers
  .babelrc.json
  .eslintrc.yml
  .flowconfig
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
Labels: PR: internal 🏠

#2786 fix: ensure variance of types matches how values are used
  integrationTests/ts/index.ts
  src/utilities/typedQueryDocumentNode.d.ts
Labels: PR: bug fix 🐞

#2819 integrationTests: add Flow test
  integrationTests/flow/.flowconfig
  integrationTests/flow/index.mjs
  integrationTests/flow/package.json
  integrationTests/integration-test.js
  resources/build-npm.js
Labels: PR: internal 🏠

#2825 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2827 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2831 build: add support for experimental releases
  resources/build-npm.js
  src/__tests__/version-test.js
Labels: PR: internal 🏠

#2835 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2836 CI: test on node 15
  .github/workflows/ci.yml
  integrationTests/node/package.json
Labels: PR: internal 🏠

#2837 Flow: remove support for measuring Flow coverage
  .github/workflows/ci.yml
  .nycflowrc.yml
  .nycrc.yml
  package.json
  resources/check-cover.js
Labels: PR: internal 🏠
