Repository graphql/graphql-js, pull requests merged in 2020-03, with the labels that each got.

#2467 Update deps
  .eslintrc.yml
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2462 Unite tests for graphqlSync in one place
  src/__tests__/graphql-test.js
  src/execution/__tests__/sync-test.js
Labels: PR: polish 💅

#2469 isDeprecated: make required on GraphQLField/GraphQLEnumValue
  src/type/definition.d.ts
  src/type/definition.js
  src/type/introspection.js
Labels: PR: bug fix 🐞

#2473 schema-test: fix name of test
  src/type/__tests__/schema-test.js
Labels: PR: polish 💅

#2474 TS: fix typing for GraphQLField::deprecationReason
  src/type/definition.d.ts
Labels: PR: bug fix 🐞

#2476 Update deps
  .eslintrc.yml
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2488 TS(definition): remove TS-specific TArgs
  src/type/definition.d.ts
Labels: PR: breaking change 💥

#2490 TS: remove TS-specific TData from ExecutionResult
  src/execution/execute.d.ts
  src/graphql.d.ts
  src/subscription/subscribe.d.ts
Labels: PR: breaking change 💥

#2491 TS: remove TS-specific TSource argument for resolveFieldValueOrError
  src/execution/execute.d.ts
Labels: PR: polish 💅
