Repository graphql/graphql-js, pull requests merged in 2020-11, with the labels that each got.

#2838 TS: exclude integration tests from root tsconfig.json
  package.json
  tsconfig.json
Labels: PR: internal 🏠

#2840 resources: use named groups in RegExp
  resources/build-npm.js
  resources/gen-changelog.js
Labels: PR: internal 🏠

#2844 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2849 README: add instructions on using experimental features
  README.md
Labels: PR: docs 📝

#2847 Add tests for supporting Iterable collections across the lib
  src/execution/__tests__/lists-test.js
  src/utilities/__tests__/astFromValue-test.js
  src/utilities/__tests__/coerceInputValue-test.js
Labels: PR: polish 💅

#2850 Update deps
  .eslintrc.yml
  .flowconfig
  integrationTests/ts/package.json
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2851 tests: update 'getIntrospectionQuery' tests to use custom matchers
  src/utilities/__tests__/getIntrospectionQuery-test.js
Labels: PR: polish 💅

#2852 introspectionFromSchema: enable 'specifiedByUrl' by default
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/introspectionFromSchema-test.js
  src/utilities/introspectionFromSchema.js
Labels: PR: bug fix 🐞

#2855 introspection: Add missing support for deprecated input values
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/getIntrospectionQuery-test.js
  src/utilities/buildClientSchema.js
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/getIntrospectionQuery.js
  src/utilities/introspectionFromSchema.js
Labels: PR: bug fix 🐞

#2858 separateOperations-test: refactor tests to look like snapshots
  src/utilities/__tests__/separateOperations-test.js
Labels: PR: polish 💅

#2859 separateOperations: distinguish query and fragment names
  src/utilities/__tests__/separateOperations-test.js
  src/utilities/separateOperations.js
Labels: PR: bug fix 🐞
