Repository graphql/graphql-js, pull requests merged in 2020-01, with the labels that each got.

#2321 tests: in expect chains use '.to.not.' instead of '.not.to.'
  src/language/__tests__/lexer-test.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/predicate-test.js
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: polish 💅

#2322 separateOperations: simplify algorithm
  src/utilities/separateOperations.js
Labels: PR: polish 💅

#2323 tests: Transpile tests less aggressively
  .babelrc.js
  src/execution/__tests__/schema-test.js
Labels: PR: internal 🏠

#2324 validateSchema: remove validation arguments uniqueness
  src/type/validate.js
Labels: PR: polish 💅

#2325 Extract 'formatError' tests into separate file + improve coverage
  src/error/__tests__/GraphQLError-test.js
  src/error/__tests__/formatError-test.js
Labels: PR: polish 💅

#2326 Clearly mark not reachable places in the code
  src/__tests__/starWarsSchema.js
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/union-interface-test.js
  src/type/introspection.js
  src/utilities/TypeInfo.js
  src/utilities/extendSchema.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/schemaPrinter.js
  src/validation/rules/KnownDirectives.js
  src/validation/rules/PossibleTypeExtensions.js
Labels: PR: polish 💅

#2327 coverage: ignore uncovered branches caused by #2203
  src/execution/execute.js
  src/execution/values.js
  src/type/validate.js
  src/utilities/extendSchema.js
  src/validation/rules/KnownArgumentNames.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
  src/validation/rules/ProvidedRequiredArguments.js
  src/validation/rules/UniqueEnumValueNames.js
  src/validation/rules/UniqueFieldDefinitionNames.js
  src/validation/rules/UniqueOperationTypes.js
Labels: PR: polish 💅

#2328 Removes default values for required fields in GraphQL*Config types
  src/type/definition.js
Labels: PR: breaking change 💥

#2329 coverage: mark ignore statements
  src/__tests__/version-test.js
  src/error/GraphQLError.js
  src/jsutils/__tests__/inspect-test.js
  src/jsutils/dedent.js
  src/jsutils/defineToJSON.js
  src/jsutils/defineToStringTag.js
  src/jsutils/devAssert.js
  src/jsutils/instanceOf.js
  src/jsutils/invariant.js
  src/jsutils/nodejsCustomInspectSymbol.js
  src/type/__tests__/introspection-test.js
  src/type/schema.js
Labels: PR: polish 💅

#2330 Simplify findDeprecatedUsages since "deprecationReason" is always present
  src/utilities/__tests__/findDeprecatedUsages-test.js
  src/utilities/findDeprecatedUsages.js
Labels: PR: polish 💅

#2331 OverlappingFieldsCanBeMerged: arguments always have value
  src/validation/rules/OverlappingFieldsCanBeMerged.js
Labels: PR: polish 💅

#2332 Improve coverage of the entire codebase
  src/__fixtures__/schema-kitchen-sink.graphql
  src/__tests__/graphql-test.js
  src/__tests__/starWarsQuery-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/mutations-test.js
  src/execution/__tests__/nonnull-test.js
  src/execution/__tests__/union-interface-test.js
  src/execution/__tests__/variables-test.js
  src/jsutils/__tests__/invariant-test.js
  src/language/__tests__/predicates-test.js
  src/language/__tests__/schema-parser-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/__tests__/source-test.js
  src/language/__tests__/visitor-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/enumType-test.js
  src/type/__tests__/introspection-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/serialization-test.js
  src/type/__tests__/validation-test.js
  src/utilities/__tests__/TypeInfo-test.js
  src/utilities/__tests__/assertValidName-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/validation/__tests__/KnownDirectives-test.js
  src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js
  src/validation/__tests__/PossibleFragmentSpreads-test.js
  src/validation/__tests__/validation-test.js
Labels: PR: polish 💅

#2333 Unify arguments naming for parseValue/serialize methods
  src/type/definition.js
  src/type/scalars.js
Labels: PR: polish 💅

#2334 enum: 'parseLiteral/parseValue/serialize' now throw on invalid values
  src/execution/__tests__/executor-test.js
  src/type/__tests__/enumType-test.js
  src/type/definition.js
  src/utilities/__tests__/astFromValue-test.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/coerceInputValue.js
  src/utilities/valueFromAST.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
  src/validation/rules/ValuesOfCorrectType.js
Labels: PR: breaking change 💥

#2335 Update Flow to v0.115
  .flowconfig
  package.json
  src/utilities/extendSchema.js
  yarn.lock
Labels: PR: dependency 📦

#2336 Update deps
  cspell.json
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2337 Flow: add missing typings on exports
  src/__fixtures__/index.js
  src/__tests__/starWarsSchema.js
  src/jsutils/Path.js
  src/language/lexer.js
  src/language/visitor.js
Labels: PR: bug fix 🐞

#2346 Update deps
  .eslintrc.yml
  package.json
  src/index.d.ts
  yarn.lock
Labels: PR: dependency 📦

#2347 valueFromAST-test: improve readability
  src/utilities/__tests__/valueFromAST-test.js
Labels: PR: polish 💅

#2348 valueFromAST: fixed coercing of null variables on non-nullable type
  src/utilities/__tests__/valueFromAST-test.js
  src/utilities/valueFromAST.js
Labels: PR: bug fix 🐞

#2349 valueFromAST-test: improve coverage
  src/utilities/__tests__/valueFromAST-test.js
Labels: PR: polish 💅

#2350 astFromValue-test: improve coverage
  src/utilities/__tests__/astFromValue-test.js
Labels: PR: polish 💅

#2351 ValuesOfCorrectType: improve coverage
  src/validation/__tests__/ValuesOfCorrectType-test.js
Labels: PR: polish 💅

#2352 OverlappingFieldsCanBeMerged: remove excessive caching
  src/validation/rules/OverlappingFieldsCanBeMerged.js
Labels: PR: polish 💅

#2353 mapAsyncIterator: improve coverage
  src/subscription/__tests__/mapAsyncIterator-test.js
Labels: PR: polish 💅

#2354 Remove unused "asyncIteratorReject" utility method
  src/subscription/__tests__/asyncIteratorReject-test.js
  src/subscription/asyncIteratorReject.d.ts
  src/subscription/asyncIteratorReject.js
Labels: PR: polish 💅

#2355 subscribe: improve coverage
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#2358 Bring coverage to 100% 🎉
  src/language/__tests__/visitor-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/schema-test.js
  src/type/schema.js
  src/validation/__tests__/validation-test.js
Labels: PR: polish 💅

#2359 babel: Switch to static config to enable caching
  .babelrc
  .babelrc.js
Labels: PR: internal 🏠

#2360 Upgrade flow to v0.116
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2361 nyc: measure coverage of all files (except benchmark and polyfills)
  .nycrc.yml
Labels: PR: internal 🏠

#2363 Use native "Symbol.asyncIterator" in tests
  src/subscription/__tests__/eventEmitterAsyncIterator.js
Labels: PR: polish 💅

#2364 Remove 'iterall' as dependency. 'graphql' becomes zero dependency lib 🎉
  cspell.json
  package.json
  src/execution/execute.js
  src/jsutils/__tests__/isCollection-test.js
  src/jsutils/isCollection.js
  src/polyfills/arrayFrom.js
  src/polyfills/symbols.js
  src/subscription/mapAsyncIterator.js
  src/subscription/subscribe.js
  src/utilities/astFromValue.js
  src/utilities/coerceInputValue.js
  yarn.lock
Labels: PR: feature 🚀

#2365 Added 'eslint-plugin-import' lint rules
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: internal 🏠

#2366 eslint-plugin-import: Enable more checks
  .eslintrc.yml
  resources/gen-changelog.js
  src/language/__tests__/schema-parser-test.js
  src/language/printLocation.js
  src/type/__tests__/validation-test.js
  src/utilities/schemaPrinter.js
  src/validation/specifiedRules.js
Labels: PR: polish 💅

#2367 Define 'toStringTag' directly inside class definitions
  src/jsutils/defineToStringTag.js
  src/language/source.js
  src/polyfills/symbols.js
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
Labels: PR: polish 💅

#2369 GraphQLError: convert to ES6 class
  .babelrc
  cspell.json
  src/error/GraphQLError.js
Labels: PR: polish 💅

#2371 Flow: enable 'sketchy-null-bool' lint rule
  .flowconfig
  src/error/GraphQLError.js
  src/error/__tests__/GraphQLError-test.js
  src/error/locatedError.js
  src/execution/__tests__/executor-test.js
  src/execution/execute.js
  src/execution/values.js
  src/jsutils/isPromise.js
  src/language/__tests__/visitor-test.js
  src/language/parser.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/directives.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/astFromValue.js
  src/utilities/buildASTSchema.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  src/utilities/findDeprecatedUsages.js
  src/utilities/getIntrospectionQuery.js
  src/utilities/getOperationAST.js
  src/utilities/schemaPrinter.js
  src/validation/rules/LoneSchemaDefinition.js
  src/validation/rules/OverlappingFieldsCanBeMerged.js
  src/validation/rules/PossibleTypeExtensions.js
  src/validation/rules/UniqueDirectiveNames.js
  src/validation/rules/UniqueTypeNames.js
  src/validation/validate.js
Labels: PR: polish 💅

#2373 ESLint: Enable linting of TS files
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: internal 🏠

#2374 ESLint: enable '@typescript-eslint/no-unused-vars' rule
  .eslintrc.yml
  src/error/GraphQLError.d.ts
  src/execution/execute.d.ts
  src/execution/values.d.ts
  src/language/lexer.d.ts
  src/language/parser.d.ts
  src/type/schema.d.ts
  src/utilities/buildASTSchema.d.ts
  src/utilities/findBreakingChanges.d.ts
  src/utilities/schemaPrinter.d.ts
  src/validation/rules/SingleFieldSubscriptions.d.ts
  src/validation/specifiedRules.d.ts
Labels: PR: polish 💅

#2375 ESLint: enable more rules for TS code
  .eslintrc.yml
  src/language/printLocation.d.ts
  src/tsutils/Maybe.d.ts
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/utilities/buildClientSchema.d.ts
  src/validation/validate.d.ts
Labels: PR: polish 💅

#2376 ESLint: require empty line between import groups
  .eslintrc.yml
  resources/build.js
  resources/check-cover.js
  resources/check-cycles.js
  resources/gen-version.js
  src/error/formatError.d.ts
  src/error/locatedError.d.ts
  src/error/syntaxError.d.ts
  src/jsutils/toObjMap.js
  src/language/__tests__/parser-test.js
  src/language/visitor.d.ts
  src/type/definition.d.ts
  src/type/schema.d.ts
  src/type/validate.d.ts
  src/utilities/introspectionFromSchema.d.ts
Labels: PR: polish 💅

#2377 ESLint: Forbid importing directories
  .eslintrc.yml
  package.json
  resources/eslint-rules/no-dir-import.js
  src/index.d.ts
  src/index.js
  src/language/__tests__/parser-benchmark.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-parser-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/__tests__/visitor-test.js
  src/utilities/__tests__/buildASTSchema-benchmark.js
  src/utilities/__tests__/buildClientSchema-benchmark.js
  src/utilities/__tests__/introspectionFromSchema-benchmark.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/validation/__tests__/validateGQL-benchmark.js
  src/validation/__tests__/validateInvalidGQL-benchmark.js
  src/validation/__tests__/validateSDL-benchmark.js
Labels: PR: polish 💅

#2378 ESLint: ensure that all packaged code doesn't have any external deps
  .eslintrc.yml
Labels: PR: internal 🏠

#2379 build: mjs files import other files using full paths with extensions
  .babelrc
  resources/add-extension-to-import-paths.js
Labels: PR: feature 🚀

#2381 ESLint: enable 'import/no-cycle' rule
  .eslintrc.yml
  src/type/definition.js
  src/type/introspection.js
Labels: PR: internal 🏠

#2383 tests: remove a few invariants
  src/execution/__tests__/nonnull-test.js
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#2384 ESLint: Add all '@typescript-eslint/eslint-plugin' rules to config
  .eslintrc.yml
Labels: PR: internal 🏠

#2382 Change serialization for Int, Float and Boolean to work with objects
  src/type/__tests__/serialization-test.js
  src/type/scalars.js
Labels: PR: feature 🚀

#2387 TS: switch to 'Array<*>' style of array types
  .eslintrc.yml
  src/execution/execute.d.ts
  src/language/visitor.d.ts
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/type/schema.d.ts
  src/utilities/findDeprecatedUsages.d.ts
  src/validation/validate.d.ts
Labels: PR: polish 💅

#2388 ESLint: enable all TS rules that require running compiler
  .eslintrc.yml
  src/tsconfig.json
Labels: PR: internal 🏠

#2390 ESLint: enable bunch of TS lint rules
  .eslintrc.yml
  src/type/definition.d.ts
  src/type/definition.js
  src/utilities/buildClientSchema.d.ts
  src/utilities/buildClientSchema.js
Labels: PR: polish 💅

#2391 buildClientSchema: small code refactoring
  src/utilities/buildClientSchema.js
Labels: PR: polish 💅

#2392 ESLint: enable 'no-unnecessary-type-arguments' check
  .eslintrc.yml
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/getIntrospectionQuery.js
Labels: PR: polish 💅

#2393 FieldsOnCorrectType: refactor error message
  src/validation/rules/FieldsOnCorrectType.js
Labels: PR: polish 💅

#2394 suggestionList: lexicographically sort options with the same lexical distance
  src/jsutils/__tests__/suggestionList-test.js
  src/jsutils/suggestionList.js
  src/validation/__tests__/FieldsOnCorrectType-test.js
  src/validation/__tests__/KnownTypeNames-test.js
  src/validation/__tests__/ValuesOfCorrectType-test.js
Labels: PR: feature 🚀

#2395 FieldsOnCorrectType: implement stable sort order for suggested types
  src/jsutils/suggestionList.js
  src/validation/__tests__/FieldsOnCorrectType-test.js
  src/validation/rules/FieldsOnCorrectType.js
Labels: PR: feature 🚀

#2396 Babel: switch to using .babelrc.json as config
  .babelrc.json
Labels: PR: internal 🏠

#2397 Update deps
  .eslintrc.yml
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2398 Drop 'babel-polyfill'
  .mocharc.yml
  package.json
  yarn.lock
Labels: PR: internal 🏠

#2399 validation: Add missing rule exports
  src/index.d.ts
  src/index.js
  src/validation/index.d.ts
  src/validation/index.js
Labels: PR: feature 🚀

#2400 validation: Add missing rule exports
  src/index.js
  src/validation/index.js
  tstypes/index.d.ts
  tstypes/validation/index.d.ts
Labels: PR: feature 🚀

#2401 Add missing export for 'ExecutableDefinitionsRule'
  src/index.d.ts
  src/index.js
Labels: PR: bug fix 🐞

#2403 Update deps
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2404 FieldsOnCorrectTypeRule: improve type coverage
  src/polyfills/arrayFrom.js
  src/validation/rules/FieldsOnCorrectTypeRule.js
Labels: PR: polish 💅

#2406 buildClientSchema-test: remove dependency on order of types
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: polish 💅

#2407 Fixing double 'Rule' suffix that was accidentally introduced in #2402
  src/index.d.ts
  src/index.js
  src/validation/__tests__/LoneSchemaDefinitionRule-test.js
  src/validation/__tests__/UniqueDirectiveNamesRule-test.js
  src/validation/__tests__/UniqueEnumValueNamesRule-test.js
  src/validation/__tests__/UniqueOperationTypesRule-test.js
  src/validation/__tests__/UniqueTypeNamesRule-test.js
  src/validation/index.d.ts
  src/validation/index.js
  src/validation/rules/LoneSchemaDefinitionRule.d.ts
  src/validation/rules/LoneSchemaDefinitionRule.js
  src/validation/rules/UniqueDirectiveNamesRule.d.ts
  src/validation/rules/UniqueDirectiveNamesRule.js
  src/validation/rules/UniqueEnumValueNamesRule.d.ts
  src/validation/rules/UniqueEnumValueNamesRule.js
  src/validation/rules/UniqueOperationTypesRule.d.ts
  src/validation/rules/UniqueOperationTypesRule.js
  src/validation/rules/UniqueTypeNamesRule.d.ts
  src/validation/rules/UniqueTypeNamesRule.js
  src/validation/specifiedRules.js
Labels: PR: bug fix 🐞

#2408 schema: Always validate basic config structure
  src/type/__tests__/schema-test.js
  src/type/schema.js
Labels: PR: feature 🚀

#2410 Schema: keep order of user provided types
  src/__tests__/starWarsIntrospection-test.js
  src/execution/__tests__/union-interface-test.js
  src/type/__tests__/introspection-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
  src/type/schema.js
Labels: PR: feature 🚀

#2411 schemaPrinter: preserve order of types
  src/type/__tests__/schema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/extendSchema.js
  src/utilities/schemaPrinter.js
Labels: PR: breaking change 💥

#2412 Improve description for lexicographicSortSchema
  src/utilities/lexicographicSortSchema.d.ts
  src/utilities/lexicographicSortSchema.js
Labels: PR: polish 💅

#2413 validation: Export rules missing in <14.6.0 using legacy names
  src/validation/rules/ExecutableDefinitions.d.ts
  src/validation/rules/ExecutableDefinitions.js
  src/validation/rules/LoneSchemaDefinition.d.ts
  src/validation/rules/LoneSchemaDefinition.js
  src/validation/rules/PossibleTypeExtensions.d.ts
  src/validation/rules/PossibleTypeExtensions.js
  src/validation/rules/UniqueDirectiveNames.d.ts
  src/validation/rules/UniqueDirectiveNames.js
  src/validation/rules/UniqueEnumValueNames.d.ts
  src/validation/rules/UniqueEnumValueNames.js
  src/validation/rules/UniqueFieldDefinitionNames.d.ts
  src/validation/rules/UniqueFieldDefinitionNames.js
  src/validation/rules/UniqueOperationTypes.d.ts
  src/validation/rules/UniqueOperationTypes.js
  src/validation/rules/UniqueTypeNames.d.ts
  src/validation/rules/UniqueTypeNames.js
Labels: PR: feature 🚀

#2339 introspection: expose fields/values with empty deprecationReason
  src/type/__tests__/introspection-test.js
  src/type/introspection.js
Labels: PR: breaking change 💥

#2414 Update deps
  .eslintrc.yml
  .flowconfig
  package.json
  yarn.lock
Labels: PR: dependency 📦

#2415 findBreakingChanges: add check for removing repeatable from directive
  src/utilities/__tests__/findBreakingChanges-test.js
  src/utilities/findBreakingChanges.d.ts
  src/utilities/findBreakingChanges.js
Labels: PR: feature 🚀

#2416 introspection: Add support for repeatable directives
  src/type/__tests__/introspection-test.js
  src/type/introspection.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/getIntrospectionQuery-test.js
  src/utilities/__tests__/schemaPrinter-test.js
  src/utilities/buildClientSchema.js
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/getIntrospectionQuery.js
  src/utilities/introspectionFromSchema.js
Labels: PR: feature 🚀

#2417 schema-parser-test: fix description of a test case
  src/language/__tests__/schema-parser-test.js
Labels: PR: polish 💅

#2418 introspection: use consistent naming for 'resolve' args
  src/type/introspection.js
Labels: PR: polish 💅
