Repository graphql/graphql-js, pull requests merged in 2020-07, with the labels that each got.

#2681 Sync JSDoc comments with docs changes
  docs/APIReference-Language.md
  src/language/source.d.ts
  src/language/source.js
  src/language/visitor.d.ts
  src/language/visitor.js
Labels: PR: docs 📝

#2683 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2685 workflows: check commit for ignored files
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#2686 ESLint: remove 'ts-lint' commits
  .eslintrc.yml
  src/type/definition.d.ts
Labels: PR: polish 💅

#2687 Make documentation for 'getFieldDef' more accurate
  src/execution/execute.js
Labels: PR: docs 📝

#2688 Added new 'FormattedExecutionResult' type
  src/execution/execute.d.ts
  src/execution/execute.js
  src/execution/index.d.ts
  src/execution/index.js
  src/index.d.ts
  src/index.js
Labels: PR: feature 🚀

#2689 Update ignore files to ignore only top-level files
  .eslintignore
  .gitignore
  .prettierignore
Labels: PR: internal 🏠

#2690 Isolate integration tests from repository
  .eslintignore
  .gitignore
  .prettierignore
  cspell.json
  integrationTests/integration-test.js
  integrationTests/ts/package.json
Labels: PR: internal 🏠

#2691 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2695 Merge all tests for standard scalars into one file
  src/type/__tests__/scalars-test.js
  src/type/__tests__/serialization-test.js
Labels: PR: polish 💅

#2696 GraphQLScalarType: default 'parseLiteral' should handle variables
  src/type/__tests__/definition-test.js
  src/type/definition.js
Labels: PR: bug fix 🐞

#2697 Cleanup valueFromAST & valueFromASTUntyped tests
  src/utilities/__tests__/valueFromAST-test.js
  src/utilities/__tests__/valueFromASTUntyped-test.js
Labels: PR: polish 💅

#2698 list-test: Simplify utility function
  src/execution/__tests__/lists-test.js
Labels: PR: polish 💅

#2699 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2701 introspection: simpify 'includeDeprecated' logic
  src/type/introspection.js
Labels: PR: polish 💅

#2702 Improve readability of readToken function
  src/language/lexer.js
Labels: PR: polish 💅

#2703 lexer: inline positionAfterWhitespace function
  src/language/lexer.js
Labels: PR: polish 💅

#2704 readToken: improve readability by rearranging character groups
  src/language/lexer.js
Labels: PR: polish 💅

#2705 lexer: Fix formatting
  src/language/lexer.js
Labels: PR: polish 💅

#2706 buildASTSchema: should match order of default types and directives
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/buildASTSchema.js
Labels: PR: bug fix 🐞

#2707 introspection-test: convert schemas to SDL
  src/type/__tests__/introspection-test.js
Labels: PR: polish 💅

#2708 introspection-test: simplify tests for description fields
  src/type/__tests__/introspection-test.js
Labels: PR: polish 💅

#2709 introspection-test: improve testing of trivial resolvers
  src/type/__tests__/introspection-test.js
Labels: PR: polish 💅

#2710 validation-test: Improve typings
  src/type/__tests__/validation-test.js
Labels: PR: polish 💅

#2713 Update deps
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2720 NoDeprecatedCustomRule-test: simplify test cases
  src/validation/__tests__/NoDeprecatedCustomRule-test.js
Labels: PR: polish 💅

#2723 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦
