Repository graphql/graphql-js, pull requests merged in 2020-06, with the labels that each got.

#2596 ci: update 'cache' action
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#2602 Update dtslint
  package-lock.json
  package.json
  src/tslint.json
Labels: PR: dependency 📦

#2603 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2607 buildASTSchema: pass empty schema as literal
  src/utilities/buildASTSchema.js
Labels: PR: polish 💅

#2612 ESLint: fix updated paths inside comment
  .eslintrc.yml
Labels: PR: internal 🏠

#2613 ci: remove Node v13 after it's end of life
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#2617 schema-parser-test: Fix order of properties in expect chain
  src/language/__tests__/schema-parser-test.js
Labels: PR: polish 💅

#2619 Improve formatting of 'istanbul ignore' comments
  src/__testUtils__/dedent.js
  src/error/GraphQLError.js
  src/execution/execute.js
  src/execution/values.js
  src/jsutils/__tests__/inspect-test.js
  src/jsutils/__tests__/isCollection-test.js
  src/jsutils/defineInspect.js
  src/jsutils/devAssert.js
  src/jsutils/instanceOf.js
  src/jsutils/invariant.js
  src/jsutils/nodejsCustomInspectSymbol.js
  src/language/__tests__/visitor-test.js
  src/polyfills/arrayFrom.js
  src/polyfills/symbols.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/introspection-test.js
  src/type/validate.js
  src/utilities/extendSchema.js
  src/validation/rules/KnownArgumentNamesRule.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
  src/validation/rules/ProvidedRequiredArgumentsRule.js
  src/validation/rules/UniqueEnumValueNamesRule.js
  src/validation/rules/UniqueFieldDefinitionNamesRule.js
  src/validation/rules/UniqueOperationTypesRule.js
Labels: PR: polish 💅

#2620 inline-invariant: stop inserting `// istanbul ignore next` comments
  .babelrc.json
  resources/inline-invariant.js
  src/__tests__/starWarsSchema.js
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/union-interface-test.js
  src/execution/execute.js
  src/type/introspection.js
  src/utilities/astFromValue.js
  src/utilities/coerceInputValue.js
  src/utilities/extendSchema.js
  src/utilities/findBreakingChanges.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/printSchema.js
  src/utilities/typeFromAST.js
  src/utilities/valueFromAST.js
  src/utilities/valueFromASTUntyped.js
  src/validation/rules/KnownDirectivesRule.js
  src/validation/rules/PossibleTypeExtensionsRule.js
Labels: PR: internal 🏠

#2621 Moved `Maybe` to `jsutils` folder and remove `tsutils`
  src/error/GraphQLError.d.ts
  src/error/locatedError.d.ts
  src/execution/execute.d.ts
  src/execution/values.d.ts
  src/graphql.d.ts
  src/jsutils/Maybe.d.ts
  src/language/visitor.d.ts
  src/subscription/subscribe.d.ts
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/type/schema.d.ts
  src/utilities/TypeInfo.d.ts
  src/utilities/astFromValue.d.ts
  src/utilities/extendSchema.d.ts
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/getOperationAST.d.ts
  src/utilities/valueFromAST.d.ts
  src/utilities/valueFromASTUntyped.d.ts
  src/validation/ValidationContext.d.ts
  src/validation/validate.d.ts
Labels: PR: polish 💅

#2622 getOperationAST: make `operationName` optional
  src/utilities/getOperationAST.d.ts
  src/utilities/getOperationAST.js
Labels: PR: bug fix 🐞

#2623 TS: sync TS typings with Flow typings
  src/language/lexer.d.ts
  src/type/definition.d.ts
  src/type/schema.d.ts
  src/utilities/getIntrospectionQuery.d.ts
  src/validation/rules/KnownTypeNamesRule.d.ts
Labels: PR: bug fix 🐞

#2624 ci: fail CI if coverage is not 100% but still upload to codecov
  .github/workflows/ci.yml
  .nycrc.yml
  package.json
  resources/build.js
  resources/utils.js
  src/type/validate.js
Labels: PR: internal 🏠

#2625 TS: made `GraphQLError` constructor's second argument optional
  src/error/GraphQLError.d.ts
Labels: PR: bug fix 🐞

#2626 TS: add TData template argument to ExecutionResult type
  src/execution/execute.d.ts
Labels: PR: feature 🚀

#2627 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2630 Remove unintended 'console.log'
  resources/utils.js
Labels: PR: internal 🏠

#2644 ExecutionResult: add 'extensions' field
  src/execution/execute.d.ts
  src/execution/execute.js
Labels: PR: feature 🚀

#2647 Integration tests for TS
  .eslintrc.yml
  .github/workflows/ci.yml
  .gitignore
  integrationTests/README.md
  integrationTests/integration-test.js
  integrationTests/ts/index.ts
  integrationTests/ts/package-lock.json
  integrationTests/ts/package.json
  integrationTests/ts/test.js
  integrationTests/ts/tsconfig.json
  package.json
Labels: PR: internal 🏠

#2650 Remove dtslint check
  .eslintrc.yml
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/tslint.json
  tsconfig.json
Labels: PR: internal 🏠

#2651 Cleanup TS integration test
  .github/workflows/ci.yml
  integrationTests/integration-test.js
  integrationTests/ts/package-lock.json
  integrationTests/ts/package.json
Labels: PR: internal 🏠

#2652 integrationTests: suppress warnings from 'npm install'
  integrationTests/integration-test.js
  integrationTests/ts/package.json
Labels: PR: internal 🏠

#2653 Revert "instanceOf: support Deno (#2642)"
  src/jsutils/instanceOf.js
Labels: PR: internal 🏠

#2654 Move prettier down in the order of tests
  .github/workflows/ci.yml
  package.json
Labels: PR: internal 🏠

#2655 tests: Improve type coverage
  src/__testUtils__/__tests__/genFuzzStrings-test.js
  src/__tests__/starWarsData.js
  src/__tests__/starWarsIntrospection-test.js
  src/__tests__/starWarsValidation-test.js
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/directives-test.js
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/lists-test.js
  src/execution/__tests__/nonnull-test.js
  src/execution/__tests__/resolve-test.js
  src/execution/__tests__/schema-test.js
  src/execution/__tests__/union-interface-test.js
Labels: PR: polish 💅

#2656 Simplify ESLint config
  .eslintrc.yml
Labels: PR: internal 🏠

#2658 Update Flow
  .flowconfig
  package-lock.json
  package.json
  src/error/__tests__/formatError-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/executor-test.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-printer-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/directive-test.js
  src/type/__tests__/enumType-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
  src/utilities/__tests__/assertValidName-test.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/getOperationRootType-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/validation/__tests__/validation-test.js
Labels: PR: internal 🏠

#2659 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2660 union-interface-test: Improve typings
  src/execution/__tests__/union-interface-test.js
Labels: PR: polish 💅

#2662 Simplify prettier config
  .prettierignore
  package.json
Labels: PR: internal 🏠

#2665 Run cspell on entire project
  .github/CONTRIBUTING.md
  cspell.json
  docs/Tutorial-PassingArguments.md
  package.json
  resources/checkgit.sh
  resources/gitpublish.sh
Labels: PR: internal 🏠

#2667 Run ESLint on the entire repo
  .eslintignore
  .eslintrc.yml
  package.json
Labels: PR: internal 🏠

#2608 buildSchema: allow to reference introspection types
  src/utilities/__tests__/buildASTSchema-test.js
  src/validation/__tests__/KnownTypeNamesRule-test.js
  src/validation/rules/KnownTypeNamesRule.js
Labels: PR: bug fix 🐞

#2600 Add NoSchemaIntrospectionCustomRule
  src/index.d.ts
  src/index.js
  src/validation/__tests__/NoSchemaIntrospectionCustomRule-test.js
  src/validation/index.d.ts
  src/validation/index.js
  src/validation/rules/custom/NoSchemaIntrospectionCustomRule.d.ts
  src/validation/rules/custom/NoSchemaIntrospectionCustomRule.js
Labels: PR: feature 🚀

#2605 Add NoDeprecatedCustomRule and deprecate findDeprecatedUsages
  .nycrc.yml
  src/index.d.ts
  src/index.js
  src/utilities/__tests__/findDeprecatedUsages-test.js
  src/utilities/findDeprecatedUsages.d.ts
  src/utilities/findDeprecatedUsages.js
  src/utilities/index.d.ts
  src/utilities/index.js
  src/validation/ValidationContext.d.ts
  src/validation/ValidationContext.js
  src/validation/__tests__/NoDeprecatedCustomRule-test.js
  src/validation/index.d.ts
  src/validation/index.js
  src/validation/rules/custom/NoDeprecatedCustomRule.d.ts
  src/validation/rules/custom/NoDeprecatedCustomRule.js
Labels: PR: feature 🚀

#2671 Added 'executeSync': promise free version of `execute`.
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/directives-test.js
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/mutations-test.js
  src/execution/__tests__/nonnull-test.js
  src/execution/__tests__/resolve-test.js
  src/execution/__tests__/schema-test.js
  src/execution/__tests__/sync-test.js
  src/execution/__tests__/union-interface-test.js
  src/execution/__tests__/variables-test.js
  src/execution/execute.d.ts
  src/execution/execute.js
  src/execution/index.d.ts
  src/execution/index.js
  src/index.d.ts
  src/index.js
  src/utilities/__tests__/introspectionFromSchema-benchmark.js
  src/utilities/introspectionFromSchema.js
Labels: PR: feature 🚀

#2672 Remove swap file accidentally committed in #2560
  src/language/__tests__/.blockString-test.js.swp
Labels: PR: internal 🏠

#2674 Switch unused imports to type imports
  src/utilities/findDeprecatedUsages.js
  src/utilities/printSchema.js
Labels: PR: polish 💅

#2669 Add parentType to path to avoid path ambiguity
  src/execution/__tests__/executor-test.js
  src/execution/execute.js
  src/jsutils/Path.d.ts
  src/jsutils/Path.js
  src/subscription/subscribe.js
  src/utilities/coerceInputValue.js
Labels: PR: feature 🚀

#2465 Change type of extensions from anonymous Record to named interfaces
  integrationTests/ts/index.ts
  src/index.d.ts
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/type/index.d.ts
  src/type/schema.d.ts
Labels: PR: feature 🚀

#2677 README: use local references
  README.md
Labels: PR: docs 📝

#2678 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2679 mapAsyncIterator-test: replace 'invariant' with expect chains
  src/subscription/__tests__/mapAsyncIterator-test.js
Labels: PR: polish 💅
