Repository graphql/graphql-js, pull requests merged in 2020-08, with the labels that each got.

#2729 execute: simplify check for promises inside collections
  src/execution/execute.js
Labels: PR: polish 💅

#2718 introspectionQuery -> getIntrospectionQuery
  docs/APIReference-Utilities.md
Labels: PR: docs 📝

#2731 execute/subscribe: simplify to improve debugging experience
  src/error/locatedError.d.ts
  src/error/locatedError.js
  src/execution/execute.d.ts
  src/execution/execute.js
  src/subscription/subscribe.js
Labels: PR: feature 🚀

#2736 list-test: improve tests readability
  src/execution/__tests__/lists-test.js
Labels: PR: polish 💅

#2737 list-test: improve test readability (part 2)
  src/execution/__tests__/lists-test.js
Labels: PR: polish 💅

#2738 list-test: improve test readability (part 3)
  src/execution/__tests__/lists-test.js
Labels: PR: polish 💅

#2739 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2742 integrationTests: add tests for supported Node versions
  .eslintrc.yml
  integrationTests/integration-test.js
  integrationTests/node/index.js
  integrationTests/node/package.json
  integrationTests/node/test.js
  resources/build-npm.js
Labels: PR: internal 🏠

#2744 parser: Export `Parser` class as unstable API
  src/language/parser.js
Labels: PR: feature 🚀

#2745 blockString-test: add test for not escaping characters
  src/language/__tests__/blockString-test.js
Labels: PR: polish 💅

#2747 Update CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: PR: docs 📝

#2748 getBlockStringIndentation: simplify implementation
  src/language/__tests__/blockString-test.js
  src/language/blockString.d.ts
  src/language/blockString.js
  src/utilities/stripIgnoredCharacters.js
Labels: PR: polish 💅

#2752 integrationTests: add TS 4.0
  integrationTests/ts/package.json
Labels: PR: internal 🏠

#2753 integrationTests: minimise test logs
  integrationTests/integration-test.js
  integrationTests/node/package.json
  integrationTests/ts/package.json
Labels: PR: internal 🏠

#2754 Update Flow
  .flowconfig
  package-lock.json
  package.json
  src/error/GraphQLError.js
  src/error/__tests__/formatError-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/executor-test.js
  src/jsutils/inspect.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-printer-test.js
  src/language/__tests__/toJSONDeep.js
  src/language/source.js
  src/polyfills/arrayFrom.js
  src/polyfills/find.js
  src/polyfills/flatMap.js
  src/polyfills/isFinite.js
  src/polyfills/isInteger.js
  src/polyfills/objectEntries.js
  src/polyfills/objectValues.js
  src/polyfills/symbols.js
  src/subscription/__tests__/eventEmitterAsyncIterator-test.js
  src/subscription/__tests__/eventEmitterAsyncIterator.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/subscribe-test.js
  src/subscription/mapAsyncIterator.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/directive-test.js
  src/type/__tests__/enumType-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
  src/type/definition.js
  src/type/directives.js
  src/type/scalars.js
  src/type/schema.js
  src/utilities/__tests__/assertValidName-test.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/getOperationRootType-test.js
  src/utilities/__tests__/printSchema-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/validation/__tests__/validation-test.js
Labels: PR: dependency 📦

#2755 lists-test: remove unneeded async
  src/execution/__tests__/lists-test.js
Labels: PR: polish 💅

#2712 Support returning async iterables from resolver functions
  src/execution/__tests__/lists-test.js
  src/execution/execute.js
  src/jsutils/isAsyncIterable.js
  src/subscription/subscribe.js
Labels: PR: feature 🚀

#2759 parser: improve formatting of the comments
  src/language/parser.js
Labels: PR: polish 💅

#2760 parser: generalize parsing of lists with delimiters
  src/language/parser.js
Labels: PR: polish 💅

#2761 Switch all code to create GraphQLList/GraphQLNonNull instances with new
  src/__tests__/starWarsSchema.js
  src/execution/__tests__/abstract-promise-test.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/executor-test.js
  src/execution/__tests__/nonnull-test.js
  src/execution/__tests__/schema-test.js
  src/execution/__tests__/union-interface-test.js
  src/execution/__tests__/variables-test.js
  src/subscription/__tests__/subscribe-test.js
  src/type/__tests__/definition-test.js
  src/type/__tests__/predicate-test.js
  src/type/__tests__/schema-test.js
  src/type/__tests__/validation-test.js
  src/type/definition.js
  src/type/directives.js
  src/type/introspection.js
  src/utilities/__tests__/astFromValue-test.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/__tests__/printSchema-test.js
  src/utilities/__tests__/typeComparators-test.js
  src/utilities/__tests__/valueFromAST-test.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/typeFromAST.js
Labels: PR: polish 💅

#2762 Enable 'new-cap' ESLint rule
  .eslintrc.yml
  resources/benchmark.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/validation/rules/KnownArgumentNamesRule.js
  src/validation/rules/ProvidedRequiredArgumentsRule.js
Labels: PR: polish 💅

#2766 parser: simplify a few utility functions
  src/language/printer.js
Labels: PR: polish 💅

#2767 Update prettier
  package-lock.json
  package.json
  src/__tests__/starWarsData.js
  src/jsutils/__tests__/isCollection-test.js
  src/language/lexer.js
Labels: PR: dependency 📦

#2771 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2773 npm: CJS files now require other files using using explicit extensions
  .babelrc.json
Labels: PR: internal 🏠

#2774 isCollection: add test that generator function is not iterable
  src/jsutils/__tests__/isCollection-test.js
Labels: PR: polish 💅

#2775 Move 'isAsyncIterable' into 'jsutils'
  src/jsutils/__tests__/isAsyncIterable-test.js
  src/jsutils/isAsyncIterable.js
  src/subscription/subscribe.js
Labels: PR: polish 💅

#2776 Flow: add hack to support 'Symbol.asyncIterator'
  flow-typed/core.js
  src/jsutils/__tests__/isAsyncIterable-test.js
  src/polyfills/symbols.js
  src/subscription/__tests__/eventEmitterAsyncIterator.js
  src/subscription/__tests__/mapAsyncIterator-test.js
Labels: PR: polish 💅

#2777 Remove polyfill for 'flatMap'
  src/polyfills/flatMap.js
  src/type/validate.js
  src/utilities/concatAST.js
Labels: PR: polish 💅
