Repository graphql/graphql-js, pull requests merged in 2021-04, with the labels that each got.

#3011 mapAsyncIterator: add default value for 'rejectCallback'
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#3012 mapAsyncIterator: allow 'rejectCallback' to only be synchronous
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#3013 mapAsyncIterator: simplify mapResult
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#3014 mapAsyncIterator: simplify abruptClose
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#3015 printer-test: switch to dedentString
  src/language/__tests__/printer-test.js
Labels: PR: polish 💅

#3016 printer-test: do more check on kitchen sink tests
  src/language/__tests__/printer-test.js
  src/language/__tests__/schema-printer-test.js
Labels: PR: polish 💅

#3017 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
  src/jsutils/instanceOf.js
  src/jsutils/isAsyncIterable.js
  src/jsutils/isIteratableObject.js
Labels: PR: dependency 📦

#3018 build: run prettier on generated files
  resources/build-deno.js
  resources/build-npm.js
Labels: PR: internal 🏠

#3019 inline-invariant: switch to use `false` instead of `0`
  resources/inline-invariant.js
Labels: PR: internal 🏠

#3020 Update deps
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3021 gen-version: prettify source code
  resources/gen-version.js
Labels: PR: internal 🏠

#3022 memoize3: remove unnecessary `mixed` type
  src/jsutils/memoize3.js
Labels: PR: polish 💅

#3023 predicate-test: improve typecheck
  src/type/__tests__/predicate-test.js
Labels: PR: polish 💅

#3024 subscribe: simplify by rewriting as async functions
  src/subscription/subscribe.js
Labels: PR: polish 💅

#3025 subscribe: simplify root field extraction
  src/subscription/subscribe.js
Labels: PR: polish 💅

#3026 Switch some of 'Object.keys' to more modern ES6 constructs
  flow-typed/core.js
  src/jsutils/inspect.js
  src/jsutils/mapValue.d.ts
  src/jsutils/mapValue.js
  src/language/__tests__/toJSONDeep.js
  src/utilities/lexicographicSortSchema.js
  src/validation/rules/KnownTypeNamesRule.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
  src/validation/rules/PossibleTypeExtensionsRule.js
  src/validation/rules/ProvidedRequiredArgumentsRule.js
Labels: PR: polish 💅

#3027 subscribe: drop mapping of AsyncIterable errors
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/subscribe-test.js
  src/subscription/mapAsyncIterator.js
  src/subscription/subscribe.js
Labels: PR: breaking change 💥

#3028 mapAsyncIterator: move promise resolution into `mapResult`
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#2979 fix(stream): allow initialValue of zero
  src/execution/__tests__/stream-test.js
  src/execution/execute.js
Labels: stream/defer

#3031 Drop experimental online parser
  src/language/experimentalOnlineParser/README.md
  src/language/experimentalOnlineParser/grammar.d.ts
  src/language/experimentalOnlineParser/grammar.js
  src/language/experimentalOnlineParser/index.d.ts
  src/language/experimentalOnlineParser/index.js
  src/language/experimentalOnlineParser/onlineParser.d.ts
  src/language/experimentalOnlineParser/onlineParser.js
Labels: PR: breaking change 💥

#3034 visitor-test: cleanup test for nodes with unknown kinds
  src/language/__tests__/visitor-test.js
Labels: PR: polish 💅

#3035 printSchema: replace array concat with spead + update comment
  src/utilities/printSchema.js
Labels: PR: polish 💅

#3036 integrationTests: test package with TS 4.2
  integrationTests/ts/package.json
Labels: PR: internal 🏠

#3037 Update deps
  .eslintrc.yml
  cspell.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3039 simplify predicate-test type
  src/type/__tests__/predicate-test.js
Labels: PR: polish 💅

#3041 Use correct terminology around iterators and iterable
  src/execution/execute.js
  src/jsutils/__tests__/isAsyncIterable-test.js
  src/jsutils/__tests__/isIterableObject-test.js
  src/jsutils/__tests__/isIteratableObject-test.js
  src/jsutils/isAsyncIterable.d.ts
  src/jsutils/isAsyncIterable.js
  src/jsutils/isIterableObject.d.ts
  src/jsutils/isIterableObject.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/utilities/astFromValue.js
  src/utilities/coerceInputValue.js
Labels: PR: polish 💅

#3042 Remove superficial usages of 'Array.from'
  .flowconfig
  src/__testUtils__/__tests__/genFuzzStrings-test.js
  src/type/schema.js
  src/utilities/astFromValue.js
  src/validation/rules/FieldsOnCorrectTypeRule.js
Labels: PR: polish 💅

#3032 Use specifiedBy instead of specifiedByUrl
  docs/APIReference-TypeSystem.md
  src/type/__tests__/definition-test.js
  src/type/__tests__/introspection-test.js
  src/type/definition.d.ts
  src/type/definition.js
  src/type/introspection.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/getIntrospectionQuery-test.js
  src/utilities/__tests__/printSchema-test.js
  src/utilities/buildClientSchema.js
  src/utilities/extendSchema.js
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/getIntrospectionQuery.js
  src/utilities/printSchema.js
Labels: PR: breaking change 💥

#3050 Generalize defineArguments()
  src/type/definition.js
  src/type/directives.js
  src/utilities/printSchema.js
Labels: PR: polish 💅
