Repository graphql/graphql-js, pull requests merged in 2021-11, with the labels that each got.

#3348 GraphQLError-test: text how extensions is inherited from originalError
  src/error/__tests__/GraphQLError-test.ts
Labels: PR: polish 💅

#3354 Lexer: fix line & column for multiline BLOCK_STRING tokens
  src/language/__tests__/lexer-test.ts
  src/language/lexer.ts
Labels: PR: bug fix 🐞

#3365 Add devAssert about removal of positional arguments
  src/execution/execute.ts
  src/execution/subscribe.ts
  src/graphql.ts
Labels: PR: polish 💅

#3355 Export GRAPHQL_MAX_INT and GRAPHQL_MIN_INT
  src/index.ts
  src/type/index.ts
  src/type/scalars.ts
Labels: PR: feature 🚀

#3375 printSchema: handle descriptions that are non-printable as block strings
  src/language/__tests__/blockString-fuzz.ts
  src/language/__tests__/blockString-test.ts
  src/language/blockString.ts
  src/language/characterClasses.ts
  src/language/lexer.ts
  src/utilities/__tests__/printSchema-test.ts
  src/utilities/printSchema.ts
  src/utilities/stripIgnoredCharacters.ts
Labels: PR: bug fix 🐞

#3376 execute: fix spec section names in comments
  src/execution/execute.ts
Labels: PR: polish 💅

#3377 lexer-tests: Use tildas as invalid characters
  src/language/__tests__/lexer-test.ts
Labels: PR: polish 💅

#3384 Preserve non-error values thrown from resolvers
  src/error/__tests__/locatedError-test.ts
  src/error/locatedError.ts
  src/jsutils/toError.ts
Labels: PR: feature 🚀

#3386 Add support for Node17
  .github/workflows/ci.yml
  integrationTests/node/package.json
Labels: PR: internal 🏠

#3387 Update package-lock.json
  package-lock.json
  src/type/directives.ts
  src/utilities/__tests__/buildASTSchema-test.ts
  src/utilities/__tests__/printSchema-test.ts
Labels: PR: dependency 📦

#3388 Drop "eslint-plugin-istanbul" and implement as internal ESLint rule
  .eslintrc.yml
  package-lock.json
  package.json
  resources/eslint-internal-rules/index.js
  resources/eslint-internal-rules/require-coverage-ignore-reason.js
Labels: PR: internal 🏠

#3389 package.json: Drop unused '@babel/eslint-parser'
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3390 Update deps
  .eslintrc.yml
  cspell.yml
  integrationTests/ts/package.json
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3391 Enable '@typescript-eslint/switch-exhaustiveness-check' rule
  .eslintrc.yml
  src/__tests__/starWarsSchema.ts
  src/execution/execute.ts
  src/language/parser.ts
  src/type/schema.ts
  src/utilities/TypeInfo.ts
  src/utilities/__tests__/separateOperations-test.ts
  src/utilities/buildClientSchema.ts
  src/utilities/extendSchema.ts
  src/utilities/separateOperations.ts
  src/utilities/valueFromASTUntyped.ts
  src/validation/rules/KnownDirectivesRule.ts
  src/validation/rules/PossibleTypeExtensionsRule.ts
Labels: PR: polish 💅

#3392 Remove $FlowFixMe comments
  src/jsutils/__tests__/instanceOf-test.ts
Labels: PR: polish 💅

#3396 typeFromAST: use exhaustive switch and remove invariant
  src/utilities/typeFromAST.ts
Labels: PR: polish 💅
