Repository graphql/graphql-js, pull requests merged in 2021-02, with the labels that each got.

#2904 Remove support for positional args in graphql/execute/subscribe func
  src/__tests__/starWarsQuery-test.js
  src/execution/__tests__/executor-test.js
  src/execution/execute.js
  src/graphql.js
  src/subscription/__tests__/subscribe-test.js
  src/subscription/subscribe.js
Labels: PR: breaking change 💥

#2905 resolveType: remove support for returning GraphQLObjectType
  src/execution/__tests__/abstract-test.js
  src/execution/execute.js
  src/type/definition.d.ts
  src/type/definition.js
Labels: PR: breaking change 💥

#2906 Convert GraphQLList and GraphQLNonNull into proper classes
  src/type/definition.d.ts
  src/type/definition.js
  src/utilities/extendSchema.js
Labels: PR: breaking change 💥

#2907 Remove 'find' polyfill
  src/execution/values.js
  src/polyfills/find.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/TypeInfo.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
Labels: PR: polish 💅

#2911 Remove 'isFinite' & 'isInteger' polyfills
  src/polyfills/isFinite.js
  src/polyfills/isInteger.js
  src/type/scalars.js
  src/utilities/astFromValue.js
Labels: PR: breaking change 💥

#2912 Drop 'Array.from' polyfill
  src/execution/execute.js
  src/jsutils/isCollection.js
  src/polyfills/arrayFrom.js
  src/type/schema.js
  src/utilities/astFromValue.js
  src/utilities/coerceInputValue.js
  src/validation/rules/FieldsOnCorrectTypeRule.js
Labels: PR: breaking change 💥

#2913 Remove polyfills for Symbol
  src/error/GraphQLError.js
  src/jsutils/isAsyncIterable.js
  src/jsutils/isCollection.js
  src/language/source.js
  src/polyfills/symbols.js
  src/subscription/mapAsyncIterator.js
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
Labels: PR: breaking change 💥

#2914 Remove Node's custom inspect function
  src/jsutils/__tests__/inspect-test.js
  src/jsutils/defineInspect.js
  src/jsutils/inspect.js
  src/jsutils/nodejsCustomInspectSymbol.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/language/ast.js
  src/type/definition.js
  src/type/directives.js
Labels: PR: breaking change 💥

#2915 Drop support for TS before 3.7
  integrationTests/ts/package.json
  src/index.d.ts
Labels: PR: breaking change 💥

#2917 Drop support for non-iteratable ArrayLike objects
  src/execution/execute.js
  src/jsutils/__tests__/isCollection-test.js
  src/jsutils/__tests__/isIteratableObject-test.js
  src/jsutils/isCollection.js
  src/jsutils/isIteratableObject.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/astFromValue.js
  src/utilities/coerceInputValue.js
Labels: PR: breaking change 💥

#2918 Drop support for older browsers
  .babelrc-deno.json
  .babelrc-npm.json
  .babelrc.json
  .browserslistrc
  .eslintrc.yml
  package.json
  resources/build-npm.js
  tsconfig.json
Labels: PR: breaking change 💥

#2919 Remove polyfills for 'Object.values' & 'Object.entries'
  .flowconfig
  .nycrc.yml
  .prettierignore
  flow-typed/core.js
  flow-typed/node.js
  src/jsutils/mapValue.js
  src/jsutils/toObjMap.js
  src/polyfills/README.md
  src/polyfills/objectEntries.js
  src/polyfills/objectValues.js
  src/type/definition.js
  src/type/directives.js
  src/type/introspection.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/astFromValue.js
  src/utilities/buildClientSchema.js
  src/utilities/coerceInputValue.js
  src/utilities/extendSchema.js
  src/utilities/findBreakingChanges.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/printSchema.js
  src/utilities/valueFromAST.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
  src/validation/rules/ValuesOfCorrectTypeRule.js
Labels: PR: breaking change 💥

#2920 Deprecate fragments with variables and reflect that in naming
  src/language/__tests__/parser-test.js
  src/language/__tests__/printer-test.js
  src/language/__tests__/visitor-test.js
  src/language/ast.d.ts
  src/language/ast.js
  src/language/parser.d.ts
  src/language/parser.js
  src/language/visitor.d.ts
  src/language/visitor.js
  src/utilities/buildASTSchema.js
Labels: PR: breaking change 💥

#2921 Deprecate 'getFieldDefFn' arg of 'TypeInfo' and move it last
  src/utilities/TypeInfo.d.ts
  src/utilities/TypeInfo.js
  src/utilities/__tests__/TypeInfo-test.js
  src/validation/__tests__/validation-test.js
  src/validation/validate.d.ts
  src/validation/validate.js
Labels: PR: breaking change 💥

#2922 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2923 Drop support for Node10
  .babelrc-npm.json
  .github/workflows/ci.yml
  integrationTests/node/package.json
  package.json
Labels: PR: breaking change 💥

#2924 cspell: disable progress and convert config to YAML
  cspell.json
  cspell.yml
  package.json
Labels: PR: internal 🏠

#2928 refactor: use regexp-exec
  src/language/experimentalOnlineParser/onlineParser.js
Labels: PR: polish 💅

#2927 build: commit package-lock for drop support node10
  package-lock.json
Labels: PR: dependency 📦

#2925 TS: Enable integrations tests for extending `GraphQL*Extensions` types
  integrationTests/ts/index.ts
Labels: PR: internal 🏠

#2929 integrationTests: always build npm packages before tests
  .github/workflows/ci.yml
  package.json
Labels: PR: internal 🏠

#2930 visitor: remove `visitorKeys` argument
  src/index.d.ts
  src/index.js
  src/language/__tests__/visitor-test.js
  src/language/index.d.ts
  src/language/index.js
  src/language/visitor.d.ts
  src/language/visitor.js
Labels: PR: breaking change 💥

#2931 visit: remove template arguments for possible nodes
  src/index.d.ts
  src/index.js
  src/language/index.d.ts
  src/language/index.js
  src/language/visitor.d.ts
  src/language/visitor.js
  src/utilities/TypeInfo.d.ts
  src/utilities/TypeInfo.js
Labels: PR: breaking change 💥

#2932 print: remove indentation inside of block strings
  src/language/__tests__/blockString-fuzz.js
  src/language/__tests__/blockString-test.js
  src/language/__tests__/printer-test.js
  src/language/blockString.js
  src/language/printer.js
  src/utilities/printSchema.js
Labels: PR: feature 🚀

#2933 printer: remove 'addDescription' wrapper
  src/language/printer.js
Labels: PR: polish 💅

#2934 printer: use `wrap` util function in more places
  src/language/printer.js
Labels: PR: polish 💅

#2935 VariablesAreInputTypesRule: remove incorrect return type
  src/validation/rules/VariablesAreInputTypesRule.js
Labels: PR: polish 💅

#2936 schema-test: use chai's `keys` instead of undocumented `key`
  src/type/__tests__/schema-test.js
Labels: PR: polish 💅

#2937 validateSchema: inline 'getAllNodes' function
  src/type/validate.js
Labels: PR: polish 💅

#2938 inspect: improve typings for `toJSON` call
  src/jsutils/inspect.js
Labels: PR: polish 💅
