Repository graphql/graphql-js, pull requests merged in 2021-12, with the labels that each got.

#3393 Update doc examples to reflect the current API
  README.md
Labels: PR: docs 📝

#3398 Switch coverage from nyc to c8
  .c8rc.json
  .eslintrc.yml
  .nycrc.yml
  package-lock.json
  package.json
  resources/eslint-internal-rules/index.js
  resources/eslint-internal-rules/require-coverage-ignore-reason.js
  src/__tests__/version-test.ts
  src/error/GraphQLError.ts
  src/execution/__tests__/abstract-test.ts
  src/execution/__tests__/mapAsyncIterator-test.ts
  src/execution/__tests__/subscribe-test.ts
  src/execution/__tests__/union-interface-test.ts
  src/execution/execute.ts
  src/execution/mapAsyncIterator.ts
  src/execution/values.ts
  src/jsutils/__tests__/inspect-test.ts
  src/jsutils/__tests__/isAsyncIterable-test.ts
  src/jsutils/__tests__/isIterableObject-test.ts
  src/jsutils/devAssert.ts
  src/jsutils/instanceOf.ts
  src/jsutils/invariant.ts
  src/language/__tests__/visitor-test.ts
  src/language/printer.ts
  src/language/visitor.ts
  src/type/__tests__/definition-test.ts
  src/type/__tests__/introspection-test.ts
  src/type/introspection.ts
  src/type/validate.ts
  src/utilities/assertValidName.ts
  src/utilities/astFromValue.ts
  src/utilities/coerceInputValue.ts
  src/utilities/extendSchema.ts
  src/utilities/findBreakingChanges.ts
  src/utilities/lexicographicSortSchema.ts
  src/utilities/printSchema.ts
  src/utilities/valueFromAST.ts
  src/validation/rules/KnownArgumentNamesRule.ts
  src/validation/rules/KnownDirectivesRule.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
  src/validation/rules/PossibleTypeExtensionsRule.ts
  src/validation/rules/ProvidedRequiredArgumentsRule.ts
  src/validation/rules/UniqueArgumentDefinitionNamesRule.ts
  src/validation/rules/UniqueArgumentNamesRule.ts
  src/validation/rules/UniqueEnumValueNamesRule.ts
  src/validation/rules/UniqueFieldDefinitionNamesRule.ts
  src/validation/rules/UniqueOperationTypesRule.ts
  src/validation/rules/UniqueVariableNamesRule.ts
Labels: PR: internal 🏠

#3399 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3400 expectJSON: improve readability
  src/__testUtils__/expectJSON.ts
Labels: PR: polish 💅

#3401 tests: Improve formating of strings with 'dedent' tag
  src/language/__tests__/printer-test.ts
  src/utilities/__tests__/stripIgnoredCharacters-test.ts
Labels: PR: polish 💅

#3403 ci: add check that 'package-lock.json' doesn't have conflicts
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3404 github/workflows: simplify npm cache setup
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3405 Use for '--ignore-scripts' for all `npm ci` & `npm install`
  .github/workflows/ci.yml
  benchmark/benchmark.js
  integrationTests/integration-test.js
  package.json
  resources/diff-npm-package.js
Labels: PR: internal 🏠

#3406 Simplify code by replacing Object.entries with Object.keys
  src/jsutils/mapValue.ts
  src/utilities/lexicographicSortSchema.ts
Labels: PR: polish 💅

#3407 ci: add check for unnecessary duplicates in package-lock.json
  .github/workflows/ci.yml
  package-lock.json
Labels: PR: internal 🏠

#3410 Refine getNamedType() for Input and Output types
  src/index.d.ts
  src/index.js
  src/type/definition.d.ts
  src/type/definition.js
  src/type/index.d.ts
  src/type/index.js
Labels: PR: feature 🚀

#3411 publish 15.x.x packages only under '15.x.x' tag
  package.json
  resources/build-npm.js
Labels: PR: internal 🏠

#3412 cspell: do not show progress
  package.json
Labels: PR: internal 🏠

#3416 fix c8 ignore decorator typos
  src/__tests__/version-test.ts
  src/error/GraphQLError.ts
  src/execution/mapAsyncIterator.ts
  src/type/__tests__/introspection-test.ts
  src/utilities/assertValidName.ts
Labels: PR: internal 🏠

#3417 package.json: Specify NPM release tag explicitly
  package.json
  resources/build-npm.js
Labels: PR: internal 🏠

#3420 resources/utils: extract 'writeGeneratedFile' to utils
  resources/build-deno.js
  resources/build-npm.js
  resources/gen-version.js
  resources/utils.js
Labels: PR: internal 🏠

#3422 Minor grammar fixes in collectFields documentation
  src/execution/collectFields.ts
Labels: PR: docs 📝

#3426 type/definition: export `resolve*Thunk` functions
  src/index.ts
  src/type/definition.ts
  src/type/index.ts
Labels: PR: feature 🚀

#3427 gh/actions: run benchmark and NPM diff on correct base commits
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3423 assertName-test: test new instead of deprecated function
  .c8rc.json
  src/type/__tests__/assertName-test.ts
Labels: PR: polish 💅

#3433 gh/actions: refactor out action to deploy branches
  .eslintignore
  .github/actions/deploy-dir-as-branch/action.yml
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  resources/gitpublish.sh
Labels: PR: internal 🏠

#3434 gh/actions: remove 'npm dedupe' check since it unexpectadly do update
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3435 gh/actions: run benchmark &amp; diff-npm-package only on PRs
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3436 gh/actions: make all cloned repo read-only
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3437 CONTRIBUTING.md: remove reference to Facebook bug bounty program
  .github/CONTRIBUTING.md
Labels: PR: docs 📝

#3438 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3441 UniqueArgumentDefinitionNamesRule: Improve tests
  src/validation/__tests__/UniqueArgumentDefinitionNamesRule-test.ts
Labels: PR: polish 💅

#3443 ci/checkPackageLock: update only package-lock.json
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3444 Update deps
  package-lock.json
  package.json
Labels: PR: dependency 📦
