Repository graphql/graphql-js, pull requests merged in 2021-08, with the labels that each got.

#3209 Fix failing CI on main
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3223 Disallow "true", "false", and "null" as enum values
  src/language/__tests__/parser-test.ts
  src/language/parser.ts
Labels: PR: bug fix 🐞

#3228 Add type params to GraphQLScalar
  src/type/definition.ts
  src/type/scalars.ts
Labels: PR: breaking change 💥

#3231 execute: Forbid to return `null` from `serialize` function
  src/execution/__tests__/executor-test.ts
  src/execution/execute.ts
Labels: PR: breaking change 💥

#3240 docs(buildASTSchema): add Subscription to list of root types
  src/utilities/buildASTSchema.ts
Labels: PR: docs 📝

#3242 parser: add specialized error for extension with descriptions
  src/language/__tests__/schema-parser-test.ts
  src/language/parser.ts
Labels: PR: feature 🚀

#3252 Deprecate 'printError' function
  .eslintrc.yml
  resources/gen-changelog.js
  src/error/GraphQLError.ts
  src/error/__tests__/GraphQLError-test.ts
Labels: PR: deprecation ⚠
