Repository graphql/graphql-js, pull requests merged in 2021-09, with the labels that each got.

#3254 Parser: fix function definition of parseArguments and parseArgument
  src/language/parser.d.ts
Labels: PR: bug fix 🐞

#3259 Deprecate 'formatError' and added 'GraphQLError.toJSON' instead
  src/error/GraphQLError.ts
  src/error/__tests__/GraphQLError-test.ts
  src/error/__tests__/formatError-test.ts
  src/error/formatError.ts
  src/error/index.ts
  src/execution/execute.ts
Labels: PR: feature 🚀

#3257 fix: Preserve `deprecationReason` on `GraphQLInputField`s
  src/type/__tests__/definition-test.ts
  src/type/definition.ts
Labels: PR: bug fix 🐞

#3260 backport: Preserve `deprecationReason` on `GraphQLInputField`s
  src/type/__tests__/definition-test.js
  src/type/definition.js
Labels: PR: bug fix 🐞

#3261 Error.toStringTag change return string from 'Object' to 'GraphQLError'
  src/__testUtils__/expectJSON.ts
  src/__tests__/starWarsQuery-test.ts
  src/error/GraphQLError.ts
  src/execution/__tests__/abstract-test.ts
  src/execution/__tests__/executor-test.ts
  src/execution/__tests__/lists-test.ts
  src/execution/__tests__/mutations-test.ts
  src/execution/__tests__/nonnull-test.ts
  src/execution/__tests__/sync-test.ts
  src/execution/__tests__/variables-test.ts
  src/language/__tests__/lexer-test.ts
  src/language/__tests__/parser-test.ts
  src/language/__tests__/schema-parser-test.ts
  src/language/__tests__/toJSONDeep.ts
  src/subscription/__tests__/subscribe-test.ts
  src/type/__tests__/enumType-test.ts
  src/type/__tests__/introspection-test.ts
  src/type/__tests__/validation-test.ts
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
  src/validation/__tests__/harness.ts
  src/validation/__tests__/validation-test.ts
Labels: PR: breaking change 💥

#3255 Add TResult to GraphQLFieldResolver signature
  src/type/definition.ts
Labels: PR: feature 🚀

#3262 integrationTests: small refactoring
  integrationTests/integration-test.js
  integrationTests/node/package.json
  integrationTests/ts/package.json
  integrationTests/webpack/package.json
Labels: PR: internal 🏠

#3263 integrationTests: increase timeout to 60s
  integrationTests/integration-test.js
Labels: PR: internal 🏠

#3264 lexer: Remove superfluous statement in `readDigits`
  src/language/lexer.ts
Labels: PR: polish 💅

#3267 Depreacate 'VisitorKeyMap' and backported 'ASTVisitorKeyMap' type
  package-lock.json
  src/index.d.ts
  src/language/index.d.ts
  src/language/visitor.d.ts
Labels: PR: feature 🚀

#3270 visitor: speed up visitInParallel by dropping support for unknown nodes
  benchmark/visit-benchmark.js
  benchmark/visitInParallel-benchmark.js
  src/index.ts
  src/language/__tests__/visitor-test.ts
  src/language/index.ts
  src/language/visitor.ts
  src/utilities/TypeInfo.ts
Labels: PR: breaking change 💥

#3271 isNode: check exact value of node's `kind`
  src/language/ast.ts
  src/language/visitor.ts
Labels: PR: breaking change 💥

#3272 collectFields/collectSubfields cleanup prototype
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/subscription/subscribe.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
Labels: PR: feature 🚀

#3273 type/introspection: add missing `__Directive.args(includeDeprecated:)`
  src/type/__tests__/introspection-test.ts
  src/type/introspection.ts
  src/utilities/__tests__/getIntrospectionQuery-test.ts
  src/utilities/__tests__/printSchema-test.ts
Labels: PR: bug fix 🐞

#3275 type/introspection: add missing `__Directive.args(includeDeprecated:)`
  src/type/__tests__/introspection-test.js
  src/type/introspection.js
  src/utilities/__tests__/getIntrospectionQuery-test.js
  src/utilities/__tests__/printSchema-test.js
Labels: PR: bug fix 🐞

#3276 Update deps
  .eslintrc.yml
  integrationTests/ts/package.json
  package-lock.json
  package.json
  tsconfig.json
Labels: PR: dependency 📦

#3277 ESLint: enable some of the rules previously blocked by TS conversion
  .eslintrc.yml
  src/language/blockString.ts
  src/language/visitor.ts
  src/utilities/assertValidName.ts
  src/utilities/stripIgnoredCharacters.ts
  src/utilities/typedQueryDocumentNode.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
Labels: PR: polish 💅

#3279 Make 'extensions' non-optional in schema types
  integrationTests/ts/index.ts
  src/jsutils/__tests__/toObjMap-test.ts
  src/jsutils/toObjMap.ts
  src/type/__tests__/definition-test.ts
  src/type/__tests__/directive-test.ts
  src/type/__tests__/enumType-test.ts
  src/type/__tests__/extensions-test.ts
  src/type/__tests__/predicate-test.ts
  src/type/definition.ts
  src/type/directives.ts
  src/type/introspection.ts
  src/type/schema.ts
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/buildASTSchema.ts
  src/utilities/extendSchema.ts
Labels: PR: feature 🚀

#3280 integrationTests/ts: split tests into separate files
  integrationTests/ts/TypedQueryDocumentNode-test.ts
  integrationTests/ts/basic-test.ts
  integrationTests/ts/extensions-test.ts
  integrationTests/ts/index.ts
Labels: PR: internal 🏠
