Repository graphql/graphql-js, pull requests merged in 2021-01, with the labels that each got.

#2879 fix: no need to mark param optional if default value is given
  src/language/blockString.js
  src/utilities/coerceInputValue.js
  src/validation/validate.js
Labels: PR: polish 💅

#2876 Replace 'localeCompare' with function independent from locale
  src/jsutils/__tests__/naturalCompare-test.js
  src/jsutils/naturalCompare.js
  src/jsutils/suggestionList.js
  src/utilities/findBreakingChanges.js
  src/utilities/lexicographicSortSchema.js
  src/validation/rules/FieldsOnCorrectTypeRule.js
Labels: PR: bug fix 🐞

#2884 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
  src/utilities/lexicographicSortSchema.js
Labels: PR: dependency 📦

#2886 Use correct flags for rmdir/mkdir functions
  benchmark/benchmark.js
  integrationTests/integration-test.js
  resources/build-deno.js
  resources/build-npm.js
  resources/utils.js
Labels: PR: internal 🏠

#2889 Simplify isAsyncIterable
  src/jsutils/isAsyncIterable.js
Labels: PR: polish 💅

#2890 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2891 benchmark: fix temp dir creation
  benchmark/benchmark.js
Labels: PR: internal 🏠

#2893 Fix handling of input objects with 'length' property
  src/execution/execute.js
  src/jsutils/__tests__/isCollection-test.js
  src/jsutils/__tests__/safeArrayFrom-test.js
  src/jsutils/isCollection.js
  src/jsutils/safeArrayFrom.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/astFromValue.js
  src/utilities/coerceInputValue.js
Labels: PR: bug fix 🐞

#2881 ci: migrate master to main
  .github/workflows/ci.yml
  README.md
  resources/checkgit.sh
  resources/gitpublish.sh
Labels: PR: internal 🏠

#2896 Remove deprecated rule aliases
  .nycrc.yml
  src/validation/rules/ExecutableDefinitions.d.ts
  src/validation/rules/ExecutableDefinitions.js
  src/validation/rules/LoneSchemaDefinition.d.ts
  src/validation/rules/LoneSchemaDefinition.js
  src/validation/rules/PossibleTypeExtensions.d.ts
  src/validation/rules/PossibleTypeExtensions.js
  src/validation/rules/UniqueDirectiveNames.d.ts
  src/validation/rules/UniqueDirectiveNames.js
  src/validation/rules/UniqueEnumValueNames.d.ts
  src/validation/rules/UniqueEnumValueNames.js
  src/validation/rules/UniqueFieldDefinitionNames.d.ts
  src/validation/rules/UniqueFieldDefinitionNames.js
  src/validation/rules/UniqueOperationTypes.d.ts
  src/validation/rules/UniqueOperationTypes.js
  src/validation/rules/UniqueTypeNames.d.ts
  src/validation/rules/UniqueTypeNames.js
Labels: PR: breaking change 💥

#2897 Remove 'findDeprecatedUsages' that was previously deprecated
  .nycrc.yml
  src/index.d.ts
  src/index.js
  src/utilities/findDeprecatedUsages.d.ts
  src/utilities/findDeprecatedUsages.js
  src/utilities/index.d.ts
  src/utilities/index.js
Labels: PR: breaking change 💥

#2898 Remove 'GraphQLSchema::isPossibleType' that was previously deprecated
  src/type/__tests__/schema-test.js
  src/type/schema.d.ts
  src/type/schema.js
Labels: PR: breaking change 💥

#2900 Drop support for long deprecated comments as descriptions
  src/index.d.ts
  src/index.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/printSchema-test.js
  src/utilities/buildASTSchema.d.ts
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.d.ts
  src/utilities/extendSchema.js
  src/utilities/index.d.ts
  src/utilities/index.js
  src/utilities/printSchema.d.ts
  src/utilities/printSchema.js
Labels: PR: breaking change 💥

#2902 Remove deprecated {GraphQLEnumValue, GraphQLField}::isDeprecated
  src/type/__tests__/definition-test.js
  src/type/__tests__/enumType-test.js
  src/type/definition.d.ts
  src/type/definition.js
  src/type/introspection.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: breaking change 💥

#2903 Removed parser support for legacy syntax
  src/language/__tests__/schema-parser-test.js
  src/language/parser.d.ts
  src/language/parser.js
  src/utilities/buildASTSchema.js
Labels: PR: breaking change 💥
