Repository graphql/graphql-js, pull requests merged in 2021-03, with the labels that each got.

#2947 valueFromAST-test: correct typings
  src/utilities/__tests__/valueFromAST-test.js
Labels: PR: polish 💅

#2948 scalars-test: improve typings of function calls
  src/type/__tests__/scalars-test.js
Labels: PR: polish 💅

#2951 Forbid null & undefined as return value of 'interfaces' thunk
  src/type/definition.d.ts
  src/type/definition.js
Labels: PR: breaking change 💥

#2953 type-validate: inline getAllNodes function
  src/type/validate.js
Labels: PR: polish 💅

#2956 buildClientSchema-test: correctly wrap test case
  src/utilities/__tests__/buildClientSchema-test.js
Labels: PR: polish 💅

#2957 visitor: remove 4th form of visitor
  src/language/__tests__/visitor-test.js
  src/language/printer.js
  src/language/visitor.d.ts
  src/language/visitor.js
Labels: PR: breaking change 💥

#2959 ASTVisitor: use type intersection instead of type union
  src/language/visitor.d.ts
  src/language/visitor.js
Labels: PR: bug fix 🐞

#2955 feat: convert Thunk to ThunkArray and ThunkObjMap
  src/index.d.ts
  src/index.js
  src/jsutils/ObjMap.d.ts
  src/type/definition.d.ts
  src/type/definition.js
  src/type/index.d.ts
  src/type/index.js
Labels: PR: breaking change 💥

#2960 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#2961 flow-typed: update Mocha typings
  flow-typed/npm/mocha_vx.x.x.js
Labels: PR: dependency 📦

#2962 flow-typed: fix unresolved types
  flow-typed/intl.js
  flow-typed/node.js
Labels: PR: internal 🏠

#2963 printer: simplify printing of query short form
  src/language/printer.js
Labels: PR: polish 💅

#2964 Simplified memoize3 and improve type checking
  src/jsutils/memoize3.js
Labels: PR: polish 💅

#2965 parser: improve type checking of 'parseTypeReference' function
  src/language/parser.js
Labels: PR: polish 💅

#2966 blockString-fuzz: improve `lexValue` typing
  src/language/__tests__/blockString-fuzz.js
Labels: PR: polish 💅

#2967 flow: improve typings of exported definitions
  src/type/directives.js
  src/type/introspection.js
  src/type/scalars.js
Labels: PR: polish 💅

#2968 ESLint: Allow 'async' functions
  .eslintrc.yml
Labels: PR: internal 🏠

#2969 ESLint: cleanup rule overrides
  .eslintrc.yml
Labels: PR: internal 🏠

#2970 Remove override of `node/global-require` rule for `resources` dir
  .eslintrc.yml
  resources/build-npm.js
  resources/eslint-internal-rules/index.js
Labels: PR: internal 🏠

#2971 benchmark: refactor args parsing code
  benchmark/benchmark.js
Labels: PR: internal 🏠

#2972 Remove deprecated `rmdirSync` usage from internal scripts
  integrationTests/integration-test.js
  resources/build-npm.js
Labels: PR: internal 🏠

#2977 dedent-test: change test data to pass spell check
  src/__testUtils__/__tests__/dedent-test.js
Labels: PR: polish 💅

#2978 internal: simplify 'exec' function
  benchmark/benchmark.js
  integrationTests/integration-test.js
  resources/utils.js
Labels: PR: internal 🏠

#2981 printSourceLocation: simplifying by using `padStart`
  src/language/printLocation.js
Labels: PR: polish 💅

#2982 benchmark: use more readable spelling of V8 flag
  benchmark/benchmark.js
  cspell.yml
Labels: PR: internal 🏠

#2987 Synchronise TS typings for graphql.js/execute.js/subscribe.js
  src/execution/execute.d.ts
  src/graphql.d.ts
  src/subscription/subscribe.d.ts
Labels: PR: bug fix 🐞

#2988 Replace 'Array.reduce' with 'for of'
  src/error/GraphQLError.js
  src/jsutils/keyMap.js
  src/jsutils/keyValMap.js
  src/jsutils/promiseForObject.js
  src/language/experimentalOnlineParser/onlineParser.js
  src/validation/ValidationContext.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
Labels: PR: polish 💅

#2989 Switch `indexOf` to `includes` whenever possible
  src/jsutils/inspect.js
  src/language/blockString.js
  src/language/printer.js
  src/type/validate.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/utilities/findBreakingChanges.js
  src/validation/rules/KnownArgumentNamesRule.js
  src/validation/rules/KnownDirectivesRule.js
  src/validation/rules/KnownTypeNamesRule.js
Labels: PR: polish 💅

#2990 Switch instanceOf to be named export
  src/jsutils/__tests__/instanceOf-test.js
  src/jsutils/instanceOf.js
  src/language/source.js
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
Labels: PR: polish 💅

#2992 flow: Improve typings for exported definitions
  src/validation/__tests__/harness.js
  src/validation/specifiedRules.js
Labels: PR: polish 💅

#2993 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
  src/execution/execute.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: dependency 📦

#2995 introspection-test: fix test to correctly check for exceptions
  src/type/__tests__/introspection-test.js
Labels: PR: polish 💅

#2996 extensionASTNodes: always populate with empty array
  src/type/definition.d.ts
  src/type/definition.js
  src/type/schema.d.ts
  src/type/schema.js
  src/type/validate.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: feature 🚀

#2997 print/printSchema: remove trailing new line
  src/__testUtils__/__tests__/dedent-test.js
  src/__testUtils__/dedent.js
  src/error/__tests__/GraphQLError-test.js
  src/language/__tests__/lexer-test.js
  src/language/__tests__/parser-test.js
  src/language/__tests__/printLocation-test.js
  src/language/__tests__/schema-parser-test.js
  src/language/printer.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/stripIgnoredCharacters-test.js
  src/utilities/printSchema.js
Labels: PR: breaking change 💥

#2998 Simplify testing AST nodes in buildSchema/extendedSchema tests
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
Labels: PR: polish 💅

#2999 tests: replace 'invariant' with 'expect' assertion whenever possible
  src/execution/__tests__/union-interface-test.js
  src/execution/__tests__/variables-test.js
  src/jsutils/__tests__/inspect-test.js
  src/language/__tests__/visitor-test.js
  src/type/__tests__/introspection-test.js
Labels: PR: polish 💅

#3001 fix: discrepancies between Flow and TS types
  src/language/blockString.d.ts
  src/language/directiveLocation.d.ts
  src/language/kinds.d.ts
  src/language/lexer.d.ts
  src/language/source.d.ts
  src/language/tokenKind.d.ts
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/type/introspection.d.ts
  src/type/schema.d.ts
  src/utilities/TypeInfo.d.ts
  src/validation/validate.d.ts
Labels: PR: bug fix 🐞

#3004 GraphQLGrammarType: no need to code in `d.ts` can just export type
  src/language/experimentalOnlineParser/grammar.d.ts
Labels: PR: polish 💅

#3003 TS: use `unknown` (TS) for `mixed` (flow)
  src/error/GraphQLError.d.ts
  src/error/formatError.d.ts
  src/error/locatedError.d.ts
  src/execution/execute.d.ts
  src/execution/values.d.ts
  src/graphql.d.ts
  src/language/ast.d.ts
  src/language/source.d.ts
  src/subscription/subscribe.d.ts
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/type/introspection.d.ts
  src/type/schema.d.ts
  src/utilities/TypeInfo.d.ts
  src/utilities/astFromValue.d.ts
  src/utilities/coerceInputValue.d.ts
  src/utilities/valueFromAST.d.ts
  src/utilities/valueFromASTUntyped.d.ts
  src/validation/ValidationContext.d.ts
Labels: PR: breaking change 💥

#3002 feat: add types for internal Parser class
  src/language/parser.d.ts
Labels: PR: polish 💅

#3005 ts: switch to use ObjMap utility type
  src/execution/execute.d.ts
  src/execution/values.d.ts
  src/type/definition.d.ts
  src/type/schema.d.ts
  src/utilities/separateOperations.d.ts
  src/utilities/valueFromAST.d.ts
  src/utilities/valueFromASTUntyped.d.ts
Labels: PR: polish 💅

#3006 ts: Switch extension values to unknown to match Flow types
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/type/schema.d.ts
Labels: PR: breaking change 💥

#3008 ESLint: enable 'func-names'
  .eslintrc.yml
  resources/eslint-internal-rules/no-dir-import.js
  src/jsutils/__tests__/inspect-test.js
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#3009 TS: use proper type for async generator
  integrationTests/ts/tsconfig.json
  src/subscription/mapAsyncIterator.d.ts
  src/subscription/subscribe.d.ts
Labels: PR: bug fix 🐞
