Repository graphql/graphql-js, pull requests merged in 2021-06, with the labels that each got.

#3151 CI: Add new job to check health of package-lock.json
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3154 tsconfig.json: enable 'isolatedModules'
  src/utilities/index.ts
  tsconfig.json
Labels: PR: internal 🏠

#2975 fix(race): concurrent next calls with defer/stream
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
Labels: stream/defer

#3115 Refactor Lexer
  src/language/__tests__/lexer-test.ts
  src/language/ast.ts
  src/language/lexer.ts
  src/language/parser.ts
Labels: PR: polish 💅

#3157 package.json: fix generating release commit
  package.json
Labels: PR: internal 🏠

#3160 versions-test: add support for experimental pre-releases
  src/__tests__/version-test.ts
Labels: PR: polish 💅

#3159 execute: Rename resolveField function and update comments
  src/execution/execute.ts
Labels: PR: polish 💅

#3161 build-npm: correctly set NPM tag on experimental pre-releases
  resources/build-npm.js
Labels: PR: internal 🏠

#3166 SingleFieldSubscriptionsRule-test: extract test schema from harness
  src/validation/__tests__/SingleFieldSubscriptionsRule-test.ts
  src/validation/__tests__/harness.ts
Labels: PR: polish 💅

#3167 SingleFieldSubscriptionsRule: fix order of imports
  src/validation/rules/SingleFieldSubscriptionsRule.ts
Labels: PR: polish 💅

#3158 allows passing --watch to npm run testonly
  .mocharc.yml
Labels: PR: internal 🏠

#3170 Add 'Symbol.toStringTag' into every publicly exported class
  .eslintrc.yml
  resources/eslint-internal-rules/index.js
  resources/eslint-internal-rules/require-to-string-tag.js
  src/language/__tests__/lexer-test.ts
  src/language/__tests__/parser-test.ts
  src/language/ast.ts
  src/language/lexer.ts
  src/utilities/TypeInfo.ts
  src/utilities/__tests__/TypeInfo-test.ts
  src/validation/ValidationContext.ts
  src/validation/__tests__/ValidationContext-test.ts
Labels: PR: feature 🚀

#3172 Avoid relying on constructor.name for instanceOf error check.
  src/jsutils/__tests__/instanceOf-test.ts
  src/jsutils/instanceOf.ts
Labels: PR: bug fix 🐞

#3173 fix: broken link to prettier rules
  .eslintrc.yml
Labels: PR: internal 🏠

#3174 ci: use update 'actions/setup-node' to v2
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3175 TypeInfo-test: remove dependency on harness schema for validation tests
  src/utilities/__tests__/TypeInfo-test.ts
Labels: PR: polish 💅

#3176 KnownDirectivesRule-test: remove dependency on harness schema
  src/validation/__tests__/KnownDirectivesRule-test.ts
  src/validation/__tests__/harness.ts
Labels: PR: polish 💅

#3177 kitchenSinkQuery: add '@onVariableDefinition' directive
  src/__testUtils__/kitchenSinkQuery.ts
  src/language/__tests__/printer-test.ts
  src/language/__tests__/visitor-test.ts
Labels: PR: polish 💅

#3179 KnownDirectivesRule-test: add tests for missing directive locations
  src/validation/__tests__/KnownDirectivesRule-test.ts
Labels: PR: polish 💅

#3180 simplify validation harness by extracting union types into approriate…
  src/validation/__tests__/FieldsOnCorrectTypeRule-test.ts
  src/validation/__tests__/PossibleFragmentSpreadsRule-test.ts
  src/validation/__tests__/harness.ts
  src/validation/__tests__/validation-test.ts
Labels: PR: polish 💅

#3181 Switch tests & internal funcs to accept ReadonlyArrays
  src/__testUtils__/__tests__/genFuzzStrings-test.ts
  src/__testUtils__/genFuzzStrings.ts
  src/__tests__/starWarsData.ts
  src/execution/__tests__/lists-test.ts
  src/execution/__tests__/union-interface-test.ts
  src/execution/execute.ts
  src/jsutils/__tests__/suggestionList-test.ts
  src/jsutils/inspect.ts
  src/language/__tests__/blockString-test.ts
  src/type/__tests__/validation-test.ts
  src/utilities/findBreakingChanges.ts
  src/utilities/separateOperations.ts
Labels: PR: polish 💅

#3182 Switch schema types to use ReadonlyArrays
  src/index.ts
  src/type/definition.ts
  src/type/directives.ts
  src/type/index.ts
  src/type/schema.ts
  src/utilities/buildASTSchema.ts
Labels: PR: breaking change 💥

#3178 Export TypeKind as value
  src/type/index.ts
Labels: PR: bug fix 🐞

#3187 refactor: collectFields to separate utility
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/subscription/subscribe.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
Labels: PR: polish 💅

#3188 integrationTests: Add test for webpack
  .eslintrc.yml
  integrationTests/integration-test.js
  integrationTests/webpack/entry.js
  integrationTests/webpack/package.json
  integrationTests/webpack/test.js
  integrationTests/webpack/webpack.config.json
Labels: PR: internal 🏠

#3189 instanceOf: add additional tests
  src/jsutils/__tests__/instanceOf-test.ts
Labels: PR: polish 💅

#3186 Backport instanceOf Error Check Improvements
  src/jsutils/__tests__/instanceOf-test.js
  src/jsutils/instanceOf.js
Labels: PR: bug fix 🐞

#3190 build-npm: fix assert message about not supported tag
  resources/build-npm.js
Labels: PR: internal 🏠

#3191 Remove deprecated rmdirSync usage from internal scripts
  benchmark/benchmark.js
  integrationTests/integration-test.js
  resources/build-deno.js
  resources/build-npm.js
Labels: PR: internal 🏠

#3194 Replace 'Idx' with 'Index' in variable names
  benchmark/benchmark.js
  src/jsutils/naturalCompare.ts
Labels: PR: polish 💅

#3206 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3146 build: add eslint-plugin-tsdoc
  .eslintrc.yml
  package-lock.json
  package.json
  src/__testUtils__/dedent.ts
  src/__tests__/starWarsSchema.ts
  src/error/GraphQLError.ts
  src/error/formatError.ts
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/index.ts
  src/jsutils/isIterableObject.ts
  src/jsutils/keyMap.ts
  src/jsutils/keyValMap.ts
  src/language/lexer.ts
  src/language/parser.ts
  src/language/printer.ts
  src/language/visitor.ts
  src/type/definition.ts
  src/type/schema.ts
  src/utilities/printSchema.ts
  src/utilities/stripIgnoredCharacters.ts
  src/validation/validate.ts
Labels: PR: docs 📝
