Repository graphql/graphql-js, pull requests merged in 2021-05, with the labels that each got.

#3043 Fix Flow issues with Symbol.asyncIterator
  flow-typed/core.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/simplePubSub-test.js
  src/subscription/__tests__/simplePubSub.js
  src/subscription/__tests__/subscribe-test.js
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#3053 Forbid non-ASCII characters in JS files
  .eslintrc.yml
  benchmark/benchmark.js
  resources/eslint-internal-rules/index.js
  resources/eslint-internal-rules/only-ascii.js
  resources/eslint-internal-rules/package.json
  src/language/__tests__/lexer-test.js
Labels: PR: polish 💅

#3054 Test with Node v16
  .github/workflows/ci.yml
  integrationTests/node/package.json
  package.json
  resources/build-deno.js
Labels: PR: internal 🏠

#3055 Drop Node v15
  .github/workflows/ci.yml
  integrationTests/node/package.json
  package.json
Labels: PR: breaking change 💥

#3057 Update deps
  .eslintrc.yml
  .flowconfig
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3058 subscribe-test: general cleanup and simplify test setups
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#3062 mapAsyncIterator: refactor async iterator
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#3064 mapAsyncIterator: refactor async iterator
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#3066 mapAsyncIterator-test: check that return value is passed on early return
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/mapAsyncIterator.js
Labels: PR: polish 💅

#3069 subscription-test: use separate dummy query type
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#3070 subscription-test: standardize generator names
  src/subscription/__tests__/subscribe-test.js
Labels: PR: polish 💅

#3072 Flow: add missing names to arguments of function types
  src/execution/values.js
  src/jsutils/instanceOf.js
  src/jsutils/memoize3.js
  src/jsutils/promiseReduce.js
  src/language/__tests__/predicates-test.js
  src/language/visitor.js
  src/subscription/__tests__/mapAsyncIterator-test.js
  src/subscription/__tests__/simplePubSub.js
  src/subscription/mapAsyncIterator.js
  src/type/validate.js
  src/utilities/lexicographicSortSchema.js
  src/validation/ValidationContext.js
Labels: PR: polish 💅

#3073 Improve naming 'err => error' and 'arr => array'
  src/utilities/lexicographicSortSchema.js
  src/validation/ValidationContext.d.ts
  src/validation/ValidationContext.js
  src/validation/__tests__/validation-test.js
Labels: PR: polish 💅

#3078 babel: Stop transpiling optional chaining operator
  .babelrc.json
  src/type/validate.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/__tests__/getOperationRootType-test.js
Labels: PR: internal 🏠

#3079 dedent: simplify implementation
  src/__testUtils__/dedent.js
  src/utilities/__tests__/printSchema-test.js
Labels: PR: polish 💅

#3080 Workaround for Flow issue with 'String.raw'
  flow-typed/core.js
  src/__testUtils__/kitchenSinkQuery.js
  src/language/__tests__/printer-test.js
  src/utilities/__tests__/printSchema-test.js
Labels: PR: internal 🏠

#3081 Flow: Replace force type conversion with explicit $FlowFixMe comments
  src/error/GraphQLError.js
  src/error/__tests__/locatedError-test.js
  src/error/locatedError.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/executor-test.js
  src/jsutils/__tests__/inspect-test.js
  src/language/__tests__/predicates-test.js
  src/language/lexer.js
  src/language/parser.js
  src/utilities/__tests__/buildClientSchema-test.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
  src/utilities/findBreakingChanges.js
  src/utilities/introspectionFromSchema.js
  src/utilities/lexicographicSortSchema.js
Labels: PR: polish 💅

#3082 collectFields: use ES6 collections instead of Object.create(null)
  src/execution/execute.js
  src/jsutils/promiseReduce.js
  src/subscription/subscribe.js
Labels: PR: polish 💅

#3083 execute: inline collectAndExecuteSubfields function
  src/execution/execute.js
Labels: PR: polish 💅

#3084 getFieldDef: accept FieldNode instead of field name
  src/execution/execute.js
  src/subscription/subscribe.js
Labels: PR: polish 💅

#3089 Flow: use semicolon as separate inside types
  src/__testUtils__/__tests__/genFuzzStrings-test.js
  src/__testUtils__/genFuzzStrings.js
  src/__tests__/starWarsData.js
  src/error/GraphQLError.js
  src/error/formatError.js
  src/execution/__tests__/abstract-test.js
  src/execution/__tests__/lists-test.js
  src/execution/__tests__/variables-test.js
  src/execution/execute.js
  src/execution/values.js
  src/graphql.js
  src/jsutils/ObjMap.js
  src/jsutils/Path.js
  src/jsutils/instanceOf.js
  src/language/__tests__/source-test.js
  src/language/ast.js
  src/language/location.js
  src/language/parser.js
  src/language/source.js
  src/language/visitor.js
  src/subscription/__tests__/subscribe-test.js
  src/subscription/subscribe.js
  src/type/__tests__/enumType-test.js
  src/type/__tests__/predicate-test.js
  src/type/definition.js
  src/type/directives.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/__tests__/buildASTSchema-test.js
  src/utilities/__tests__/coerceInputValue-test.js
  src/utilities/__tests__/extendSchema-test.js
  src/utilities/buildASTSchema.js
  src/utilities/extendSchema.js
  src/utilities/findBreakingChanges.js
  src/utilities/getIntrospectionQuery.js
  src/utilities/lexicographicSortSchema.js
  src/utilities/printSchema.js
  src/validation/ValidationContext.js
  src/validation/rules/UniqueFieldDefinitionNamesRule.js
Labels: PR: polish 💅

#3091 TS Migration: enable tests and remove flow infra
  .babelrc-deno.json
  .babelrc-npm.json
  .babelrc.json
  .eslintignore
  .eslintrc.yml
  .flowconfig
  .github/CONTRIBUTING.md
  .github/workflows/ci.yml
  .mocharc.yml
  .prettierignore
  cspell.yml
  flow-typed/core.js
  flow-typed/intl.js
  flow-typed/node.js
  flow-typed/npm/chai_vx.x.x.js
  flow-typed/npm/mocha_vx.x.x.js
  integrationTests/flow/.flowconfig
  integrationTests/flow/index.mjs
  integrationTests/flow/package.json
  integrationTests/integration-test.js
  package-lock.json
  package.json
  resources/build-deno.js
  resources/build-npm.js
  resources/check-cycles.js
  resources/ts-register.js
  src/jsutils/__tests__/toObjMap-test.ts
  src/subscription/__tests__/mapAsyncIterator-test.ts
  tsconfig.json
Labels: PR: internal 🏠

#3094 Update prettier to 2.3
  benchmark/benchmark.js
  integrationTests/ts/index.ts
  package-lock.json
  package.json
  resources/gen-changelog.js
  src/error/formatError.d.ts
  src/execution/execute.d.ts
  src/execution/execute.js
  src/jsutils/memoize3.d.ts
  src/language/directiveLocation.d.ts
  src/type/definition.d.ts
  src/type/definition.js
  src/type/directives.js
  src/type/introspection.js
  src/type/scalars.js
  src/type/schema.js
  src/type/validate.js
  src/utilities/__tests__/getOperationRootType-test.js
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/typedQueryDocumentNode.d.ts
  src/validation/rules/FieldsOnCorrectTypeRule.js
  src/validation/specifiedRules.js
Labels: PR: dependency 📦

#3096 Flow: Remove inferrable types
  src/__testUtils__/kitchenSinkSDL.js
  src/jsutils/__tests__/toObjMap-test.js
Labels: PR: polish 💅

#3097 Flow: use only type imports for importing types
  src/type/schema.js
  src/validation/__tests__/harness.js
Labels: PR: polish 💅

#3098 mapAsyncIterator: simplify test case
  src/subscription/__tests__/mapAsyncIterator-test.js
Labels: PR: polish 💅

#3099 OverlappingFieldsCanBeMergedRule: refactor 'PairSet'
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
Labels: PR: polish 💅

#3100 Flow: add missing arg name in function type
  src/language/__tests__/predicates-test.js
Labels: PR: polish 💅

#3101 Flow: remove unnecessary '%checks'
  src/language/lexer.js
  src/type/definition.js
Labels: PR: polish 💅

#3102 eslintrc: fix spelling mistake in comment
  .eslintrc.yml
Labels: PR: internal 🏠

#3103 ESLint: fix config for '@typescript-eslint/no-throw-literal'
  .eslintrc.yml
Labels: PR: internal 🏠

#3105 getLocation: use more explicit `matchAll` instead of `RegExp.exec`
  .eslintrc.yml
  src/language/location.js
Labels: PR: polish 💅

#3108 OverlappingFieldsCanBeMergedRule: futher simplify 'PairSet'
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
Labels: PR: polish 💅

#3112 gen-version: fix notice comment was polluting 'version.d.ts'
  resources/gen-version.js
  src/version.js
Labels: PR: internal 🏠

#3114 Drop support for TS 3.7
  integrationTests/ts/package.json
  integrationTests/ts/tsconfig.json
Labels: PR: breaking change 💥

#3121 `*.d.ts`: Switch comments to comment to TSDoc
  src/index.d.ts
  src/index.js
  src/jsutils/Maybe.d.ts
  src/language/ast.d.ts
  src/language/ast.js
  src/language/directiveLocation.d.ts
  src/language/directiveLocation.js
  src/language/index.d.ts
  src/language/index.js
  src/language/kinds.d.ts
  src/language/kinds.js
  src/type/definition.d.ts
  src/type/definition.js
  src/type/index.d.ts
  src/type/index.js
  src/utilities/TypeInfo.d.ts
  src/utilities/TypeInfo.js
  src/utilities/getIntrospectionQuery.d.ts
  src/utilities/getIntrospectionQuery.js
  src/utilities/index.d.ts
  src/utilities/index.js
  src/validation/index.d.ts
  src/validation/index.js
  src/validation/validate.d.ts
  src/validation/validate.js
Labels: PR: docs 📝

#3122 valueFromAST: drop unnecessary 'void' since `mixed` already includes it
  src/utilities/valueFromAST.js
Labels: PR: polish 💅

#3123 visitor: convert arguments descriptions to JSDoc comments
  src/language/visitor.js
Labels: PR: polish 💅

#3124 src/type: correct order of import/exports
  src/type/definition.js
  src/type/index.js
Labels: PR: polish 💅

#3125 TypeInfo: use explicit type for `getFieldDef` arg
  src/utilities/TypeInfo.d.ts
  src/utilities/TypeInfo.js
Labels: PR: polish 💅

#3126 Restrict TS to files inside `src`
  tsconfig.json
Labels: PR: internal 🏠

#3127 Disable '@typescript-eslint/prefer-readonly'
  .eslintrc.yml
Labels: PR: internal 🏠

#3128 definition: Remove deprecation comment
  src/type/definition.js
Labels: PR: polish 💅

#3129 definition.d.ts: correct types
  src/type/definition.d.ts
Labels: PR: bug fix 🐞

#3130 coerceInputValue: add missing argument in function call
  src/utilities/coerceInputValue.js
Labels: PR: polish 💅

#3131 TS: Drop template argument from GraphQLFormattedError
  src/error/formatError.d.ts
Labels: PR: breaking change 💥

#3132 Synchronise `*.d.ts` with sources converted to TS
  src/error/GraphQLError.d.ts
  src/error/formatError.d.ts
  src/error/index.d.ts
  src/error/locatedError.d.ts
  src/error/syntaxError.d.ts
  src/execution/execute.d.ts
  src/execution/index.d.ts
  src/execution/values.d.ts
  src/graphql.d.ts
  src/index.d.ts
  src/jsutils/ObjMap.d.ts
  src/jsutils/Path.d.ts
  src/jsutils/instanceOf.d.ts
  src/jsutils/isObjectLike.d.ts
  src/jsutils/promiseReduce.d.ts
  src/language/ast.d.ts
  src/language/blockString.d.ts
  src/language/directiveLocation.d.ts
  src/language/index.d.ts
  src/language/kinds.d.ts
  src/language/lexer.d.ts
  src/language/parser.d.ts
  src/language/printLocation.d.ts
  src/language/tokenKind.d.ts
  src/language/visitor.d.ts
  src/subscription/index.d.ts
  src/subscription/mapAsyncIterator.d.ts
  src/subscription/subscribe.d.ts
  src/type/definition.d.ts
  src/type/directives.d.ts
  src/type/index.d.ts
  src/type/introspection.d.ts
  src/type/scalars.d.ts
  src/type/schema.d.ts
  src/type/validate.d.ts
  src/utilities/TypeInfo.d.ts
  src/utilities/assertValidName.d.ts
  src/utilities/astFromValue.d.ts
  src/utilities/buildASTSchema.d.ts
  src/utilities/buildClientSchema.d.ts
  src/utilities/coerceInputValue.d.ts
  src/utilities/concatAST.d.ts
  src/utilities/extendSchema.d.ts
  src/utilities/findBreakingChanges.d.ts
  src/utilities/index.d.ts
  src/utilities/lexicographicSortSchema.d.ts
  src/utilities/stripIgnoredCharacters.d.ts
  src/utilities/typeFromAST.d.ts
  src/utilities/valueFromAST.d.ts
  src/utilities/valueFromASTUntyped.d.ts
  src/validation/ValidationContext.d.ts
  src/validation/index.d.ts
  src/validation/rules/KnownArgumentNamesRule.d.ts
  src/validation/rules/NoFragmentCyclesRule.d.ts
  src/validation/rules/NoUnusedFragmentsRule.d.ts
  src/validation/rules/UniqueDirectivesPerLocationRule.d.ts
  src/validation/validate.d.ts
  src/version.d.ts
Labels: PR: breaking change 💥

#3144 ESLint: fail `npm run lint` if any warnings are reported
  package.json
Labels: PR: internal 🏠

#3149 Update deps
  .eslintrc.yml
  integrationTests/ts/package.json
  package-lock.json
  package.json
  resources/build-deno.js
  resources/build-npm.js
  resources/eslint-internal-rules/index.js
  resources/gen-changelog.js
  src/jsutils/__tests__/suggestionList-test.ts
Labels: PR: dependency 📦
