Repository graphql/graphql-js, pull requests merged in 2022-01, with the labels that each got.

#3447 Fix index.ts files to be compatible with Typedoc
  src/index.ts
  src/language/index.ts
  src/type/index.ts
  src/utilities/getIntrospectionQuery.ts
  src/utilities/index.ts
  src/validation/index.ts
Labels: PR: polish 💅

#3442 Prevent Infinite Loop in OverlappingFieldsCanBeMergedRule
  src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Labels: PR: bug fix 🐞

#3452 validation-test.ts: various grammar fixes
  src/type/__tests__/validation-test.ts
Labels: PR: polish 💅

#3455 OverlappingFieldsCanBeMerged: sort argument values before comparing
  src/utilities/__tests__/sortValueNode-test.ts
  src/utilities/findBreakingChanges.ts
  src/utilities/sortValueNode.ts
  src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Labels: PR: bug fix 🐞

#3459 blockString-tests: remove duplicate test, fix grammar
  src/language/__tests__/blockString-test.ts
Labels: PR: polish 💅

#3457 OverlappingFieldsCanBeMergedRule: simplify argument comparison
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Labels: PR: polish 💅

#3454 feat: allow providing an object to the GraphQLError constructor
  src/error/GraphQLError.ts
  src/error/__tests__/GraphQLError-test.ts
Labels: PR: feature 🚀

#3461 visit: simplify handling of root node
  src/language/visitor.ts
Labels: PR: polish 💅

#3462 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3463 Update deps + fix 'npm audit'
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3464 Expose `getArgumentValues` as public API
  src/execution/index.ts
  src/execution/values.ts
  src/index.ts
Labels: PR: feature 🚀
