Repository graphql/graphql-js, pull requests merged in 2022-02, with the labels that each got.

#3468 ci: add stub action for canary releases on PRs
  .github/workflows/canary.yaml
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3470 ci: implement canary releases on PRs
  .github/workflows/canary.yaml
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3472 ci: remove NPM caching on canary release script
  .github/workflows/canary.yaml
Labels: PR: internal 🏠

#3473 ci: Pass 'GITHUB_TOKEN' to GitHub CLI
  .github/workflows/canary.yaml
Labels: PR: internal 🏠

#3475 ci: checkout repo in canary workflow
  .github/workflows/canary.yaml
Labels: PR: internal 🏠

#3477 ci: fix & cleanup script for modifying NPM package into canary
  .github/workflows/canary.yaml
Labels: PR: internal 🏠

#3479 ci: Add missing require to canary script
  .github/workflows/canary.yaml
Labels: PR: internal 🏠

#3481 ci: fix missing PR number in canary release workflow
  .github/workflows/canary.yaml
Labels: PR: internal 🏠

#3483 ci: fix missing PR number in canary release workflow
  .github/workflows/canary.yaml
Labels: PR: internal 🏠

#3484 ci: Moving GH Action template syntax to env variables
  .github/actions/deploy-dir-as-branch/action.yml
Labels: PR: internal 🏠

#3485 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3486 ci: improve comment on canary releases
  .github/workflows/canary.yaml
Labels: PR: internal 🏠

#3487 feat: expose getArgumentValues
  src/execution/index.ts
  src/execution/values.ts
  src/index.ts
Labels: PR: feature 🚀

#3488 ci: Extract branch publishing into separate workflow
  .github/actions/deploy-dir-as-branch/action.yml
  .github/workflows/canary.yaml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-artifact-as-branch.yml
Labels: PR: internal 🏠

#3489 ci: use '.node-version' file to configure node version used for CI
  .github/workflows/canary.yaml
  .github/workflows/ci.yml
  .node-version
Labels: PR: internal 🏠

#3491 ci: use separate workflows for 'push' and 'pull_request'
  .github/workflows/canary.yaml
  .github/workflows/ci.yml
  .github/workflows/deploy-artifact-as-branch.yml
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
Labels: PR: internal 🏠

#3493 ci: remove unused 'workflow_id' input
  .github/workflows/deploy-artifact-as-branch.yml
  .github/workflows/push.yml
Labels: PR: internal 🏠

#3496 ci: fix deprecation of canary package
  .github/workflows/canary.yaml
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3502 ci: fix deployments of npm & deno branches
  .github/workflows/deploy-artifact-as-branch.yml
  .github/workflows/push.yml
Labels: PR: internal 🏠

#3505 correct outdated documentation
  src/type/definition.ts
Labels: PR: docs 📝
