Repository graphql/graphql-js, pull requests merged in 2022-03, with the labels that each got.

#3514 GraphQLError: switch constructor overload order
  src/error/GraphQLError.ts
Labels: PR: bug fix 🐞

#3503 ci: Add '@github-actions' bot
  .github/workflows/ci.yml
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/cmd-run-benchmark.yml
  .github/workflows/github-actions-bot.yml
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_opened.yml
Labels: PR: internal 🏠

#3522 tests(execution): add missing new lines
  src/execution/__tests__/directives-test.ts
Labels: PR: polish 💅

#3524 tests(printSchema): test omitting schema of common names
  src/utilities/__tests__/printSchema-test.ts
Labels: PR: polish 💅
