Repository graphql/graphql-js, pull requests merged in 2022-05, with the labels that each got.

#3552 Switch NPM package to support only ESM
  .babelrc-npm.json
  .eslintrc.yml
  benchmark/benchmark.js
  benchmark/buildASTSchema-benchmark.js
  benchmark/buildClientSchema-benchmark.js
  benchmark/fixtures.js
  benchmark/introspectionFromSchema-benchmark.js
  benchmark/parser-benchmark.js
  benchmark/validateGQL-benchmark.js
  benchmark/validateInvalidGQL-benchmark.js
  benchmark/validateSDL-benchmark.js
  benchmark/visit-benchmark.js
  benchmark/visitInParallel-benchmark.js
  integrationTests/node/index.js
  integrationTests/node/package.json
  integrationTests/node/test.js
  integrationTests/ts/package.json
  integrationTests/ts/test.js
  integrationTests/webpack/entry.js
  integrationTests/webpack/package.json
  integrationTests/webpack/test.js
  integrationTests/webpack/webpack.config.json
  package.json
  resources/build-npm.js
  resources/utils.js
Labels: PR: breaking change 💥

#3553 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3551 Add test watch script
  .github/workflows/ci.yml
  package.json
Labels: PR: internal 🏠

#3554 Expose GraphQLErrorOptions type
  src/error/GraphQLError.ts
  src/error/index.ts
  src/index.ts
Labels: PR: feature 🚀

#3555 Switch from shell's `cp` to 'fs.cpSync' in scripts
  benchmark/benchmark.js
  integrationTests/integration-test.js
Labels: PR: internal 🏠

#3557 Fully switch to `tsc` and remove `babel`
  .mocharc.yml
  package-lock.json
  package.json
  resources/add-extension-to-import-paths.js
  resources/build-deno.js
  resources/build-npm.js
  resources/inline-invariant.js
  resources/ts-register.js
  src/execution/__tests__/mapAsyncIterator-test.ts
  src/execution/__tests__/subscribe-test.ts
  src/validation/rules/KnownDirectivesRule.ts
  src/validation/rules/PossibleTypeExtensionsRule.ts
  tsconfig.json
Labels: PR: internal 🏠

#3558 integrationTests: switch tests to TS
  .eslintrc.yml
  integrationTests/integration-test.ts
  package.json
  tsconfig.json
Labels: PR: internal 🏠

#3559 benchmark: rewrite benchmark in TS
  .eslintrc.yml
  benchmark/benchmark.ts
  package.json
  tsconfig.json
Labels: PR: internal 🏠

#3560 diff-npm-packages: fix crash with ENOBUFS
  resources/diff-npm-package.js
  resources/utils.js
Labels: PR: internal 🏠

#3562 resources: switch internal scripts to TS
  .eslintrc.yml
  .github/workflows/pull_request.yml
  package-lock.json
  package.json
  resources/add-extension-to-import-paths.js
  resources/add-extension-to-import-paths.ts
  resources/build-deno.ts
  resources/build-npm.ts
  resources/diff-npm-package.ts
  resources/gen-changelog.ts
  resources/gen-version.ts
  resources/inline-invariant.ts
  resources/utils.ts
  tsconfig.json
Labels: PR: internal 🏠

#3563 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3565 Expose GraphQLErrorOptions type (#3554)
  src/error/GraphQLError.ts
  src/error/index.ts
  src/index.ts
Labels: PR: feature 🚀

#3566 validateSchema: unify check of root types
  src/jsutils/__tests__/capitalize-test.ts
  src/jsutils/capitalize.ts
  src/type/validate.ts
Labels: PR: polish 💅

#3568 Refactor out `AccumulatorMap` from `groupBy`
  src/execution/collectFields.ts
  src/jsutils/AccumulatorMap.ts
  src/jsutils/__tests__/AccumulatorMap-test.ts
  src/jsutils/groupBy.ts
Labels: PR: polish 💅

#3453 fix(validate): no reusing root types
  src/jsutils/didYouMean.ts
  src/jsutils/formatList.ts
  src/type/__tests__/validation-test.ts
  src/type/validate.ts
Labels: PR: feature 🚀

#3569 invariant/devAssert: make typings of `condition` stricter
  src/error/__tests__/GraphQLError-test.ts
  src/execution/__tests__/simplePubSub.ts
  src/execution/execute.ts
  src/jsutils/devAssert.ts
  src/jsutils/invariant.ts
  src/type/__tests__/extensions-test.ts
  src/type/schema.ts
  src/utilities/introspectionFromSchema.ts
  src/validation/rules/UniqueInputFieldNamesRule.ts
  src/validation/validate.ts
Labels: PR: polish 💅

#3570 Delete deprecated 'graphql/subscription' module
  src/index.ts
  src/subscription/README.md
  src/subscription/index.ts
Labels: PR: breaking change 💥

#3571 Remove deprecated `getOperationRootType`
  src/index.ts
  src/utilities/__tests__/getOperationRootType-test.ts
  src/utilities/getOperationRootType.ts
  src/utilities/index.ts
Labels: PR: breaking change 💥

#3574 Remove deprecated `TypeInfo` argument of `validate` function
  src/validation/__tests__/validation-test.ts
  src/validation/validate.ts
Labels: PR: breaking change 💥

#3575 Remove deprecate `getFieldDefFn` argument of `TypeInfo` constructor
  src/utilities/TypeInfo.ts
Labels: PR: breaking change 💥

#3577 Drop deprecated positional arguments on GraphQLError
  src/error/GraphQLError.ts
  src/error/__tests__/GraphQLError-test.ts
  src/execution/execute.ts
  src/type/scalars.ts
Labels: PR: breaking change 💥

#3578 Remove dev asserts added temporary for v15 to v16 migration
  src/execution/execute.ts
  src/execution/subscribe.ts
  src/graphql.ts
Labels: PR: breaking change 💥

#3579 Remove deprecated `*Enum` types
  src/index.ts
  src/language/directiveLocation.ts
  src/language/index.ts
  src/language/kinds.ts
  src/language/tokenKind.ts
Labels: PR: breaking change 💥

#3580 Remove deprecated `getVisitFn` function
  src/index.ts
  src/language/index.ts
  src/language/visitor.ts
Labels: PR: breaking change 💥

#3581 ASTVisitorKeyMap: drop deprecation notice
  src/language/visitor.ts
Labels: PR: deprecation ⚠

#3582 Remove deprecate printError/formatError methods
  src/error/GraphQLError.ts
  src/error/__tests__/GraphQLError-test.ts
  src/error/index.ts
  src/index.ts
Labels: PR: breaking change 💥

#3583 tests: Use chai's `assert` instead of `invariant`
  src/error/__tests__/GraphQLError-test.ts
  src/execution/__tests__/executor-test.ts
  src/execution/__tests__/simplePubSub.ts
  src/execution/__tests__/subscribe-test.ts
  src/execution/__tests__/variables-test.ts
  src/language/__tests__/blockString-fuzz.ts
  src/type/__tests__/extensions-test.ts
  src/utilities/__tests__/TypeInfo-test.ts
  src/utilities/__tests__/buildASTSchema-test.ts
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/__tests__/extendSchema-test.ts
  src/utilities/__tests__/stripIgnoredCharacters-fuzz.ts
  src/utilities/__tests__/stripIgnoredCharacters-test.ts
  src/utilities/__tests__/valueFromAST-test.ts
Labels: PR: polish 💅

#3584 Speedup tests by ~15% by moving some `stripIgnoredCharacters` tests to fuzzing
  src/utilities/__tests__/stripIgnoredCharacters-fuzz.ts
  src/utilities/__tests__/stripIgnoredCharacters-test.ts
Labels: PR: polish 💅

#3585 internal: move `benchmark.ts` into resources folder
  .eslintrc.yml
  package.json
  resources/benchmark.ts
Labels: PR: internal 🏠

#3586 Fix performance issue with ESLint
  .eslintrc.yml
Labels: PR: internal 🏠

#3587 resources: mark node's modules with 'node:' prefix
  resources/benchmark.ts
  resources/gen-changelog.ts
Labels: PR: internal 🏠

#3588 Remove superficial ESLint config
  .eslintrc.yml
Labels: PR: internal 🏠

#3591 Initial support of mutation testing with stryker-js
  .c8rc.json
  .eslintignore
  .github/workflows/mutation-testing.yml
  .gitignore
  .prettierignore
  package-lock.json
  package.json
  stryker.conf.json
Labels: PR: internal 🏠

#3594 Revert "Remove deprecate `getFieldDefFn` argument of `TypeInfo` const…
  src/utilities/TypeInfo.ts
Labels: PR: breaking change 💥

#3595 Revert "Remove deprecated `TypeInfo` argument of `validate` function"
  src/validation/__tests__/validation-test.ts
  src/validation/validate.ts
Labels: PR: breaking change 💥

#3597 Fix typing for `isNonNullType`
  src/index.ts
  src/type/definition.ts
  src/type/index.ts
Labels: PR: feature 🚀

#3598 Refactor `GraphQL*Type` TS types to be more DRY
  src/type/definition.ts
Labels: PR: polish 💅

#3596 benchmark: test performance cost of re-creating schema
  benchmark/GraphQLSchema-benchmark.js
Labels: PR: internal 🏠

#3602 gen-changelog: fix crash due to 'git rev-list' returning empty string
  resources/utils.ts
Labels: PR: internal 🏠

#3605 Add new 'GraphQLSchema.getField' method
  src/execution/execute.ts
  src/execution/subscribe.ts
  src/type/__tests__/schema-test.ts
  src/type/schema.ts
  src/utilities/TypeInfo.ts
  src/utilities/__tests__/TypeInfo-test.ts
Labels: PR: feature 🚀

#3607 Update deps
  .eslintrc.yml
  integrationTests/ts/package.json
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3608 Remove 'utf-8' as argument of `writeFileSync`
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/github-actions-bot.yml
  resources/diff-npm-package.ts
Labels: PR: internal 🏠

#3610 resources: add new `localRepoPath` utility function
  resources/benchmark.ts
  resources/build-npm.ts
  resources/diff-npm-package.ts
  resources/utils.ts
Labels: PR: internal 🏠

#3611 diff-npm-package: move report into shared 'reports' folder
  .github/workflows/pull_request.yml
  resources/diff-npm-package.ts
Labels: PR: internal 🏠

#3612 github actions: switch embedded JS to ESM
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/cmd-run-benchmark.yml
  .github/workflows/github-actions-bot.yml
Labels: PR: internal 🏠

#3613 GH actions: fix 'checkForCommonlyIgnoredFiles'
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3614 Lint GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/cmd-run-benchmark.yml
  .github/workflows/deploy-artifact-as-branch.yml
  .github/workflows/pull_request.yml
Labels: PR: internal 🏠

#3615 Update GitHub actions dependencies
  .github/workflows/ci.yml
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/cmd-run-benchmark.yml
  .github/workflows/deploy-artifact-as-branch.yml
  .github/workflows/github-actions-bot.yml
  .github/workflows/mutation-testing.yml
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_opened.yml
Labels: PR: internal 🏠
