Repository graphql/graphql-js, pull requests merged in 2022-08, with the labels that each got.

#3684 parser: limit maximum number of tokens
  src/language/__tests__/parser-test.ts
  src/language/parser.ts
Labels: PR: feature 🚀

#3688 Replace all instances of `ObjMap<boolean>` with ES6 Set
  src/type/schema.ts
  src/type/validate.ts
  src/validation/ValidationContext.ts
  src/validation/rules/KnownTypeNamesRule.ts
  src/validation/rules/NoFragmentCyclesRule.ts
  src/validation/rules/NoUndefinedVariablesRule.ts
  src/validation/rules/NoUnusedFragmentsRule.ts
  src/validation/rules/NoUnusedVariablesRule.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Labels: PR: polish 💅

#3689 Remove superficial `.values()` and `.entries()` calls
  src/execution/execute.ts
  src/jsutils/__tests__/AccumulatorMap-test.ts
  src/jsutils/promiseForObject.ts
  src/type/validate.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
Labels: PR: polish 💅

#3690 Motivation: looked into this it as part of #3687
  src/utilities/extendSchema.ts
Labels: PR: polish 💅

#3692 gen-changelog: Use `fetch` instead of `http.request`
  resources/gen-changelog.ts
  tsconfig.json
Labels: PR: internal 🏠

#3693 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3655 polish: add tests for `expectPromise` and `expectEqualPromisesOrValues`
  src/__testUtils__/__tests__/expectEqualPromisesOrValues-test.ts
  src/__testUtils__/__tests__/expectMatchingValues-test.ts
  src/__testUtils__/__tests__/expectPromise-test.ts
  src/__testUtils__/expectEqualPromisesOrValues.ts
  src/__testUtils__/expectMatchingValues.ts
  src/__testUtils__/expectPromise.ts
  src/execution/__tests__/subscribe-test.ts
Labels: PR: polish 💅

#3695 benchmark: use 'execOutput' from 'util.ts'
  resources/benchmark.ts
Labels: PR: internal 🏠

#3697 resources: Move `mkdirSync` into `writeGeneratedFile`
  resources/build-deno.ts
  resources/build-npm.ts
  resources/diff-npm-package.ts
  resources/utils.ts
Labels: PR: internal 🏠

#3698 resources: merge execOutput and exec into single function
  resources/benchmark.ts
  resources/diff-npm-package.ts
  resources/gen-changelog.ts
  resources/utils.ts
Labels: PR: internal 🏠

#3699 ci: add dependency review workflow
  .github/workflows/pull_request.yml
Labels: PR: internal 🏠

#3686 Workaround for codesandbox having bug with TS enums
  src/language/ast.ts
  src/language/directiveLocation.ts
  src/language/kinds.ts
  src/language/tokenKind.ts
  src/type/introspection.ts
  src/utilities/findBreakingChanges.ts
Labels: PR: bug fix 🐞

#3701 Parser: allow 'options' to explicitly accept undefined
  src/language/parser.ts
Labels: PR: bug fix 🐞

#3702 parser: limit maximum number of tokens
  src/language/__tests__/parser-test.ts
  src/language/parser.ts
Labels: PR: feature 🚀

#3704 resources: replace execSync with spawnSync
  integrationTests/integration-test.ts
  resources/benchmark.ts
  resources/diff-npm-package.ts
  resources/gen-changelog.ts
  resources/utils.ts
Labels: PR: internal 🏠

#3700 ci: Add CodeQL analysis
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3659 Reference implementation of defer and stream spec
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/flattenAsyncIterable-test.ts
  src/execution/__tests__/mutations-test.ts
  src/execution/__tests__/nonnull-test.ts
  src/execution/__tests__/stream-test.ts
  src/execution/__tests__/subscribe-test.ts
  src/execution/__tests__/sync-test.ts
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/execution/flattenAsyncIterable.ts
  src/execution/index.ts
  src/graphql.ts
  src/index.ts
  src/type/directives.ts
  src/type/index.ts
  src/validation/__tests__/DeferStreamDirectiveLabelRule-test.ts
  src/validation/__tests__/DeferStreamDirectiveOnRootFieldRule-test.ts
  src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
  src/validation/__tests__/StreamDirectiveOnListFieldRule-test.ts
  src/validation/__tests__/harness.ts
  src/validation/index.ts
  src/validation/rules/DeferStreamDirectiveLabelRule.ts
  src/validation/rules/DeferStreamDirectiveOnRootFieldRule.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
  src/validation/rules/StreamDirectiveOnListFieldRule.ts
  src/validation/specifiedRules.ts
  website/docs/tutorials/defer-stream.md
  website/sidebars.js
Labels: PR: feature 🚀
