Repository graphql/graphql-js, pull requests merged in 2022-12, with the labels that each got.

#3797 workflows: fix and cleanup permissions
  .github/workflows/ci.yml
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/cmd-run-benchmark.yml
  .github/workflows/deploy-artifact-as-branch.yml
  .github/workflows/github-actions-bot.yml
  .github/workflows/mutation-testing.yml
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_opened.yml
  .github/workflows/push.yml
Labels: PR: internal 🏠

#3800 fix permissions for codeql-action
  .github/workflows/ci.yml
  .github/workflows/pull_request.yml
Labels: PR: internal 🏠

#3793 polish: do not repeat isPromise check
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
Labels: PR: polish 💅

#3754 enhancement: remove extra ticks
  src/execution/__tests__/nonnull-test.ts
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
Labels: PR: feature 🚀

#3801 polish: narrow mapSourceToResponse return type
  src/execution/execute.ts
Labels: PR: polish 💅

#3742 Remove defer/stream support from subscriptions
  src/execution/__tests__/flattenAsyncIterable-test.ts
  src/execution/__tests__/subscribe-test.ts
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/execution/flattenAsyncIterable.ts
  src/execution/index.ts
  src/index.ts
  src/validation/__tests__/DeferStreamDirectiveOnValidOperationsRule-test.ts
  src/validation/index.ts
  src/validation/rules/DeferStreamDirectiveOnValidOperationsRule.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
  src/validation/specifiedRules.ts
Labels: PR: breaking change 💥

#3722 original `execute` should throw if defer/stream directives are present
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/executor-test.ts
  src/execution/execute.ts
Labels: PR: breaking change 💥
