Repository graphql/graphql-js, pull requests merged in 2022-06, with the labels that each got.

#3625 benchmark: replace failing on context switching with warning
  resources/benchmark.ts
Labels: PR: internal 🏠

#3624 diff-npm-package: fix reports dir creation
  resources/diff-npm-package.ts
Labels: PR: internal 🏠

#3618 extendSchema: Do not modify standard directives
  src/utilities/__tests__/extendSchema-test.ts
  src/utilities/extendSchema.ts
Labels: PR: bug fix 🐞

#3626 ci: Fix imports in 'actions/github-script'
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/cmd-run-benchmark.yml
  .github/workflows/github-actions-bot.yml
Labels: PR: internal 🏠

#3622 fix: update remaining `GraphQLNonNull<GraphQLType>` codepoints to `GraphQLNonNull<GraphQLNullableType>`
  src/type/definition.ts
Labels: PR: breaking change 💥

#3627 Reuse GraphQLWrappingType in 'GraphQLType' definition
  src/type/definition.ts
Labels: PR: polish 💅

#3631 ci: speed up 'ci' workflow by removing unneeded internal dependencies
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3628 benchmark: add Windows compatibility
  resources/benchmark.ts
Labels: PR: internal 🏠

#3630 subscribe-test: extract `subscribeWithBadFn` function
  src/execution/__tests__/subscribe-test.ts
Labels: PR: polish 💅

#3621 change incorrect subscribe return type to a GraphQLError
  src/execution/__tests__/subscribe-test.ts
  src/execution/subscribe.ts
Labels: PR: breaking change 💥

#3620 align return types from execution and subscription
  src/execution/__tests__/subscribe-test.ts
  src/execution/subscribe.ts
Labels: PR: breaking change 💥

#3634 createSourceEventStream: introduce named arguments and deprecate positional arguments
  src/execution/__tests__/subscribe-test.ts
  src/execution/subscribe.ts
Labels: PR: feature 🚀

#3635 createSourceEventStream: remove deprecated positional argument overload
  src/execution/__tests__/subscribe-test.ts
  src/execution/subscribe.ts
Labels: PR: breaking change 💥

#3636 move `subscribe` code to `execute` file
  src/execution/__tests__/subscribe-test.ts
  src/execution/execute.ts
  src/execution/index.ts
  src/execution/subscribe.ts
Labels: PR: polish 💅

#3642 Remove 'devAssert' checks that duplicate TS types
  src/execution/__tests__/executor-test.ts
  src/execution/__tests__/subscribe-test.ts
  src/execution/execute.ts
  src/language/__tests__/source-test.ts
  src/language/source.ts
  src/type/__tests__/assertName-test.ts
  src/type/__tests__/definition-test.ts
  src/type/__tests__/directive-test.ts
  src/type/__tests__/predicate-test.ts
  src/type/__tests__/schema-test.ts
  src/type/assertName.ts
  src/type/definition.ts
  src/type/directives.ts
  src/type/schema.ts
  src/utilities/__tests__/buildASTSchema-test.ts
  src/utilities/__tests__/extendSchema-test.ts
  src/utilities/buildASTSchema.ts
  src/utilities/buildClientSchema.ts
  src/utilities/extendSchema.ts
  src/validation/__tests__/validation-test.ts
  src/validation/validate.ts
Labels: PR: breaking change 💥

#3643 Remove 'assertValidExecutionArguments' function
  src/execution/execute.ts
Labels: PR: breaking change 💥

#3654 refactor: use `exeContext` strategically
  src/execution/execute.ts
Labels: PR: polish 💅

#3639 refactor: subscribe: introduce `buildPerEventExecutionContext`
  src/execution/__tests__/subscribe-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞

#3418 [RFC] Client Controlled Nullability experiment implementation w/o execution
  src/__testUtils__/kitchenSinkQuery.ts
  src/index.ts
  src/language/__tests__/lexer-test.ts
  src/language/__tests__/parser-test.ts
  src/language/__tests__/predicates-test.ts
  src/language/__tests__/printer-test.ts
  src/language/__tests__/visitor-test.ts
  src/language/ast.ts
  src/language/index.ts
  src/language/kinds.ts
  src/language/lexer.ts
  src/language/parser.ts
  src/language/predicates.ts
  src/language/printer.ts
  src/language/tokenKind.ts
  src/utilities/__tests__/stripIgnoredCharacters-test.ts
Labels: spec RFC, PR: feature 🚀
