Repository graphql/graphql-js, pull requests merged in 2022-11, with the labels that each got.

#3769 Fix typo in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: PR: internal 🏠

#3770 Minor simplification in schema-test
  src/type/__tests__/schema-test.ts
Labels: PR: internal 🏠

#3771 lint: enable ESLint's `logical-assignment-operators` rule
  .eslintrc.yml
  resources/diff-npm-package.ts
  resources/gen-changelog.ts
  resources/utils.ts
  src/language/blockString.ts
Labels: PR: polish 💅

#3772 eslintrc: reorder rules to match order in the official docs
  .eslintrc.yml
Labels: PR: internal 🏠

#3774 eslintrc: enable few rules with minimal code changes
  .eslintrc.yml
  integrationTests/node/test.js
  resources/benchmark.ts
Labels: PR: internal 🏠

#3778 Remove outdated instructions on experimental tag
  README.md
Labels: PR: docs 📝

#3781 Fix comments in defer/stream validation rules
  src/validation/__tests__/DeferStreamDirectiveOnRootFieldRule-test.ts
  src/validation/rules/DeferStreamDirectiveLabelRule.ts
  src/validation/rules/DeferStreamDirectiveOnRootFieldRule.ts
  src/validation/rules/StreamDirectiveOnListFieldRule.ts
Labels: PR: polish 💅

#3779 Update deps
  .eslintrc.yml
  integrationTests/ts/package.json
  package-lock.json
  package.json
  src/jsutils/instanceOf.ts
Labels: PR: dependency 📦

#3776 extendSchema: preserve "description" and "extensions"
  src/utilities/__tests__/extendSchema-test.ts
  src/utilities/extendSchema.ts
Labels: PR: bug fix 🐞
