Repository graphql/graphql-js, pull requests merged in 2022-10, with the labels that each got.

#3757 fix: re-initialize subsequentPayloads
  src/execution/execute.ts
Labels: PR: bug fix 🐞

#3706 Fix crash in node when mixing sync/async resolvers
  src/execution/__tests__/executor-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞

#3762 Fix formatting in schema for test "resolve Interface type using __typename on source object"
  src/execution/__tests__/abstract-test.ts
Labels: PR: polish 💅

#3763 resources/utils: fix `git().revList`
  resources/utils.ts
Labels: PR: bug fix 🐞

#3759 fix(github-actions-bot): add additional permissions
  .github/workflows/github-actions-bot.yml
Labels: PR: internal 🏠

#3766 Update deps
  .eslintrc.yml
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3760 fix(incrementalDelivery): fix null bubbling with async iterables
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞
