Repository graphql/graphql-js, pull requests merged in 2022-04, with the labels that each got.

#3525 github-actions-bot: Fix collapsing of unrelated comments
  .github/workflows/github-actions-bot.yml
Labels: PR: internal 🏠

#3512 Update documentation on deprecated formatError(..)
  src/error/GraphQLError.ts
Labels: PR: docs 📝

#3530 integrationTests/node: fix crash on Mac with M1 by using docker
  integrationTests/integration-test.js
  integrationTests/node/package.json
  integrationTests/node/test.js
  package-lock.json
  package.json
Labels: PR: internal 🏠

#3533 Update deps
  .eslintrc.yml
  integrationTests/ts/package.json
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3534 github-actions-bot: fix publishing of canary releases
  .github/workflows/github-actions-bot.yml
Labels: PR: internal 🏠

#3536 github-actions-bot: fix usage of NPM_CANARY_PR_PUBLISH_TOKEN
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/github-actions-bot.yml
Labels: PR: internal 🏠

#3537 ESLint: disallow using node globals in src/tests
  .eslintrc.yml
  src/jsutils/instanceOf.ts
Labels: PR: polish 💅

#3538 github-actions-bot: fix reply on commands
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/cmd-run-benchmark.yml
  .github/workflows/github-actions-bot.yml
Labels: PR: internal 🏠

#3543 pass valid value to codecov config
  codecov.yml
Labels: PR: internal 🏠

#3544 internal: add node@18 to supported versions and test it
  package.json
Labels: PR: internal 🏠

#3545 package.json: Switch to alpha tag on NPM
  package.json
Labels: PR: internal 🏠

#3546 Drop support for node 12 and 17, update rest to latest minor version
  .babelrc-npm.json
  .node-version
  package-lock.json
  package.json
Labels: PR: breaking change 💥

#3548 ci: disable Codecov and measure test coverage on every run
  .c8rc.json
  .github/workflows/ci.yml
  README.md
  codecov.yml
  cspell.yml
  package.json
Labels: PR: internal 🏠

#3549 ESLint: add 'shared-node-browser' environment
  .eslintrc.yml
Labels: PR: internal 🏠

#3456 print: add spaces inside input object
  src/language/__tests__/printer-test.ts
  src/language/__tests__/schema-printer-test.ts
  src/language/printer.ts
  src/type/__tests__/introspection-test.ts
  src/type/__tests__/scalars-test.ts
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/__tests__/findBreakingChanges-test.ts
  src/utilities/__tests__/sortValueNode-test.ts
Labels: PR: breaking change 💥
