Repository graphql/graphql-js, pull requests merged in 2022-09, with the labels that each got.

#3721 ci: Move 'integration-test.ts' into 'resources'
  package.json
  resources/integration-test.ts
Labels: PR: internal 🏠

#3723 resources: add utility function to create tmp dir
  package.json
  resources/benchmark.ts
  resources/build-docusaurus.ts
  resources/diff-npm-package.ts
  resources/integration-test.ts
  resources/utils.ts
Labels: PR: internal 🏠

#3724 resources/utils.ts: npm/git will inherit stdout by default
  resources/benchmark.ts
  resources/build-docusaurus.ts
  resources/diff-npm-package.ts
  resources/gen-changelog.ts
  resources/integration-test.ts
  resources/utils.ts
Labels: PR: internal 🏠

#3720 Filter subsequent payloads when parent field is null
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞, stream/defer

#3725 changelog: use top-level await to simplify code
  resources/gen-changelog.ts
  resources/utils.ts
Labels: PR: internal 🏠

#3735 resources: replace usage of deprecated ts function
  resources/build-deno.ts
Labels: PR: internal 🏠

#3736 promiseForObject: convert to be async function
  src/jsutils/promiseForObject.ts
Labels: PR: polish 💅

#3737 Update deps
  .eslintrc.yml
  cspell.yml
  integrationTests/ts/package.json
  package-lock.json
  package.json
Labels: PR: dependency 📦

#3738 Remove unused Babel config files
  .babelrc-deno.json
  .babelrc-npm.json
  .babelrc.json
Labels: PR: internal 🏠

#3729 incrementalDelivery: fix iterable streaming with errors
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞

#3741 build-npm/deno: use TS to find all *.ts files
  resources/build-deno.ts
  resources/build-npm.ts
  resources/utils.ts
Labels: PR: internal 🏠

#3745 resources/util: spawn command fail on error
  integrationTests/node/index.cjs
  resources/utils.ts
Labels: PR: internal 🏠

#3751 GitHub Workflows security hardening
  .github/workflows/ci.yml
  .github/workflows/cmd-publish-pr-on-npm.yml
  .github/workflows/cmd-run-benchmark.yml
  .github/workflows/deploy-artifact-as-branch.yml
  .github/workflows/github-actions-bot.yml
  .github/workflows/mutation-testing.yml
  .github/workflows/push.yml
Labels: PR: internal 🏠

#3747 add filtering for asyncIterable lists
  src/execution/__tests__/defer-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞

#3749 polish: add additional test
  src/execution/__tests__/stream-test.ts
Labels: PR: polish 💅

#3748 Fix typo in the error message for max tokens
  src/language/__tests__/parser-test.ts
  src/language/parser.ts
Labels: PR: bug fix 🐞

#3728 incrementalDelivery: refactoring and streamlining
  src/execution/execute.ts
Labels: PR: polish 💅

#3752 refactor: introduce completeListItemValue
  src/execution/execute.ts
Labels: PR: polish 💅
