Repository graphql/graphql-js, pull requests merged in 2023-08, with the labels that each got.

#3947 Fix edit URL in documentation
  website/docusaurus.config.cjs
Labels: PR: docs 📝

#3948 Add support for fourfold nested lists in introspection
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/getIntrospectionQuery.ts
Labels: PR: feature 🚀

#3950 Support fourfold nested lists
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/getIntrospectionQuery.ts
Labels: PR: feature 🚀

#3951 Fix invalid sample code
  website/docs/tutorials/index.md
Labels: PR: docs 📝

#3930 incremental publisher should handle all response building
  src/execution/IncrementalPublisher.ts
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/lists-test.ts
  src/execution/__tests__/nonnull-test.ts
  src/execution/__tests__/oneof-test.ts
  src/execution/__tests__/stream-test.ts
  src/execution/__tests__/subscribe-test.ts
  src/execution/execute.ts
  src/execution/index.ts
  src/graphql.ts
Labels: PR: polish 💅

#3904 add tests with regard to duplication
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/stream-test.ts
Labels: PR: polish 💅

#3886 RFC: incremental delivery: without branching, with deduplication
  src/execution/IncrementalPublisher.ts
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/mutations-test.ts
  src/execution/__tests__/stream-test.ts
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/jsutils/getBySet.ts
  src/jsutils/isSameSet.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
Labels: PR: breaking change 💥

#3897 incremental delivery: add pending notifications
  src/execution/IncrementalPublisher.ts
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/mutations-test.ts
  src/execution/__tests__/stream-test.ts
Labels: PR: breaking change 💥

#3960 incremental: utilize `id` and `subPath` rather than `path` and `label`
  src/execution/IncrementalPublisher.ts
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/mutations-test.ts
  src/execution/__tests__/stream-test.ts
Labels: PR: breaking change 💥

#3962 skip unnecessary initialization of empty items array
  src/execution/IncrementalPublisher.ts
Labels: PR: polish 💅
