Repository graphql/graphql-js, pull requests merged in 2023-02, with the labels that each got.

#3843 internal: fix website build error
  resources/build-docusaurus.ts
Labels: PR: internal 🏠

#3839 Fix ambiguity around when schema definition may be omitted
  src/__testUtils__/viralSDL.ts
  src/__testUtils__/viralSchema.ts
  src/utilities/__tests__/buildASTSchema-test.ts
  src/utilities/__tests__/printSchema-test.ts
  src/utilities/printSchema.ts
Labels: spec RFC

#3849 ESLint: use the `--rulesdir` option for internal rules.
  .eslintrc.yml
  package-lock.json
  package.json
  resources/build-docusaurus.ts
  resources/eslint-internal-rules/README.md
  resources/eslint-internal-rules/package.json
Labels: PR: internal 🏠

#3832 internal: fix inlineInvariant for cjs builds that require filenames with explicit extensions
  integrationTests/node/index.cjs
  integrationTests/node/index.mjs
  resources/inline-invariant.ts
Labels: PR: bug fix 🐞

#3848 Add node@19 to integration tests + use it in CI
  .node-version
  package-lock.json
  package.json
Labels: PR: internal 🏠

#3850 ci: uncomment package-lock.json check for unmet dependencies
  .github/workflows/ci.yml
Labels: PR: internal 🏠

#3852 ESLint: switch to '.eslintrc.cjs' as config file
  .eslintrc.cjs
  .eslintrc.yml
Labels: PR: internal 🏠

#3854 Update deps
  .eslintrc.cjs
  package-lock.json
  package.json
  website/docusaurus.config.cjs
Labels: PR: dependency 📦

#3855 Drop support for node14
  .eslintrc.cjs
  .github/workflows/ci.yml
  package-lock.json
  package.json
  resources/eslint-internal-rules/package.json
  src/execution/values.ts
  src/language/parser.ts
  tsconfig.json
Labels: PR: breaking change 💥

#3856 Use `replaceAll` instead of RegExp with global flag
  integrationTests/node/test.js
  src/__testUtils__/dedent.ts
  src/__testUtils__/inspectStr.ts
  src/language/blockString.ts
  src/language/printer.ts
  src/utilities/printSchema.ts
Labels: PR: polish 💅
