Repository graphql/graphql-js, pull requests merged in 2023-09, with the labels that each got.

#3964 fix for development on Windows
  package.json
  resources/utils.ts
Labels: PR: internal 🏠

#3965 instanceOf: workaround bundler issue with process.env
  src/jsutils/instanceOf.ts
Labels: PR: bug fix 🐞

#3966 polish: addDeferredFragments
  src/execution/execute.ts
Labels: PR: polish 💅

#3958 OverlappingFieldsCanBeMergedRule: Fix performance degradation
  benchmark/repeated-fields-benchmark.js
  src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Labels: PR: bug fix 🐞

#3957 docs: add installation instructions for bun
  README.md
Labels: PR: docs 📝

#3967 OverlappingFieldsCanBeMergedRule: Fix performance degradation
  benchmark/repeated-fields-benchmark.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Labels: PR: bug fix 🐞

#3970 tests: remove empty strings in string literals
  .eslintrc.cjs
  src/__testUtils__/kitchenSinkQuery.ts
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/stream-test.ts
  src/utilities/__tests__/printSchema-test.ts
Labels: PR: polish 💅
