Repository graphql/graphql-js, pull requests merged in 2023-04, with the labels that each got.

#3872 Enable @typescript-eslint/strict-boolean-expressions rule
  .eslintrc.cjs
  resources/gen-changelog.ts
  src/error/GraphQLError.ts
  src/execution/__tests__/abstract-test.ts
  src/execution/__tests__/executor-test.ts
  src/execution/__tests__/stream-test.ts
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/execution/values.ts
  src/jsutils/didYouMean.ts
  src/language/printer.ts
  src/language/visitor.ts
  src/type/__tests__/enumType-test.ts
  src/type/introspection.ts
  src/type/validate.ts
  src/utilities/TypeInfo.ts
  src/utilities/buildClientSchema.ts
  src/utilities/coerceInputValue.ts
  src/utilities/valueFromAST.ts
  src/validation/rules/DeferStreamDirectiveLabelRule.ts
  src/validation/rules/FieldsOnCorrectTypeRule.ts
  src/validation/rules/KnownArgumentNamesRule.ts
  src/validation/rules/KnownDirectivesRule.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
  src/validation/rules/PossibleTypeExtensionsRule.ts
  src/validation/rules/ProvidedRequiredArgumentsRule.ts
  src/validation/rules/UniqueDirectiveNamesRule.ts
  src/validation/rules/UniqueDirectivesPerLocationRule.ts
  src/validation/rules/UniqueEnumValueNamesRule.ts
  src/validation/rules/UniqueFieldDefinitionNamesRule.ts
  src/validation/rules/UniqueFragmentNamesRule.ts
  src/validation/rules/UniqueInputFieldNamesRule.ts
  src/validation/rules/UniqueOperationNamesRule.ts
  src/validation/rules/UniqueOperationTypesRule.ts
  src/validation/rules/UniqueTypeNamesRule.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
  src/validation/rules/VariablesInAllowedPositionRule.ts
Labels: PR: polish 💅

#3873 ASTReducer: correctly type scalar values
  src/language/printer.ts
  src/language/visitor.ts
Labels: PR: bug fix 🐞

#3874 GraphQLObjectType: partial revert of #3143, due to perf regression
  src/type/definition.ts
Labels: PR: polish 💅

#3875 GraphQLInputObjectType: remove check that duplicate TS types
  src/type/__tests__/definition-test.ts
  src/type/definition.ts
Labels: PR: breaking change 💥

#3876 GraphQL*Type: bind only single property instead of entire context
  src/type/definition.ts
Labels: PR: polish 💅

#3877 GraphQLInterface: add missing template parameters
  src/execution/__tests__/abstract-test.ts
  src/type/definition.ts
Labels: PR: feature 🚀

#3860 Make print() break long List and Object Values over multiple line
  src/language/__tests__/printer-test.ts
  src/language/printer.ts
Labels: PR: feature 🚀

#3879 gen-changelog: Fix error introduced in #3872
  resources/gen-changelog.ts
Labels: PR: internal 🏠

#3881 simplify schema in defer tests
  src/execution/__tests__/defer-test.ts
Labels: PR: polish 💅

#3880 Testing the right functions in testUtils
  src/__testUtils__/__tests__/expectMatchingValues-test.ts
Labels: PR: polish 💅

#3822 Expose printDirective function to enable schema sharding
  src/index.ts
  src/utilities/index.ts
  src/utilities/printSchema.ts
Labels: PR: feature 🚀

#3882 eslint: replace unmaintained 'node' plugin with it's fork
  .eslintrc.cjs
  integrationTests/webpack/test.js
  package-lock.json
  package.json
Labels: PR: internal 🏠

#3885 remove unnecessary duplicated fields from defer tests
  src/execution/__tests__/defer-test.ts
Labels: PR: polish 💅
