Repository graphql/graphql-js, pull requests merged in 2023-06, with the labels that each got.

#3902 introduce promiseWithResolvers helper
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
  src/jsutils/__tests__/promiseWithResolvers-test.ts
  src/jsutils/promiseWithResolvers.ts
Labels: PR: polish 💅

#3903 execute: move publishing code into separate file
  src/execution/IncrementalPublisher.ts
  src/execution/__tests__/defer-test.ts
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
  src/execution/index.ts
Labels: PR: polish 💅

#3894 introduce new IncrementalPublisher class
  src/execution/IncrementalPublisher.ts
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞

#3923 instanceOf: workaround bundler issue with `process.env`
  src/jsutils/instanceOf.ts
Labels: PR: bug fix 🐞

#3513 Implement OneOf Input Objects via `@oneOf` directive
  src/__testUtils__/kitchenSinkSDL.ts
  src/execution/__tests__/oneof-test.ts
  src/index.ts
  src/language/__tests__/schema-printer-test.ts
  src/type/__tests__/introspection-test.ts
  src/type/__tests__/validation-test.ts
  src/type/definition.ts
  src/type/directives.ts
  src/type/index.ts
  src/type/introspection.ts
  src/type/validate.ts
  src/utilities/__tests__/buildASTSchema-test.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/__tests__/findBreakingChanges-test.ts
  src/utilities/__tests__/printSchema-test.ts
  src/utilities/__tests__/valueFromAST-test.ts
  src/utilities/coerceInputValue.ts
  src/utilities/extendSchema.ts
  src/utilities/valueFromAST.ts
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
  src/validation/__tests__/harness.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
Labels: spec RFC, PR: feature 🚀
