Repository graphql/graphql-js, pull requests merged in 2023-01, with the labels that each got.

#3806 polish: remove misleading comment
  src/execution/execute.ts
Labels: PR: polish 💅

#3816 polish: clarify filtering test semantics
  src/execution/__tests__/stream-test.ts
Labels: PR: polish 💅

#3823 Avoid an before consonant
  src/execution/__tests__/lists-test.ts
  src/language/__tests__/printLocation-test.ts
  src/type/__tests__/definition-test.ts
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/__tests__/printSchema-test.ts
Labels: PR: polish 💅, PR: internal 🏠

#3821 Fix wording of comment in buildClientSchema
  src/utilities/buildClientSchema.ts
Labels: PR: polish 💅

#3837 fix: invalid originalError propagation in custom scalars
  src/execution/__tests__/variables-test.ts
  src/execution/values.ts
Labels: PR: bug fix 🐞
