Repository graphql/graphql-js, pull requests merged in 2024-10, with the labels that each got.

#4217 chore(workspace): lint and format on commit
  .husky/pre-commit
  .lintstagedrc.json
  package-lock.json
  package.json
Labels: PR: polish 💅

#4220 move to separate script
  .husky/pre-commit
  package.json
Labels: PR: internal 🏠

#4222 Include kind in the types
  src/type/__tests__/introspection-test.ts
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/getIntrospectionQuery.ts
Labels: PR: bug fix 🐞

#4214 feat: Allow skipping suggestions
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/execution/values.ts
  src/graphql.ts
  src/type/__tests__/enumType-test.ts
  src/type/definition.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/coerceInputValue.ts
  src/validation/ValidationContext.ts
  src/validation/__tests__/FieldsOnCorrectTypeRule-test.ts
  src/validation/__tests__/KnownArgumentNamesRule-test.ts
  src/validation/__tests__/KnownTypeNamesRule-test.ts
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
  src/validation/__tests__/harness.ts
  src/validation/rules/FieldsOnCorrectTypeRule.ts
  src/validation/rules/KnownArgumentNamesRule.ts
  src/validation/rules/KnownTypeNamesRule.ts
  src/validation/rules/PossibleTypeExtensionsRule.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
  src/validation/validate.ts
Labels: PR: feature 🚀

#4218 improve new leaf type `parseConstLiteral()` method
  integrationTests/ts/kitchenSink-test.ts
  src/execution/__tests__/variables-test.ts
  src/index.ts
  src/type/__tests__/definition-test.ts
  src/type/__tests__/scalars-test.ts
  src/type/definition.ts
  src/type/index.ts
  src/type/scalars.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/coerceInputValue.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
Labels: PR: polish 💅

#4227 Remove the normalized config export
  src/type/definition.ts
Labels: PR: breaking change 💥

#4226 Backport introspection type fix
  src/type/__tests__/introspection-test.ts
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/getIntrospectionQuery.ts
Labels: PR: bug fix 🐞

#4228 Cover empty field-selections
  src/validation/__tests__/ScalarLeafsRule-test.ts
  src/validation/rules/ScalarLeafsRule.ts
Labels: PR: bug fix 🐞

#4231 Add sourcemaps to our published bundles
  resources/build-npm.ts
  tsconfig.json
Labels: PR: polish 💅

#4234 Support symbol properties on extension objects
  src/jsutils/ObjMap.ts
  src/jsutils/toObjMap.ts
  src/type/__tests__/definition-test.ts
  src/type/definition.ts
  src/type/directives.ts
  src/type/schema.ts
Labels: PR: feature 🚀

#4236 fix(replaceVariables): handle missing individual variable source
  src/utilities/__tests__/replaceVariables-test.ts
  src/utilities/replaceVariables.ts
Labels: PR: bug fix 🐞

#4206 polish(ast): prefer undefined over empty arrays
  src/execution/execute.ts
  src/execution/values.ts
  src/language/__tests__/parser-test.ts
  src/language/__tests__/schema-parser-test.ts
  src/language/parser.ts
  src/language/printer.ts
  src/type/__tests__/validation-test.ts
  src/type/validate.ts
  src/utilities/__tests__/buildASTSchema-test.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/__tests__/replaceVariables-test.ts
  src/utilities/extendSchema.ts
  src/validation/rules/KnownArgumentNamesRule.ts
  src/validation/rules/NoUnusedVariablesRule.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
  src/validation/rules/ProvidedRequiredArgumentsRule.ts
  src/validation/rules/UniqueArgumentDefinitionNamesRule.ts
  src/validation/rules/UniqueArgumentNamesRule.ts
  src/validation/rules/UniqueEnumValueNamesRule.ts
  src/validation/rules/UniqueFieldDefinitionNamesRule.ts
  src/validation/rules/UniqueOperationTypesRule.ts
  src/validation/rules/UniqueVariableNamesRule.ts
Labels: PR: breaking change 💥

#4181 Fix/optimize value coercion check for OneOf type
  src/utilities/coerceInputValue.ts
Labels: PR: bug fix 🐞

#4194 move variable position validation for OneOf to `VariablesInAllowedPositionRule`
  src/validation/ValidationContext.ts
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
  src/validation/__tests__/VariablesInAllowedPositionRule-test.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
  src/validation/rules/VariablesInAllowedPositionRule.ts
Labels: PR: bug fix 🐞

#4241 rename serialize and parseValue methods
  integrationTests/ts/kitchenSink-test.ts
  src/execution/__tests__/executor-test.ts
  src/execution/__tests__/variables-test.ts
  src/execution/execute.ts
  src/index.ts
  src/type/__tests__/definition-test.ts
  src/type/__tests__/scalars-test.ts
  src/type/definition.ts
  src/type/index.ts
  src/type/scalars.ts
  src/utilities/__tests__/astFromValue-test.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/astFromValue.ts
  src/utilities/buildClientSchema.ts
  src/utilities/coerceInputValue.ts
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
Labels: PR: feature 🚀

#4244 add permanent flag for schema configuration property assumeValid
  src/type/__tests__/schema-test.ts
  src/type/schema.ts
Labels: PR: bug fix 🐞

#3813 Input Value Validation
  src/execution/__tests__/nonnull-test.ts
  src/execution/__tests__/oneof-test.ts
  src/execution/__tests__/subscribe-test.ts
  src/execution/__tests__/variables-test.ts
  src/execution/values.ts
  src/index.ts
  src/jsutils/printPathArray.ts
  src/type/__tests__/enumType-test.ts
  src/type/definition.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/__tests__/validateInputValue-test.ts
  src/utilities/coerceInputValue.ts
  src/utilities/index.ts
  src/utilities/validateInputValue.ts
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
Labels: PR: breaking change 💥

#4235 Alternative approach for findSchemaChanges
  src/index.ts
  src/utilities/__tests__/findBreakingChanges-test.ts
  src/utilities/__tests__/findSchemaChanges-test.ts
  src/utilities/findSchemaChanges.ts
  src/utilities/index.ts
Labels: PR: feature 🚀

#4250 AbortController support
  integrationTests/ts/tsconfig.json
  package-lock.json
  package.json
  src/execution/__tests__/abort-signal-test.ts
  src/execution/execute.ts
  src/graphql.ts
Labels: PR: feature 🚀

#4259 fix: abortion should not cause incremental completion error
  src/execution/__tests__/abort-signal-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞

#4258 fix: handle default and different types passed to abort method
  src/execution/__tests__/abort-signal-test.ts
  src/execution/execute.ts
Labels: PR: bug fix 🐞

#3814 RFC: Default value validation & coercion
  cspell.yml
  src/execution/__tests__/variables-test.ts
  src/index.ts
  src/type/__tests__/enumType-test.ts
  src/type/__tests__/validation-test.ts
  src/type/introspection.ts
  src/type/validate.ts
  src/utilities/__tests__/astFromValue-test.ts
  src/utilities/astFromValue.ts
  src/utilities/coerceInputValue.ts
  src/utilities/findSchemaChanges.ts
  src/utilities/index.ts
  src/utilities/printSchema.ts
Labels: PR: breaking change 💥, spec RFC

#4261 feat: pass abortSignal to resolvers
  src/execution/__tests__/abort-signal-test.ts
  src/execution/execute.ts
  src/type/definition.ts
Labels: PR: feature 🚀

#4265 use object for GraphQLWrappedResult instead of tuple
  src/execution/execute.ts
Labels: PR: polish 💅

#4254 Remove typescript enums in favor of plain JS/TS solution
  src/language/ast.ts
  src/language/directiveLocation.ts
  src/language/kinds.ts
  src/language/tokenKind.ts
  src/type/introspection.ts
  src/utilities/findSchemaChanges.ts
  src/utilities/getIntrospectionQuery.ts
Labels: PR: polish 💅
