Repository graphql/graphql-js, pull requests merged in 2024-06, with the labels that each got.

#4104 Fix publish scripts
  package.json
  resources/checkgit.sh
Labels: PR: internal 🏠

#4098 incremental: handle Stream as stream rather than linked list
  src/execution/IncrementalGraph.ts
  src/execution/__tests__/stream-test.ts
  src/execution/execute.ts
  src/execution/types.ts
Labels: PR: polish 💅

#4106 polish(IncrementalPublisher): remove unnecessary check and method call
  src/execution/IncrementalPublisher.ts
Labels: PR: polish 💅

#4018 Enable passing values configuration to GraphQLEnumType as a thunk
  src/type/__tests__/enumType-test.ts
  src/type/definition.ts
Labels: PR: feature 🚀

#4000 Backport "Prevent Infinite Loop in OverlappingFieldsCanBeMergedRule" to v15
  src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.js
  src/validation/rules/OverlappingFieldsCanBeMergedRule.js
Labels: PR: bug fix 🐞

#4078 Add `@oneOf` support to introspection query
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/__tests__/getIntrospectionQuery-test.ts
  src/utilities/buildClientSchema.ts
  src/utilities/getIntrospectionQuery.ts
  src/utilities/introspectionFromSchema.ts
Labels: PR: feature 🚀

#4124 backport[v16]: Implement OneOf Input Objects via `@oneOf` directive
  src/__testUtils__/kitchenSinkSDL.ts
  src/execution/__tests__/oneof-test.ts
  src/index.ts
  src/language/__tests__/schema-printer-test.ts
  src/type/__tests__/introspection-test.ts
  src/type/__tests__/validation-test.ts
  src/type/definition.ts
  src/type/directives.ts
  src/type/index.ts
  src/type/introspection.ts
  src/type/validate.ts
  src/utilities/__tests__/buildASTSchema-test.ts
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/__tests__/findBreakingChanges-test.ts
  src/utilities/__tests__/getIntrospectionQuery-test.ts
  src/utilities/__tests__/printSchema-test.ts
  src/utilities/__tests__/valueFromAST-test.ts
  src/utilities/buildClientSchema.ts
  src/utilities/coerceInputValue.ts
  src/utilities/extendSchema.ts
  src/utilities/getIntrospectionQuery.ts
  src/utilities/introspectionFromSchema.ts
  src/utilities/printSchema.ts
  src/utilities/valueFromAST.ts
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
  src/validation/__tests__/harness.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
Labels: PR: feature 🚀

#4125 Rename `inputObjectOneOf` to `oneOf` in `getIntrospectionQuery()`
  src/utilities/__tests__/getIntrospectionQuery-test.ts
  src/utilities/getIntrospectionQuery.ts
  src/utilities/introspectionFromSchema.ts
Labels: PR: bug fix 🐞

#4126 backport(v15): fix publish scripts
  package.json
  resources/checkgit.sh
Labels: PR: internal 🏠

#4108 polish(incremental): refactor getNewPending functionality
  src/execution/IncrementalGraph.ts
  src/execution/IncrementalPublisher.ts
Labels: PR: polish 💅

#4112 refactor(incremental): simplify incremental graph by allowing mutations
  src/execution/IncrementalGraph.ts
  src/execution/execute.ts
  src/execution/types.ts
Labels: PR: polish 💅
