Repository graphql/graphql-js, pull requests merged in 2024-11, with the labels that each got.

#4273 polish: refactor execution plan functions to match spec
  src/execution/execute.ts
Labels: PR: polish 💅

#4263 stop resolvers after execution ends
  src/execution/__tests__/nonnull-test.ts
  src/execution/execute.ts
Labels: PR: feature 🚀

#4275 Add safe schema change for descriptions changing
  src/utilities/__tests__/findSchemaChanges-test.ts
  src/utilities/findSchemaChanges.ts
Labels: PR: feature 🚀

#4279 Solve some low hanging fruit in the documentation
  website/pages/execution.mdx
  website/pages/graphql.mdx
  website/pages/type.mdx
Labels: PR: docs 📝

#4277 Detect directive argument changes
  src/utilities/__tests__/findSchemaChanges-test.ts
  src/utilities/findSchemaChanges.ts
Labels: PR: feature 🚀

#4274 add cancellation support to async iterable iteration
  src/execution/PromiseCanceller.ts
  src/execution/__tests__/PromiseCanceller-test.ts
  src/execution/__tests__/abort-signal-test.ts
  src/execution/__tests__/mapAsyncIterable-test.ts
  src/execution/execute.ts
  src/execution/mapAsyncIterable.ts
Labels: PR: feature 🚀

#4282 rename PromiseCanceller to AbortSignalListener
  src/execution/AbortSignalListener.ts
  src/execution/IncrementalPublisher.ts
  src/execution/PromiseCanceller.ts
  src/execution/__tests__/AbortSignalListener-test.ts
  src/execution/__tests__/PromiseCanceller-test.ts
  src/execution/__tests__/cancellation-test.ts
  src/execution/execute.ts
Labels: PR: polish 💅

#4286 fix: properly type `extensions` in GraphQLFormattedError
  src/error/GraphQLError.ts
  src/error/index.ts
  src/index.ts
Labels: PR: feature 🚀

#4292 Expose tokenCount on the DocumentNode
  src/language/__tests__/parser-test.ts
  src/language/ast.ts
  src/language/parser.ts
Labels: PR: feature 🚀

#4291 Address empty selection-set
  src/validation/__tests__/ScalarLeafsRule-test.ts
  src/validation/rules/ScalarLeafsRule.ts
Labels: PR: bug fix 🐞

#4294 polish: fix lexer state comment
  src/language/lexer.ts
Labels: PR: polish 💅

#4304 internal: update CONTRIBUTING guide
  .github/CONTRIBUTING.md
Labels: PR: internal 🏠
