Repository graphql/graphql-js, pull requests merged in 2024-09, with the labels that each got.

#4176 improve errors around around dots
  src/language/__tests__/lexer-test.ts
  src/language/lexer.ts
Labels: PR: bug fix 🐞

#4177 standardize error messages prior to introducing schema coordinates
  src/execution/__tests__/variables-test.ts
  src/execution/execute.ts
  src/execution/values.ts
  src/type/__tests__/introspection-test.ts
  src/type/__tests__/validation-test.ts
  src/type/validate.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/__tests__/findBreakingChanges-test.ts
  src/utilities/coerceInputValue.ts
  src/utilities/findBreakingChanges.ts
  src/utilities/printSchema.ts
  src/validation/__tests__/DeferStreamDirectiveLabelRule-test.ts
  src/validation/__tests__/NoDeprecatedCustomRule-test.ts
  src/validation/__tests__/ProvidedRequiredArgumentsRule-test.ts
  src/validation/__tests__/StreamDirectiveOnListFieldRule-test.ts
  src/validation/__tests__/ValuesOfCorrectTypeRule-test.ts
  src/validation/rules/DeferStreamDirectiveLabelRule.ts
  src/validation/rules/DeferStreamDirectiveOnRootFieldRule.ts
  src/validation/rules/FieldsOnCorrectTypeRule.ts
  src/validation/rules/KnownArgumentNamesRule.ts
  src/validation/rules/ProvidedRequiredArgumentsRule.ts
  src/validation/rules/StreamDirectiveOnListFieldRule.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
  src/validation/rules/custom/NoDeprecatedCustomRule.ts
Labels: PR: bug fix 🐞

#4172 Add flexibility around the waiting period for merging PRs
  .github/CONTRIBUTING.md
Labels: PR: internal 🏠

#4166 chore(deps): upgrade dependencies
  .eslintrc.cjs
  benchmark/fixtures.js
  benchmark/github-schema.graphql
  cspell.yml
  integrationTests/node/test.js
  integrationTests/ts/package.json
  integrationTests/ts/test.js
  integrationTests/webpack/test.js
  package-lock.json
  package.json
  resources/build-deno.ts
  resources/build-npm.ts
  resources/diff-npm-package.ts
  resources/eslint-internal-rules/no-dir-import.js
  resources/gen-version.ts
  resources/utils.ts
  src/__testUtils__/__tests__/expectPromise-test.ts
  src/execution/IncrementalPublisher.ts
  src/execution/__tests__/executor-test.ts
  src/execution/__tests__/mapAsyncIterable-test.ts
  src/execution/__tests__/simplePubSub.ts
  src/execution/__tests__/stream-test.ts
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/jsutils/invariant.ts
  src/language/ast.ts
  src/language/lexer.ts
  src/language/predicates.ts
  src/language/visitor.ts
  src/type/__tests__/enumType-test.ts
  src/type/introspection.ts
  src/utilities/__tests__/stripIgnoredCharacters-fuzz.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
  website/docusaurus.config.cjs
Labels: PR: polish 💅

#4187 remove deprecated custom typeInfo arg for validate()
  src/validation/__tests__/validation-test.ts
  src/validation/validate.ts
Labels: PR: breaking change 💥

#4185 fix(IntrospectionType): properly type using TypeKind enum
  src/utilities/buildClientSchema.ts
  src/utilities/getIntrospectionQuery.ts
Labels: PR: breaking change 💥

#4184 update comments regarding fragment arguments and variables
  src/language/ast.ts
Labels: PR: polish 💅

#4191 chore(deps): remove prettier-ignore
  src/type/definition.ts
Labels: PR: polish 💅

#3809 Add coerceInputLiteral()
  src/execution/getVariableSignature.ts
  src/execution/values.ts
  src/index.ts
  src/language/parser.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/__tests__/valueFromAST-test.ts
  src/utilities/buildClientSchema.ts
  src/utilities/coerceInputValue.ts
  src/utilities/extendSchema.ts
  src/utilities/index.ts
  src/utilities/valueFromAST.ts
  src/utilities/valueFromASTUntyped.ts
Labels: PR: feature 🚀

#4168 fix(validation): catch OverlappingFieldsCanBeMergedRule violations with nested fragments
  src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Labels: PR: bug fix 🐞

#4199 fix(validation): catch OverlappingFieldsCanBeMergedRule violations with nested fragments (#4168)
  src/validation/__tests__/OverlappingFieldsCanBeMergedRule-test.ts
  src/validation/rules/OverlappingFieldsCanBeMergedRule.ts
Labels: PR: bug fix 🐞

#3810 Preserve defaultValue literals
  src/execution/getVariableSignature.ts
  src/execution/values.ts
  src/index.ts
  src/type/__tests__/definition-test.ts
  src/type/__tests__/predicate-test.ts
  src/type/definition.ts
  src/type/index.ts
  src/type/introspection.ts
  src/utilities/TypeInfo.ts
  src/utilities/__tests__/buildClientSchema-test.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/buildClientSchema.ts
  src/utilities/coerceInputValue.ts
  src/utilities/extendSchema.ts
  src/utilities/findBreakingChanges.ts
  src/utilities/printSchema.ts
  src/utilities/valueFromAST.ts
  src/validation/ValidationContext.ts
  src/validation/rules/VariablesInAllowedPositionRule.ts
Labels: PR: breaking change 💥

#3775 Improve directive tests
  src/validation/__tests__/KnownDirectivesRule-test.ts
Labels: PR: polish 💅

#3811 Preserve sources of variable values
  src/execution/__tests__/executor-test.ts
  src/execution/collectFields.ts
  src/execution/execute.ts
  src/execution/values.ts
  src/type/definition.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/coerceInputValue.ts
  src/validation/rules/SingleFieldSubscriptionsRule.ts
Labels: PR: breaking change 💥

#3812 Add valueToLiteral()
  integrationTests/ts/kitchenSink-test.ts
  src/execution/__tests__/variables-test.ts
  src/index.ts
  src/type/__tests__/definition-test.ts
  src/type/__tests__/scalars-test.ts
  src/type/definition.ts
  src/type/scalars.ts
  src/utilities/__tests__/coerceInputValue-test.ts
  src/utilities/__tests__/replaceVariables-test.ts
  src/utilities/__tests__/valueToLiteral-test.ts
  src/utilities/coerceInputValue.ts
  src/utilities/index.ts
  src/utilities/replaceVariables.ts
  src/utilities/valueToLiteral.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
Labels: PR: feature 🚀

#4209 improve upgrade path for new custom scalar `parseConstLiteral()` method
  src/type/__tests__/definition-test.ts
  src/type/__tests__/scalars-test.ts
  src/type/definition.ts
  src/utilities/coerceInputValue.ts
  src/validation/rules/ValuesOfCorrectTypeRule.ts
Labels: PR: breaking change 💥
