Repository graphql/graphql-js, pull requests merged in 2025-01, with the labels that each got.

#4326 Re-export GraphQLFormattedError as type
  src/error/formatError.js
Labels: PR: bug fix 🐞

#4335 Add cspell exception
  cspell.yml
Labels: PR: docs 📝

#4312 Increase print/visit performance
  benchmark/fixtures.js
  benchmark/kitchen-sink.graphql
  benchmark/printer-benchmark.js
  src/language/visitor.ts
Labels: PR: polish 💅
